// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Internal.Docs {
    internal static partial class CPUInfo {
        /// <summary>
        /// <para>Determine the L1 cache line size of the CPU.</para>
        /// </summary>
        /// <remarks>
        /// <para>This is useful for determining multi-threaded structure padding or SIMD prefetch sizes.</para>
        /// </remarks>
        /// <returns>
        /// <para>(int) Returns the L1 cache line size of the CPU, in bytes.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetCPUCacheLineSize">SDL_GetCPUCacheLineSize</seealso></SDLWiki>
        public static extern void GetCPUCacheLineSize();

        /// <summary>
        /// <para>Get the number of logical CPU cores available.</para>
        /// </summary>
        /// <returns>
        /// <para>(int) Returns the total number of logical CPU cores. On CPUs that include technologies such as hyperthreading, the number of logical cores may be more than the number of physical cores.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetNumLogicalCPUCores">SDL_GetNumLogicalCPUCores</seealso></SDLWiki>
        public static extern void GetNumLogicalCPUCores();

        /// <summary>
        /// <para>Report the alignment this system needs for SIMD allocations.</para>
        /// </summary>
        /// <remarks>
        /// <para>This will return the minimum number of bytes to which a pointer must be aligned to be compatible with SIMD instructions on the current machine. For example, if the machine supports SSE only, it will return 16, but if it supports AVX-512F, it'll return 64 (etc). This only reports values for instruction sets SDL knows about, so if your SDL build doesn't have <see cref="CSDL.CPUInfo.HasAVX512F">HasAVX512F</see>, then it might return 16 for the SSE support it sees and not 64 for the AVX-512 instructions that exist but SDL doesn't know about. Plan accordingly.</para>
        /// </remarks>
        /// <returns>
        /// <para>(size_t) Returns the alignment in bytes needed for available, known SIMD instructions.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetSIMDAlignment">SDL_GetSIMDAlignment</seealso></SDLWiki>
        /// <seealso><c>SDL_aligned_alloc</c></seealso>
        /// <seealso><c>SDL_aligned_free</c></seealso>
        public static extern void GetSIMDAlignment();

        /// <summary>
        /// <para>Report the size of a page of memory.</para>
        /// </summary>
        /// <remarks>
        /// <para>Different platforms might have different memory page sizes. In current times, 4 kilobytes is not unusual, but newer systems are moving to larger page sizes, and esoteric platforms might have any unexpected size.</para>
        /// <para>Note that this function can return 0, which means SDL can't determine the page size on this platform. It will _not_ set an error string to be retrieved with <see cref="CSDL.Error.GetError">GetError</see> in this case! In this case, defaulting to 4096 is often a reasonable option.</para>
        /// </remarks>
        /// <returns>
        /// <para>(int) Returns the size of a single page of memory, in bytes, or 0 if SDL can't determine this information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.4.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetSystemPageSize">SDL_GetSystemPageSize</seealso></SDLWiki>
        public static extern void GetSystemPageSize();

        /// <summary>
        /// <para>Get the amount of RAM configured in the system.</para>
        /// </summary>
        /// <returns>
        /// <para>(int) Returns the amount of RAM configured in the system in MiB.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetSystemRAM">SDL_GetSystemRAM</seealso></SDLWiki>
        public static extern void GetSystemRAM();

        /// <summary>
        /// <para>Determine whether the CPU has AltiVec features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using PowerPC instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has AltiVec features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasAltiVec">SDL_HasAltiVec</seealso></SDLWiki>
        public static extern void HasAltiVec();

        /// <summary>
        /// <para>Determine whether the CPU has ARM SIMD (ARMv6) features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This is different from ARM NEON, which is a different instruction set.</para>
        /// <para>This always returns false on CPUs that aren't using ARM instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has ARM SIMD features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasARMSIMD">SDL_HasARMSIMD</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.CPUInfo.HasNEON">HasNEON</see></seealso>
        public static extern void HasARMSIMD();

        /// <summary>
        /// <para>Determine whether the CPU has AVX features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using Intel instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has AVX features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasAVX">SDL_HasAVX</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.CPUInfo.HasAVX2">HasAVX2</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasAVX512F">HasAVX512F</see></seealso>
        public static extern void HasAVX();

        /// <summary>
        /// <para>Determine whether the CPU has AVX2 features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using Intel instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has AVX2 features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasAVX2">SDL_HasAVX2</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.CPUInfo.HasAVX">HasAVX</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasAVX512F">HasAVX512F</see></seealso>
        public static extern void HasAVX2();

        /// <summary>
        /// <para>Determine whether the CPU has AVX-512F (foundation) features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using Intel instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has AVX-512F features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasAVX512F">SDL_HasAVX512F</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.CPUInfo.HasAVX">HasAVX</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasAVX2">HasAVX2</see></seealso>
        public static extern void HasAVX512F();

        /// <summary>
        /// <para>Determine whether the CPU has LASX (LOONGARCH SIMD) features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using LOONGARCH instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has LOONGARCH LASX features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasLASX">SDL_HasLASX</seealso></SDLWiki>
        public static extern void HasLASX();

        /// <summary>
        /// <para>Determine whether the CPU has LSX (LOONGARCH SIMD) features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using LOONGARCH instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has LOONGARCH LSX features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasLSX">SDL_HasLSX</seealso></SDLWiki>
        public static extern void HasLSX();

        /// <summary>
        /// <para>Determine whether the CPU has MMX features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using Intel instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has MMX features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasMMX">SDL_HasMMX</seealso></SDLWiki>
        public static extern void HasMMX();

        /// <summary>
        /// <para>Determine whether the CPU has NEON (ARM SIMD) features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using ARM instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has ARM NEON features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasNEON">SDL_HasNEON</seealso></SDLWiki>
        public static extern void HasNEON();

        /// <summary>
        /// <para>Determine whether the CPU has SSE features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using Intel instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has SSE features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasSSE">SDL_HasSSE</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE2">HasSSE2</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE3">HasSSE3</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE41">HasSSE41</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE42">HasSSE42</see></seealso>
        public static extern void HasSSE();

        /// <summary>
        /// <para>Determine whether the CPU has SSE2 features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using Intel instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has SSE2 features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasSSE2">SDL_HasSSE2</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE">HasSSE</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE3">HasSSE3</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE41">HasSSE41</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE42">HasSSE42</see></seealso>
        public static extern void HasSSE2();

        /// <summary>
        /// <para>Determine whether the CPU has SSE3 features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using Intel instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has SSE3 features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasSSE3">SDL_HasSSE3</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE">HasSSE</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE2">HasSSE2</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE41">HasSSE41</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE42">HasSSE42</see></seealso>
        public static extern void HasSSE3();

        /// <summary>
        /// <para>Determine whether the CPU has SSE4.1 features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using Intel instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has SSE4.1 features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasSSE41">SDL_HasSSE41</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE">HasSSE</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE2">HasSSE2</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE3">HasSSE3</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE42">HasSSE42</see></seealso>
        public static extern void HasSSE41();

        /// <summary>
        /// <para>Determine whether the CPU has SSE4.2 features.</para>
        /// </summary>
        /// <remarks>
        /// <para>This always returns false on CPUs that aren't using Intel instruction sets.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has SSE4.2 features or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasSSE42">SDL_HasSSE42</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE">HasSSE</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE2">HasSSE2</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE3">HasSSE3</see></seealso>
        /// <seealso><see cref="CSDL.CPUInfo.HasSSE41">HasSSE41</see></seealso>
        public static extern void HasSSE42();

        /// <summary>
        /// <para>Determine whether the CPU has SVE2 (Scalable Vector Extension 2).</para>
        /// </summary>
        /// <remarks>
        /// <para>This is only relevant on ARM64 Linux. On other platforms it always returns false.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if the CPU has SVE2, false otherwise.</para>
        /// </returns>
        /// <since>This function is available since SDL 3.6.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasSVE2">SDL_HasSVE2</seealso></SDLWiki>
        public static extern void HasSVE2();
    }
}
