// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>An entry for filters for file dialogs.</para>
    /// </summary>
    /// <remarks>
    /// <para><see cref="Name"/> is a user-readable label for the filter (for example, "Office document").</para>
    /// <para><see cref="Pattern"/> is a semicolon-separated list of file extensions (for example, "doc;docx"). File extensions may only contain alphanumeric characters, hyphens, underscores and periods. Alternatively, the whole string can be a single asterisk ("*"), which serves as an "All files" filter.</para>
    /// </remarks>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_DialogFileFilter">SDL_DialogFileFilter</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.FileDialog.FileCallback">FileCallback</see></seealso>
    /// <seealso><see cref="CSDL.FileDialog.ShowOpenFile">ShowOpenFile</see></seealso>
    /// <seealso><see cref="CSDL.FileDialog.ShowSaveFile">ShowSaveFile</see></seealso>
    /// <seealso><see cref="CSDL.FileDialog.ShowOpenFolder">ShowOpenFolder</see></seealso>
    /// <seealso><see cref="CSDL.FileDialog.Show">Show</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct DialogFileFilter {
        private nint _name;

        public string Name => Marshal.PtrToStringUTF8(_name);

        private nint _pattern;

        public string Pattern => Marshal.PtrToStringUTF8(_pattern);
    }
}
