// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>A struct to provide locale data.</para>
    /// </summary>
    /// <remarks>
    /// <para>Locale data is split into a spoken language, like English, and an optional country, like Canada.</para>
    /// <para>Language strings are ISO-639 language specifiers (such as "en" for English, "de" for German, etc). Country strings are ISO-3166 country codes (such as "US" for the United States, "CA" for Canada, etc). The country might be NULL if there's no specific guidance on them (so you might have <c>{ "en", "US" }</c> for American English, but <c>{ "en", NULL }</c> means "English language, generically"). Language strings are never NULL.</para>
    /// <para>Please note that not all of these strings are 2 characters; some are three or more.</para>
    /// </remarks>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_Locale">SDL_Locale</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Locales.Preferred">Preferred</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Locale {
        /// <summary>
        /// <para>A language name, like "en" for English.</para>
        /// </summary>
        private nint _language;

        public string Language => Marshal.PtrToStringUTF8(_language);

        /// <summary>
        /// <para>A country, like "US" for America. Can be NULL.</para>
        /// </summary>
        private nint _country;

        public string Country => Marshal.PtrToStringUTF8(_country);
    }
}
