// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>MessageBox structure containing title, text, window, etc.</para>
    /// </summary>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MessageBoxData">SDL_MessageBoxData</seealso></SDLWiki>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct MessageBoxData {
        public CSDL.MessageBoxFlags Flags;

        /// <summary>
        /// <para>Parent window, can be NULL</para>
        /// </summary>
        public nint Window;

        /// <summary>
        /// <para>UTF-8 title</para>
        /// </summary>
        private nint _title;

        public string Title => Marshal.PtrToStringUTF8(_title);

        /// <summary>
        /// <para>UTF-8 message text</para>
        /// </summary>
        private nint _message;

        public string Message => Marshal.PtrToStringUTF8(_message);

        public int Numbuttons;

        public nint Buttons;

        /// <summary>
        /// <para>SDL_MessageBoxColorScheme, can be NULL to use system settings</para>
        /// </summary>
        public nint ColorScheme;
    }
}
