// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Internal.Docs {
    public static partial class Misc {
        /// <summary>
        /// <para>Open a URL/URI in the browser or other appropriate external application.</para>
        /// </summary>
        /// <remarks>
        /// <para>Open a URL in a separate, system-provided application. How this works will vary wildly depending on the platform. This will likely launch what makes sense to handle a specific URL's protocol (a web browser for <a href="http://">http://</a>, etc), but it might also be able to launch file managers for directories and other things.</para>
        /// <para>What happens when you open a URL varies wildly as well: your game window may lose focus (and may or may not lose focus if your game was fullscreen or grabbing input at the time). On mobile devices, your app will likely move to the background or your process might be paused. Any given platform may or may not handle a given URL.</para>
        /// <para>If this is unimplemented (or simply unavailable) for a platform, this will fail with an error. A successful result does not mean the URL loaded, just that we launched _something_ to handle it (or at least believe we did).</para>
        /// <para>All this to say: this function can be useful, but you should definitely test it on every platform you target.</para>
        /// </remarks>
        /// <param name="url">a valid URL/URI to open. Use <c>file:///full/path/to/file</c> for local files, if supported.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>This function should only be called on the main thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_OpenURL">SDL_OpenURL</seealso></SDLWiki>
        public static extern void OpenURL();
    }
}
