// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL {
    /// <summary>
    /// <para>The basic state for the system's power supply.</para>
    /// </summary>
    /// <remarks>
    /// <para>These are results returned by <see cref="CSDL.Power.State">State</see>.</para>
    /// </remarks>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PowerState">SDL_PowerState</seealso></SDLWiki>
    public enum PowerState {
        /// <summary>
        /// <para>error determining power status</para>
        /// </summary>
        Error = -1,
        /// <summary>
        /// <para>cannot determine power status</para>
        /// </summary>
        Unknown,
        /// <summary>
        /// <para>Not plugged in, running on the battery</para>
        /// </summary>
        OnBattery,
        /// <summary>
        /// <para>Plugged in, no battery available</para>
        /// </summary>
        NoBattery,
        /// <summary>
        /// <para>Plugged in, charging battery</para>
        /// </summary>
        Charging,
        /// <summary>
        /// <para>Plugged in, battery charged</para>
        /// </summary>
        Charged,
    }
}
