// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Internal.Docs {
    internal static partial class Power {
        /// <summary>
        /// <para>Get the current power supply details.</para>
        /// </summary>
        /// <remarks>
        /// <para>You should never take a battery status as absolute truth. Batteries (especially failing batteries) are delicate hardware, and the values reported here are best estimates based on what that hardware reports. It's not uncommon for older batteries to lose stored power much faster than it reports, or completely drain when reporting it has 20 percent left, etc.</para>
        /// <para>Battery status can change at any time; if you are concerned with power state, you should call this function frequently, and perhaps ignore changes until they seem to be stable for a few seconds.</para>
        /// <para>It's possible a platform can only report battery percentage or time left but not both.</para>
        /// <para>On some platforms, retrieving power supply details might be expensive. If you want to display continuous status you could call this function every minute or so.</para>
        /// </remarks>
        /// <param name="seconds">a pointer filled in with the seconds of battery life left, or NULL to ignore. This will be filled in with -1 if we can't determine a value or there is no battery.</param>
        /// <param name="percent">a pointer filled in with the percentage of battery life left, between 0 and 100, or NULL to ignore. This will be filled in with -1 when we can't determine a value or there is no battery.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.PowerState">PowerState</see>) Returns the current battery state or <see cref="CSDL.PowerState.Error">Error</see> on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>This function is not thread safe.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetPowerInfo">SDL_GetPowerInfo</seealso></SDLWiki>
        public static extern void GetPowerInfo();
    }
}
