// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL {
    internal static partial class SDL {
        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateProcess"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlProcess> CreateProcess(NativePtr<nint> args, CBool pipeStdio);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateProcessWithProperties"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlProcess> CreateProcessWithProperties(CSDL.PropertiesID props);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_DestroyProcess"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void DestroyProcess(NativePtr<CSDL.Opaque.SdlProcess> process);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetProcessInput"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlIOStream> GetProcessInput(NativePtr<CSDL.Opaque.SdlProcess> process);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetProcessOutput"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlIOStream> GetProcessOutput(NativePtr<CSDL.Opaque.SdlProcess> process);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetProcessProperties"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.PropertiesID GetProcessProperties(NativePtr<CSDL.Opaque.SdlProcess> process);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_KillProcess"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool KillProcess(NativePtr<CSDL.Opaque.SdlProcess> process, CBool force);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadProcess"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial IntPtr ReadProcess(NativePtr<CSDL.Opaque.SdlProcess> process, out nuint datasize, out int exitcode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WaitProcess"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WaitProcess(NativePtr<CSDL.Opaque.SdlProcess> process, CBool block, out int exitcode);

    }
}
