// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL3-CS / SDL definitions.


using System.Runtime.InteropServices;

namespace CSDL {
    public static partial class Macros {
        /// <summary>
        /// <para>Epsilon constant, used for comparing floating-point numbers.</para>
        /// </summary>
        /// <remarks>
        /// <para>Equals by default to platform-defined <c>FLT_EPSILON</c>, or <c>1.1920928955078125e-07F</c> if that's not available.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_FLT_EPSILON">SDL_FLT_EPSILON</seealso></SDLWiki>
        public const float FltEpsilon = 1.1920928955078125e-07F;

        /// <summary>
        /// <para>The Unicode REPLACEMENT CHARACTER codepoint.</para>
        /// </summary>
        /// <remarks>
        /// <para><c>SDL_StepUTF8</c> and <c>SDL_StepBackUTF8</c> report this codepoint when they encounter a UTF-8 string with encoding errors.</para>
        /// <para>This tends to render as something like a question mark in most places.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_INVALID_UNICODE_CODEPOINT">SDL_INVALID_UNICODE_CODEPOINT</seealso></SDLWiki>
        /// <seealso><c>SDL_StepBackUTF8</c></seealso>
        /// <seealso><c>SDL_StepUTF8</c></seealso>
        public const uint InvalidUnicodeCodepoint = 0xFFFD;

        /// <summary>
        /// <para>Don't let SDL use "long long" C types.</para>
        /// </summary>
        /// <remarks>
        /// <para>SDL will define this if it believes the compiler doesn't understand the "long long" syntax for C datatypes. This can happen on older compilers.</para>
        /// <para>If _your_ compiler doesn't support "long long" but SDL doesn't know it, it is safe to define this yourself to build against the SDL headers.</para>
        /// <para>If this is defined, it will remove access to some C runtime support functions, like <c>SDL_ulltoa</c> and <c>SDL_strtoll</c> that refer to this datatype explicitly. The rest of SDL will still be available.</para>
        /// <para>SDL's own source code cannot be built with a compiler that has this defined, for various technical reasons.</para>
        /// </remarks>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_NOLONGLONG">SDL_NOLONGLONG</seealso></SDLWiki>
        public const uint Nolonglong = 1;

        /// <summary>
        /// <para>The value of Pi, as a double-precision floating point literal.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PI_D">SDL_PI_D</seealso></SDLWiki>
        /// <seealso><c>SDL_PI_F</c></seealso>
        public const double PiD = 3.141592653589793238462643383279502884;

        /// <summary>
        /// <para>The value of Pi, as a single-precision floating point literal.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PI_F">SDL_PI_F</seealso></SDLWiki>
        /// <seealso><c>SDL_PI_D</c></seealso>
        public const float PiF = 3.141592653589793238462643383279502884F;

        /// <summary>
        /// <para>A printf-formatting string for an <c>unsigned long long</c> value as upper-case hexadecimal.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRILLX " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRILLX">SDL_PRILLX</seealso></SDLWiki>
        public const string Prillx = PrillPrefix + "X";

        /// <summary>
        /// <para>A printf-formatting string prefix for a <c>long long</c> value.</para>
        /// </summary>
        /// <remarks>
        /// <para>This is just the prefix! You probably actually want <c>SDL_PRILLd</c>, <c>SDL_PRILLu</c>, <c>SDL_PRILLx</c>, or <c>SDL_PRILLX</c> instead.</para>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRILL_PREFIX "d bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRILL_PREFIX">SDL_PRILL_PREFIX</seealso></SDLWiki>
        public const string PrillPrefix = "ll";

        /// <summary>
        /// <para>A printf-formatting string for a <c>long long</c> value.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRILLd " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRILLd">SDL_PRILLd</seealso></SDLWiki>
        public const string PrilLd = PrillPrefix + "d";

        /// <summary>
        /// <para>A printf-formatting string for a <c>unsigned long long</c> value.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRILLu " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRILLu">SDL_PRILLu</seealso></SDLWiki>
        public const string PrilLu = PrillPrefix + "u";

        /// <summary>
        /// <para>A printf-formatting string for an <c>unsigned long long</c> value as lower-case hexadecimal.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRILLx " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRILLx">SDL_PRILLx</seealso></SDLWiki>
        public const string PrilLx = PrillPrefix + "x";

        /// <summary>
        /// <para>A printf-formatting string for an <c>size_t</c> value as upper-case hexadecimal.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRISZX " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.6.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRISZX">SDL_PRISZX</seealso></SDLWiki>
        public const string Priszx = PriszPrefix + "X";

        /// <summary>
        /// <para>A printf-formatting string prefix for a <c>size_t</c> value.</para>
        /// </summary>
        /// <remarks>
        /// <para>This is just the prefix! You probably actually want <c>SDL_PRISZu</c>, <c>SDL_PRISZx</c>, or <c>SDL_PRISZX</c> instead.</para>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRISZ_PREFIX "u bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.6.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRISZ_PREFIX">SDL_PRISZ_PREFIX</seealso></SDLWiki>
        public const string PriszPrefix = "z";

        /// <summary>
        /// <para>A printf-formatting string for a <c>size_t</c> value.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRISZu " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.6.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRISZu">SDL_PRISZu</seealso></SDLWiki>
        public const string PrisZu = PriszPrefix + "u";

        /// <summary>
        /// <para>A printf-formatting string for an <c>size_t</c> value as lower-case hexadecimal.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRISZx " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.6.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRISZx">SDL_PRISZx</seealso></SDLWiki>
        public const string PrisZx = PriszPrefix + "x";

        /// <summary>
        /// <para>A printf-formatting string for a <c>Uint32</c> value as upper-case hexadecimal.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRIX32 " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRIX32">SDL_PRIX32</seealso></SDLWiki>
        public const string Prix32 = "X";

        /// <summary>
        /// <para>A printf-formatting string for a <c>Uint64</c> value as upper-case hexadecimal.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRIX64 " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRIX64">SDL_PRIX64</seealso></SDLWiki>
        public const string Prix64 = "llX";

        /// <summary>
        /// <para>A printf-formatting string for an <c>Sint32</c> value.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRIs32 " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRIs32">SDL_PRIs32</seealso></SDLWiki>
        public const string PrIs32 = "d";

        /// <summary>
        /// <para>A printf-formatting string for an <c>Sint64</c> value.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRIs64 " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRIs64">SDL_PRIs64</seealso></SDLWiki>
        public const string PrIs64 = "lld";

        /// <summary>
        /// <para>A printf-formatting string for a <c>Uint32</c> value.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRIu32 " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRIu32">SDL_PRIu32</seealso></SDLWiki>
        public const string PrIu32 = "u";

        /// <summary>
        /// <para>A printf-formatting string for a <c>Uint64</c> value.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRIu64 " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRIu64">SDL_PRIu64</seealso></SDLWiki>
        public const string PrIu64 = "llu";

        /// <summary>
        /// <para>A printf-formatting string for a <c>Uint32</c> value as lower-case hexadecimal.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRIx32 " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRIx32">SDL_PRIx32</seealso></SDLWiki>
        public const string PrIx32 = "x";

        /// <summary>
        /// <para>A printf-formatting string for a <c>Uint64</c> value as lower-case hexadecimal.</para>
        /// </summary>
        /// <remarks>
        /// <para>Use it like this:</para>
        /// <para>``<c>c SDL_Log("There are %" SDL_PRIx64 " bottles of beer on the wall.", bottles);</c>``</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PRIx64">SDL_PRIx64</seealso></SDLWiki>
        public const string PrIx64 = "llx";

        /// <summary>
        /// <para>The largest value that a <c>size_t</c> can hold for the target platform.</para>
        /// </summary>
        /// <remarks>
        /// <para><c>size_t</c> is generally the same size as a pointer in modern times, but this can get weird on very old and very esoteric machines. For example, on a 16-bit Intel 286, you might have a 32-bit "far" pointer (16-bit segment plus 16-bit offset), but <c>size_t</c> is 16 bits, because it can only deal with the offset into an individual segment.</para>
        /// <para>In modern times, it's generally expected to cover an entire linear address space. But be careful!</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SIZE_MAX">SDL_SIZE_MAX</seealso></SDLWiki>
        public static readonly nuint SizeMax = nuint.MaxValue;

        /// <summary>
        /// <para>Define a four character code as a <c>Uint32</c>.</para>
        /// </summary>
        /// <returns>
        /// <para>Returns the four characters converted into a <c>Uint32</c>, one character per-byte.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this macro from any thread.</threadsafety>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_FOURCC">SDL_FOURCC</seealso></SDLWiki>
        public static uint Fourcc(char a, char b, char c, char d) => ((uint)(a) | ((uint)(b) << 8) | ((uint)(c) << 16) | ((uint)(d) << 24));

        /// <summary>
        /// <para>Macro that annotates function params with input/output string buffer size.</para>
        /// </summary>
        /// <remarks>
        /// <para>If we were to annotate <c>strlcat</c>:</para>
        /// <para>``<c>c size_t strlcat(SDL_INOUT_Z_CAP(maxlen) char *dst, const char *src, size_t maxlen);</c>`<c>This notes that</c>dst<c>is a null-terminated C string, should be</c>maxlen` bytes in size, and is both read from and written to by the function. The compiler or other analysis tools can warn when this doesn't appear to be the case.</para>
        /// <para>On compilers without this annotation mechanism, this is defined to nothing.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_INOUT_Z_CAP">SDL_INOUT_Z_CAP</seealso></SDLWiki>
        // TODO: Unsupported function-like macro 'SDL_INOUT_Z_CAP'.

        /// <summary>
        /// <para>Append the 64 bit integer suffix to a signed integer literal.</para>
        /// </summary>
        /// <remarks>
        /// <para>This helps compilers that might believe a integer literal larger than 0xFFFFFFFF is overflowing a 32-bit value. Use <c>SDL_SINT64_C(0xFFFFFFFF1)</c> instead of <c>0xFFFFFFFF1</c> by itself.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SINT64_C">SDL_SINT64_C</seealso></SDLWiki>
        /// <seealso><c>SDL_UINT64_C</c></seealso>
        public static long SINT64C(long c) => (long)(c);

        /// <summary>
        /// <para>Append the 64 bit integer suffix to an unsigned integer literal.</para>
        /// </summary>
        /// <remarks>
        /// <para>This helps compilers that might believe a integer literal larger than 0xFFFFFFFF is overflowing a 32-bit value. Use <c>SDL_UINT64_C(0xFFFFFFFF1)</c> instead of <c>0xFFFFFFFF1</c> by itself.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_UINT64_C">SDL_UINT64_C</seealso></SDLWiki>
        /// <seealso><c>SDL_SINT64_C</c></seealso>
        public static ulong UINT64C(ulong c) => (ulong)(c);

        /// <summary>
        /// <para>The number of elements in a static array.</para>
        /// </summary>
        /// <remarks>
        /// <para>This will compile but return incorrect results for a pointer to an array; it has to be an array the compiler knows the size of.</para>
        /// <para>This macro looks like it double-evaluates the argument, but it does so inside of <c>sizeof</c>, so there are no side-effects here, as expressions do not actually run any code in these cases.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_arraysize">SDL_arraysize</seealso></SDLWiki>
        // TODO: Unsupported function-like macro 'SDL_arraysize'.

        /// <summary>
        /// <para>Return a value clamped to a range.</para>
        /// </summary>
        /// <remarks>
        /// <para>If <c>x</c> is outside the range a values between <c>a</c> and <c>b</c>, the returned value will be <c>a</c> or <c>b</c> as appropriate. Otherwise, <c>x</c> is returned.</para>
        /// <para>This macro will produce incorrect results if <c>b</c> is less than <c>a</c>.</para>
        /// <para>This is a helper macro that might be more clear than writing out the comparisons directly, and works with any type that can be compared with the <c>&lt;</c> and <c>&gt;</c> operators. However, it double-evaluates all its parameters, so do not use expressions with side-effects here.</para>
        /// </remarks>
        /// <returns>
        /// <para>Returns x, clamped between a and b.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this macro from any thread.</threadsafety>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_clamp">SDL_clamp</seealso></SDLWiki>
        public static uint Clamp(uint x, uint a, uint b) => (((x) < (a)) ? (a) : (((x) > (b)) ? (b) : (x)));

        /// <summary>
        /// <para>Return the greater of two values.</para>
        /// </summary>
        /// <remarks>
        /// <para>This is a helper macro that might be more clear than writing out the comparisons directly, and works with any type that can be compared with the <c>&gt;</c> operator. However, it double-evaluates both its parameters, so do not use expressions with side-effects here.</para>
        /// </remarks>
        /// <returns>
        /// <para>Returns the greater of <c>x</c> and <c>y</c>.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this macro from any thread.</threadsafety>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_max">SDL_max</seealso></SDLWiki>
        public static uint Max(uint x, uint y) => (((x) > (y)) ? (x) : (y));

        /// <summary>
        /// <para>Return the lesser of two values.</para>
        /// </summary>
        /// <remarks>
        /// <para>This is a helper macro that might be more clear than writing out the comparisons directly, and works with any type that can be compared with the <c>&lt;</c> operator. However, it double-evaluates both its parameters, so do not use expressions with side-effects here.</para>
        /// </remarks>
        /// <returns>
        /// <para>Returns the lesser of <c>x</c> and <c>y</c>.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this macro from any thread.</threadsafety>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_min">SDL_min</seealso></SDLWiki>
        public static uint Min(uint x, uint y) => (((x) < (y)) ? (x) : (y));

        /// <summary>
        /// The following macros were intentionally skipped because they are C/C++ compatibility helpers.
        /// </summary>
        // Skipped: SDL_COMPILE_TIME_ASSERT
        // Skipped: SDL_INIT_INTERFACE
        // Skipped: SDL_IN_BYTECAP
        // Skipped: SDL_OUT_BYTECAP
        // Skipped: SDL_OUT_CAP
        // Skipped: SDL_OUT_Z_BYTECAP
        // Skipped: SDL_OUT_Z_CAP
        // Skipped: SDL_PRINTF_FORMAT_STRING
        // Skipped: SDL_PRINTF_VARARG_FUNC
        // Skipped: SDL_PRINTF_VARARG_FUNCV
        // Skipped: SDL_SCANF_FORMAT_STRING
        // Skipped: SDL_SCANF_VARARG_FUNC
        // Skipped: SDL_SCANF_VARARG_FUNCV
        // Skipped: SDL_STRINGIFY_ARG
        // Skipped: SDL_WPRINTF_VARARG_FUNC
        // Skipped: SDL_WPRINTF_VARARG_FUNCV
        // Skipped: SDL_const_cast
        // Skipped: SDL_copyp
        // Skipped: SDL_iconv_utf8_locale
        // Skipped: SDL_iconv_utf8_ucs2
        // Skipped: SDL_iconv_utf8_ucs4
        // Skipped: SDL_iconv_wchar_utf8
        // Skipped: SDL_reinterpret_cast
        // Skipped: SDL_stack_alloc
        // Skipped: SDL_stack_free
        // Skipped: SDL_static_cast
        // Skipped: SDL_zero
        // Skipped: SDL_zeroa
        // Skipped: SDL_zerop

    }
}
