// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Image {
    public static partial class Macros {
        /// <summary>
        /// <para>Printable format: "%d.%d.%d", MAJOR, MINOR, MICRO</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_IMAGE_MAJOR_VERSION">SDL_IMAGE_MAJOR_VERSION</seealso></SDLWiki>
        public const uint ImageMajorVersion = 3;

        /// <summary>
        /// <para>This is the version number macro for the current SDL_image version.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_IMAGE_VERSION">SDL_IMAGE_VERSION</seealso></SDLWiki>
        // TODO: Unsupported constant macro 'SDL_IMAGE_VERSION'.

        /// <summary>
        /// <para>This macro will evaluate to true if compiled with SDL_image at least X.Y.Z.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_IMAGE_VERSION_ATLEAST">SDL_IMAGE_VERSION_ATLEAST</seealso></SDLWiki>
        // TODO: Unsupported function-like macro 'SDL_IMAGE_VERSION_ATLEAST'.

    }
}
