// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Video {
    /// <summary>
    /// <para>A set of blend modes used in drawing operations.</para>
    /// </summary>
    /// <remarks>
    /// <para>These predefined blend modes are supported everywhere.</para>
    /// <para>Additional values may be obtained from <see cref="CSDL.Video.blendmode.BlendModeExtension.ComposeCustom">ComposeCustom</see>.</para>
    /// </remarks>
    /// <since>This datatype is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_BlendMode">SDL_BlendMode</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Video.blendmode.BlendModeExtension.ComposeCustom">ComposeCustom</see></seealso>
    [System.Flags]
    public enum BlendMode : uint {
        /// <summary>
        /// <para>no blending: dstRGBA = srcRGBA</para>
        /// </summary>
        None = 0x00000000,
        /// <summary>
        /// <para>alpha blending: dstRGB = (srcRGB * srcA) + (dstRGB * (1-srcA)), dstA = srcA + (dstA * (1-srcA))</para>
        /// </summary>
        Blend = 0x00000001,
        /// <summary>
        /// <para>pre-multiplied alpha blending: dstRGBA = srcRGBA + (dstRGBA * (1-srcA))</para>
        /// </summary>
        BlendPremultiplied = 0x00000010,
        /// <summary>
        /// <para>additive blending: dstRGB = (srcRGB * srcA) + dstRGB, dstA = dstA</para>
        /// </summary>
        Add = 0x00000002,
        /// <summary>
        /// <para>pre-multiplied additive blending: dstRGB = srcRGB + dstRGB, dstA = dstA</para>
        /// </summary>
        AddPremultiplied = 0x00000020,
        /// <summary>
        /// <para>color modulate: dstRGB = srcRGB * dstRGB, dstA = dstA</para>
        /// </summary>
        Mod = 0x00000004,
        /// <summary>
        /// <para>color multiply: dstRGB = (srcRGB * dstRGB) + (dstRGB * (1-srcA)), dstA = dstA</para>
        /// </summary>
        Mul = 0x00000008,
        Invalid = 0x7FFFFFFF,
    }
}
