// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Internal.Docs {
    internal static partial class Asyncio {
        /// <summary>
        /// <para>Use this function to create a new <c>SDL_AsyncIO</c> object for reading from and/or writing to a named file.</para>
        /// </summary>
        /// <remarks>
        /// <para>The <c>mode</c> string understands the following values:</para>
        /// <list type="bullet">
        /// <item><description>"r": Open a file for reading only. It must exist.</description></item>
        /// <item><description>"w": Open a file for writing only. It will create missing files or truncate existing ones.</description></item>
        /// <item><description>"r+": Open a file for update both reading and writing. The file must exist.</description></item>
        /// <item><description>"w+": Create an empty file for both reading and writing. If a file with the same name already exists its content is erased and the file is treated as a new empty file.</description></item>
        /// </list>
        /// <para>There is no "b" mode, as there is only "binary" style I/O, and no "a" mode for appending, since you specify the position when starting a task.</para>
        /// <para>This function supports Unicode filenames, but they must be encoded in UTF-8 format, regardless of the underlying operating system.</para>
        /// <para>This call is _not_ asynchronous; it will open the file before returning, under the assumption that doing so is generally a fast operation. Future reads and writes to the opened file will be async, however.</para>
        /// </remarks>
        /// <param name="file">a UTF-8 string representing the filename to open.</param>
        /// <param name="mode">an ASCII string representing the mode to be used for opening the file.</param>
        /// <returns>
        /// <para>(<c>SDL_AsyncIO</c> *) Returns a pointer to the <c>SDL_AsyncIO</c> structure that is created or NULL on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_AsyncIOFromFile">SDL_AsyncIOFromFile</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.File.AsyncIO.Close">Close</see></seealso>
        /// <seealso><see cref="CSDL.File.AsyncIO.Read">Read</see></seealso>
        /// <seealso><see cref="CSDL.File.AsyncIO.Write">Write</see></seealso>
        public static extern void AsyncIOFromFile();

        /// <summary>
        /// <para>Close and free any allocated resources for an async I/O object.</para>
        /// </summary>
        /// <remarks>
        /// <para>Closing a file is _also_ an asynchronous task! If a write failure were to happen during the closing process, for example, the task results will report it as usual.</para>
        /// <para>Closing a file that has been written to does not guarantee the data has made it to physical media; it may remain in the operating system's file cache, for later writing to disk. This means that a successfully-closed file can be lost if the system crashes or loses power in this small window. To prevent this, call this function with the <c>flush</c> parameter set to true. This will make the operation take longer, and perhaps increase system load in general, but a successful result guarantees that the data has made it to physical storage. Don't use this for temporary files, caches, and unimportant data, and definitely use it for crucial irreplaceable files, like game saves.</para>
        /// <para>This function guarantees that the close will happen after any other pending tasks to <c>asyncio</c>, so it's safe to open a file, start several operations, close the file immediately, then check for all results later. This function will not block until the tasks have completed.</para>
        /// <para>Once this function returns true, <c>asyncio</c> is no longer valid, regardless of any future outcomes. Any completed tasks might still contain this pointer in their <see cref="CSDL.File.AsyncIOOutcome">AsyncIOOutcome</see> data, in case the app was using this value to track information, but it should not be used again.</para>
        /// <para>If this function returns false, the close wasn't started at all, and it's safe to attempt to close again later.</para>
        /// <para>An <c>SDL_AsyncIOQueue</c> must be specified. The newly-created task will be added to it when it completes its work.</para>
        /// </remarks>
        /// <param name="asyncio">a pointer to an <c>SDL_AsyncIO</c> structure to close.</param>
        /// <param name="flush">true if data should sync to disk before the task completes.</param>
        /// <param name="queue">a queue to add the new <c>SDL_AsyncIO</c> to.</param>
        /// <param name="userdata">an app-defined pointer that will be provided with the task results.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread, but two threads should not attempt to close the same object.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_CloseAsyncIO">SDL_CloseAsyncIO</seealso></SDLWiki>
        public static extern void CloseAsyncIO();

        /// <summary>
        /// <para>Create a task queue for tracking multiple I/O operations.</para>
        /// </summary>
        /// <remarks>
        /// <para>Async I/O operations are assigned to a queue when started. The queue can be checked for completed tasks thereafter.</para>
        /// </remarks>
        /// <returns>
        /// <para>(<c>SDL_AsyncIOQueue</c> *) Returns a new task queue object or NULL if there was an error; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_CreateAsyncIOQueue">SDL_CreateAsyncIOQueue</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.File.AsyncIOQueue.DisposeResource">DisposeResource</see></seealso>
        /// <seealso><see cref="CSDL.File.AsyncIOQueue.GetResult">GetResult</see></seealso>
        /// <seealso><see cref="CSDL.File.AsyncIOQueue.WaitResult">WaitResult</see></seealso>
        public static extern void CreateAsyncIOQueue();

        /// <summary>
        /// <para>Destroy a previously-created async I/O task queue.</para>
        /// </summary>
        /// <remarks>
        /// <para>If there are still tasks pending for this queue, this call will block until those tasks are finished. All those tasks will be deallocated. Their results will be lost to the app.</para>
        /// <para>Any pending reads from <see cref="CSDL.File.AsyncIOQueue.LoadFileAsync">LoadFileAsync</see> that are still in this queue will have their buffers deallocated by this function, to prevent a memory leak.</para>
        /// <para>Once this function is called, the queue is no longer valid and should not be used, including by other threads that might access it while destruction is blocking on pending tasks.</para>
        /// <para>Do not destroy a queue that still has threads waiting on it through <see cref="CSDL.File.AsyncIOQueue.WaitResult">WaitResult</see>. You can call <see cref="CSDL.File.AsyncIOQueue.Signal">Signal</see> first to unblock those threads, and take measures (such as <see cref="CSDL.Threads.Thread.Wait">Wait</see>) to make sure they have finished their wait and won't wait on the queue again.</para>
        /// </remarks>
        /// <param name="queue">the task queue to destroy.</param>
        /// <threadsafety>It is safe to call this function from any thread, so long as no other thread is waiting on the queue with <see cref="CSDL.File.AsyncIOQueue.WaitResult">WaitResult</see>.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_DestroyAsyncIOQueue">SDL_DestroyAsyncIOQueue</seealso></SDLWiki>
        public static extern void DestroyAsyncIOQueue();

        /// <summary>
        /// <para>Query an async I/O task queue for completed tasks.</para>
        /// </summary>
        /// <remarks>
        /// <para>If a task assigned to this queue has finished, this will return true and fill in <c>outcome</c> with the details of the task. If no task in the queue has finished, this function will return false. This function does not block.</para>
        /// <para>If a task has completed, this function will free its resources and the task pointer will no longer be valid. The task will be removed from the queue.</para>
        /// <para>It is safe for multiple threads to call this function on the same queue at once; a completed task will only go to one of the threads.</para>
        /// </remarks>
        /// <param name="queue">the async I/O task queue to query.</param>
        /// <param name="outcome">details of a finished task will be written here. May not be NULL.</param>
        /// <returns>
        /// <para>(bool) Returns true if a task has completed, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetAsyncIOResult">SDL_GetAsyncIOResult</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.File.AsyncIOQueue.WaitResult">WaitResult</see></seealso>
        public static extern void GetAsyncIOResult();

        /// <summary>
        /// <para>Use this function to get the size of the data stream in an <c>SDL_AsyncIO</c>.</para>
        /// </summary>
        /// <remarks>
        /// <para>This call is _not_ asynchronous; it assumes that obtaining this info is a non-blocking operation in most reasonable cases.</para>
        /// </remarks>
        /// <param name="asyncio">the <c>SDL_AsyncIO</c> to get the size of the data stream from.</param>
        /// <returns>
        /// <para>(<c>Sint64</c>) Returns the size of the data stream in the <see cref="CSDL.File.IOStream">IOStream</see> on success or a negative error code on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetAsyncIOSize">SDL_GetAsyncIOSize</seealso></SDLWiki>
        public static extern void GetAsyncIOSize();

        /// <summary>
        /// <para>Load all the data from a file path, asynchronously.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function returns as quickly as possible; it does not wait for the read to complete. On a successful return, this work will continue in the background. If the work begins, even failure is asynchronous: a failing return value from this function only means the work couldn't start at all.</para>
        /// <para>The data is allocated with a zero byte at the end (null terminated) for convenience. This extra byte is not included in <see cref="CSDL.File.AsyncIOOutcome">AsyncIOOutcome</see>'s bytes_transferred value.</para>
        /// <para>This function will allocate the buffer to contain the file. It must be deallocated by calling <see cref="CSDL.Memory.Free">Free</see> on <see cref="CSDL.File.AsyncIOOutcome">AsyncIOOutcome</see>'s buffer field after completion.</para>
        /// <para>An <c>SDL_AsyncIOQueue</c> must be specified. The newly-created task will be added to it when it completes its work.</para>
        /// </remarks>
        /// <param name="file">the path to read all available data from.</param>
        /// <param name="queue">a queue to add the new <c>SDL_AsyncIO</c> to.</param>
        /// <param name="userdata">an app-defined pointer that will be provided with the task results.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_LoadFileAsync">SDL_LoadFileAsync</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.File.IOStream.Load">Load</see></seealso>
        public static extern void LoadFileAsync();

        /// <summary>
        /// <para>Start an async read.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function reads up to <c>size</c> bytes from <c>offset</c> position in the data source to the area pointed at by <c>ptr</c>. This function may read less bytes than requested.</para>
        /// <para>This function returns as quickly as possible; it does not wait for the read to complete. On a successful return, this work will continue in the background. If the work begins, even failure is asynchronous: a failing return value from this function only means the work couldn't start at all.</para>
        /// <para><c>ptr</c> must remain available until the work is done, and may be accessed by the system at any time until then. Do not allocate it on the stack, as this might take longer than the life of the calling function to complete!</para>
        /// <para>An <c>SDL_AsyncIOQueue</c> must be specified. The newly-created task will be added to it when it completes its work.</para>
        /// </remarks>
        /// <param name="asyncio">a pointer to an <c>SDL_AsyncIO</c> structure.</param>
        /// <param name="ptr">a pointer to a buffer to read data into.</param>
        /// <param name="offset">the position to start reading in the data source.</param>
        /// <param name="size">the number of bytes to read from the data source.</param>
        /// <param name="queue">a queue to add the new <c>SDL_AsyncIO</c> to.</param>
        /// <param name="userdata">an app-defined pointer that will be provided with the task results.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_ReadAsyncIO">SDL_ReadAsyncIO</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.File.AsyncIO.Write">Write</see></seealso>
        /// <seealso><see cref="CSDL.File.AsyncIOQueue()">AsyncIOQueue()</see></seealso>
        public static extern void ReadAsyncIO();

        /// <summary>
        /// <para>Wake up any threads that are blocking in <see cref="CSDL.File.AsyncIOQueue.WaitResult">WaitResult</see>.</para>
        /// </summary>
        /// <remarks>
        /// <para>This will unblock any threads that are sleeping in a call to <see cref="CSDL.File.AsyncIOQueue.WaitResult">WaitResult</see> for the specified queue, and cause them to return from that function.</para>
        /// <para>This can be useful when destroying a queue to make sure nothing is touching it indefinitely. In this case, once this call completes, the caller should take measures to make sure any previously-blocked threads have returned from their wait and will not touch the queue again (perhaps by setting a flag to tell the threads to terminate and then using <see cref="CSDL.Threads.Thread.Wait">Wait</see> to make sure they've done so).</para>
        /// </remarks>
        /// <param name="queue">the async I/O task queue to signal.</param>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SignalAsyncIOQueue">SDL_SignalAsyncIOQueue</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.File.AsyncIOQueue.WaitResult">WaitResult</see></seealso>
        public static extern void SignalAsyncIOQueue();

        /// <summary>
        /// <para>Block until an async I/O task queue has a completed task.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function puts the calling thread to sleep until there a task assigned to the queue that has finished.</para>
        /// <para>If a task assigned to the queue has finished, this will return true and fill in <c>outcome</c> with the details of the task. If no task in the queue has finished, this function will return false.</para>
        /// <para>If a task has completed, this function will free its resources and the task pointer will no longer be valid. The task will be removed from the queue.</para>
        /// <para>It is safe for multiple threads to call this function on the same queue at once; a completed task will only go to one of the threads.</para>
        /// <para>Note that by the nature of various platforms, more than one waiting thread may wake to handle a single task, but only one will obtain it, so <c>timeoutMS</c> is a _maximum_ wait time, and this function may return false sooner.</para>
        /// <para>This function may return false if there was a system error, the OS inadvertently awoke multiple threads, or if <see cref="CSDL.File.AsyncIOQueue.Signal">Signal</see> was called to wake up all waiting threads without a finished task.</para>
        /// <para>A timeout can be used to specify a maximum wait time, but rather than polling, it is possible to have a timeout of -1 to wait forever, and use <see cref="CSDL.File.AsyncIOQueue.Signal">Signal</see> to wake up the waiting threads later.</para>
        /// </remarks>
        /// <param name="queue">the async I/O task queue to wait on.</param>
        /// <param name="outcome">details of a finished task will be written here. May not be NULL.</param>
        /// <param name="timeoutMS">the maximum time to wait, in milliseconds, or -1 to wait indefinitely.</param>
        /// <returns>
        /// <para>(bool) Returns true if task has completed, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_WaitAsyncIOResult">SDL_WaitAsyncIOResult</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.File.AsyncIOQueue.Signal">Signal</see></seealso>
        public static extern void WaitAsyncIOResult();

        /// <summary>
        /// <para>Start an async write.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function writes <c>size</c> bytes from <c>offset</c> position in the data source to the area pointed at by <c>ptr</c>.</para>
        /// <para>This function returns as quickly as possible; it does not wait for the write to complete. On a successful return, this work will continue in the background. If the work begins, even failure is asynchronous: a failing return value from this function only means the work couldn't start at all.</para>
        /// <para><c>ptr</c> must remain available until the work is done, and may be accessed by the system at any time until then. Do not allocate it on the stack, as this might take longer than the life of the calling function to complete!</para>
        /// <para>An <c>SDL_AsyncIOQueue</c> must be specified. The newly-created task will be added to it when it completes its work.</para>
        /// </remarks>
        /// <param name="asyncio">a pointer to an <c>SDL_AsyncIO</c> structure.</param>
        /// <param name="ptr">a pointer to a buffer to write data from.</param>
        /// <param name="offset">the position to start writing to the data source.</param>
        /// <param name="size">the number of bytes to write to the data source.</param>
        /// <param name="queue">a queue to add the new <c>SDL_AsyncIO</c> to.</param>
        /// <param name="userdata">an app-defined pointer that will be provided with the task results.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_WriteAsyncIO">SDL_WriteAsyncIO</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.File.AsyncIO.Read">Read</see></seealso>
        /// <seealso><see cref="CSDL.File.AsyncIOQueue()">AsyncIOQueue()</see></seealso>
        public static extern void WriteAsyncIO();
    }
}
