// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.File {
    /// <summary>
    /// <para>Possible outcomes of an asynchronous I/O task.</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_AsyncIOResult">SDL_AsyncIOResult</seealso></SDLWiki>
    public enum AsyncIOResult {
        /// <summary>
        /// <para>request was completed without error</para>
        /// </summary>
        Complete,
        /// <summary>
        /// <para>request failed for some reason; check SDL_GetError()!</para>
        /// </summary>
        Failure,
        /// <summary>
        /// <para>request was canceled before completing.</para>
        /// </summary>
        Canceled,
    }
}
