// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL.File {
    internal static partial class SDL {
        [LibraryImport(SDLLibrary, EntryPoint = "SDL_AsyncIOFromFile"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlAsyncIO> AsyncIOFromFile([MarshalAs(UnmanagedType.LPUTF8Str)] string? file, [MarshalAs(UnmanagedType.LPUTF8Str)] string? mode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_AsyncIOFromFile"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlAsyncIO> AsyncIOFromFile(NativePtr<byte> file, NativePtr<byte> mode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CloseAsyncIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool CloseAsyncIO(NativePtr<CSDL.Opaque.SdlAsyncIO> asyncio, CBool flush, NativePtr<CSDL.Opaque.SdlAsyncIOQueue> queue, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateAsyncIOQueue"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlAsyncIOQueue> CreateAsyncIOQueue();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_DestroyAsyncIOQueue"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void DestroyAsyncIOQueue(NativePtr<CSDL.Opaque.SdlAsyncIOQueue> queue);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetAsyncIOResult"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetAsyncIOResult(NativePtr<CSDL.Opaque.SdlAsyncIOQueue> queue, ref CSDL.File.AsyncIOOutcome outcome);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetAsyncIOSize"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial long GetAsyncIOSize(NativePtr<CSDL.Opaque.SdlAsyncIO> asyncio);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LoadFileAsync"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool LoadFileAsync([MarshalAs(UnmanagedType.LPUTF8Str)] string? file, NativePtr<CSDL.Opaque.SdlAsyncIOQueue> queue, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LoadFileAsync"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool LoadFileAsync(NativePtr<byte> file, NativePtr<CSDL.Opaque.SdlAsyncIOQueue> queue, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadAsyncIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadAsyncIO(NativePtr<CSDL.Opaque.SdlAsyncIO> asyncio, IntPtr ptr, ulong offset, ulong size, NativePtr<CSDL.Opaque.SdlAsyncIOQueue> queue, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SignalAsyncIOQueue"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void SignalAsyncIOQueue(NativePtr<CSDL.Opaque.SdlAsyncIOQueue> queue);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WaitAsyncIOResult"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WaitAsyncIOResult(NativePtr<CSDL.Opaque.SdlAsyncIOQueue> queue, ref CSDL.File.AsyncIOOutcome outcome, int timeoutMs);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteAsyncIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteAsyncIO(NativePtr<CSDL.Opaque.SdlAsyncIO> asyncio, IntPtr ptr, ulong offset, ulong size, NativePtr<CSDL.Opaque.SdlAsyncIOQueue> queue, IntPtr userData);

    }
}
