// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Threads {
    /// <summary>
    /// <para>The SDL thread priority.</para>
    /// </summary>
    /// <remarks>
    /// <para>SDL will make system changes as necessary in order to apply the thread priority. Code which attempts to control thread state related to priority should be aware that calling <see cref="CSDL.Threads.Thread.SetCurrentThreadPriority">SetCurrentThreadPriority</see> may alter such state. <see cref="CSDL.Hints.ThreadPriorityPolicy">ThreadPriorityPolicy</see> can be used to control aspects of this behavior.</para>
    /// </remarks>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_ThreadPriority">SDL_ThreadPriority</seealso></SDLWiki>
    public enum ThreadPriority {
        Low,
        Normal,
        High,
        TimeCritical,
    }
}
