// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Threads {
    /// <summary>
    /// <para>Thread local storage ID.</para>
    /// </summary>
    /// <remarks>
    /// <para>0 is the invalid ID. An app can create these and then set data for these IDs that is unique to each thread.</para>
    /// </remarks>
    /// <since>This datatype is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_TLSID">SDL_TLSID</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Threads.TLSIDExtension.Get">Get</see></seealso>
    /// <seealso><see cref="CSDL.Threads.TLSIDExtension.Set">Set</see></seealso>
    public readonly record struct TLSID(AtomicInt Value) {
        public static implicit operator AtomicInt(TLSID id) => id.Value;
        public static implicit operator TLSID(AtomicInt value) => new(value);
        public override string ToString() => Value.ToString();
    }
}
