// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL.File {
    internal static partial class SDL {
        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CloseIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool CloseIO(NativePtr<CSDL.Opaque.SdlIOStream> context);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_FlushIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool FlushIO(NativePtr<CSDL.Opaque.SdlIOStream> context);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetIOProperties"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.PropertiesID GetIOProperties(NativePtr<CSDL.Opaque.SdlIOStream> context);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetIOSize"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial long GetIOSize(NativePtr<CSDL.Opaque.SdlIOStream> context);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetIOStatus"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.File.IOStatus GetIOStatus(NativePtr<CSDL.Opaque.SdlIOStream> context);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_IOFromConstMem"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlIOStream> IOFromConstMem(IntPtr mem, nuint size);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_IOFromDynamicMem"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlIOStream> IOFromDynamicMem();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_IOFromFile"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlIOStream> IOFromFile([MarshalAs(UnmanagedType.LPUTF8Str)] string? file, [MarshalAs(UnmanagedType.LPUTF8Str)] string? mode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_IOFromFile"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlIOStream> IOFromFile(NativePtr<byte> file, NativePtr<byte> mode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_IOFromMem"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlIOStream> IOFromMem(IntPtr mem, nuint size);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_IOprintf"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial nuint IOprintf(NativePtr<CSDL.Opaque.SdlIOStream> context, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_IOprintf"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial nuint IOprintf(NativePtr<CSDL.Opaque.SdlIOStream> context, NativePtr<byte> fmt);


        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LoadFile"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial IntPtr LoadFile([MarshalAs(UnmanagedType.LPUTF8Str)] string? file, out nuint datasize);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LoadFile"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial IntPtr LoadFile(NativePtr<byte> file, out nuint datasize);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LoadFile_IO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial IntPtr LoadFile_IO(NativePtr<CSDL.Opaque.SdlIOStream> src, out nuint datasize, CBool closeio);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_OpenIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlIOStream> OpenIO(in CSDL.File.IOStreamInterface iface, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial nuint ReadIO(NativePtr<CSDL.Opaque.SdlIOStream> context, IntPtr ptr, nuint size);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadS16BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadS16BE(NativePtr<CSDL.Opaque.SdlIOStream> src, out short value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadS16LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadS16LE(NativePtr<CSDL.Opaque.SdlIOStream> src, out short value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadS32BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadS32BE(NativePtr<CSDL.Opaque.SdlIOStream> src, out int value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadS32LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadS32LE(NativePtr<CSDL.Opaque.SdlIOStream> src, out int value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadS64BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadS64BE(NativePtr<CSDL.Opaque.SdlIOStream> src, out long value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadS64LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadS64LE(NativePtr<CSDL.Opaque.SdlIOStream> src, out long value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadS8"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadS8(NativePtr<CSDL.Opaque.SdlIOStream> src, out sbyte value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadU16BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadU16BE(NativePtr<CSDL.Opaque.SdlIOStream> src, out ushort value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadU16LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadU16LE(NativePtr<CSDL.Opaque.SdlIOStream> src, out ushort value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadU32BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadU32BE(NativePtr<CSDL.Opaque.SdlIOStream> src, out uint value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadU32LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadU32LE(NativePtr<CSDL.Opaque.SdlIOStream> src, out uint value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadU64BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadU64BE(NativePtr<CSDL.Opaque.SdlIOStream> src, out ulong value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadU64LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadU64LE(NativePtr<CSDL.Opaque.SdlIOStream> src, out ulong value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReadU8"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ReadU8(NativePtr<CSDL.Opaque.SdlIOStream> src, out byte value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SaveFile"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SaveFile([MarshalAs(UnmanagedType.LPUTF8Str)] string? file, IntPtr data, nuint datasize);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SaveFile"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SaveFile(NativePtr<byte> file, IntPtr data, nuint datasize);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SaveFile_IO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SaveFile_IO(NativePtr<CSDL.Opaque.SdlIOStream> src, IntPtr data, nuint datasize, CBool closeio);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SeekIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial long SeekIO(NativePtr<CSDL.Opaque.SdlIOStream> context, long offset, CSDL.File.IOWhence whence);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_TellIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial long TellIO(NativePtr<CSDL.Opaque.SdlIOStream> context);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteIO"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial nuint WriteIO(NativePtr<CSDL.Opaque.SdlIOStream> context, IntPtr ptr, nuint size);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteS16BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteS16BE(NativePtr<CSDL.Opaque.SdlIOStream> dst, short value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteS16LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteS16LE(NativePtr<CSDL.Opaque.SdlIOStream> dst, short value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteS32BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteS32BE(NativePtr<CSDL.Opaque.SdlIOStream> dst, int value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteS32LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteS32LE(NativePtr<CSDL.Opaque.SdlIOStream> dst, int value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteS64BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteS64BE(NativePtr<CSDL.Opaque.SdlIOStream> dst, long value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteS64LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteS64LE(NativePtr<CSDL.Opaque.SdlIOStream> dst, long value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteS8"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteS8(NativePtr<CSDL.Opaque.SdlIOStream> dst, sbyte value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteU16BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteU16BE(NativePtr<CSDL.Opaque.SdlIOStream> dst, ushort value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteU16LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteU16LE(NativePtr<CSDL.Opaque.SdlIOStream> dst, ushort value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteU32BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteU32BE(NativePtr<CSDL.Opaque.SdlIOStream> dst, uint value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteU32LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteU32LE(NativePtr<CSDL.Opaque.SdlIOStream> dst, uint value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteU64BE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteU64BE(NativePtr<CSDL.Opaque.SdlIOStream> dst, ulong value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteU64LE"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteU64LE(NativePtr<CSDL.Opaque.SdlIOStream> dst, ulong value);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WriteU8"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WriteU8(NativePtr<CSDL.Opaque.SdlIOStream> dst, byte value);

    }
}
