// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Input {
    /// <summary>
    /// <para>Auto capitalization type.</para>
    /// </summary>
    /// <remarks>
    /// <para>These are the valid values for <see cref="CSDL.Props.TextinputCapitalizationNumber">TextinputCapitalizationNumber</see>. Not every value is valid on every platform, but where a value isn't supported, a reasonable fallback will be used.</para>
    /// </remarks>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_Capitalization">SDL_Capitalization</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Input.Keyboards.StartTextInput">StartTextInput</see></seealso>
    public enum Capitalization {
        /// <summary>
        /// <para>No auto-capitalization will be done</para>
        /// </summary>
        None,
        /// <summary>
        /// <para>The first letter of sentences will be capitalized</para>
        /// </summary>
        Sentences,
        /// <summary>
        /// <para>The first letter of words will be capitalized</para>
        /// </summary>
        Words,
        /// <summary>
        /// <para>All letters will be capitalized</para>
        /// </summary>
        Letters,
    }
}
