// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL.Input {
    internal static partial class SDL {
        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ClearComposition"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ClearComposition(NativePtr<CSDL.Opaque.SdlWindow> window);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetKeyboardFocus"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlWindow> GetKeyboardFocus();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetKeyboardNameForID"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<byte> GetKeyboardNameForID(CSDL.Input.KeyboardID instanceID);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetKeyboards"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Input.KeyboardID> GetKeyboards(out int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetKeyboardState"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<bool> GetKeyboardState(NativePtr<int> numkeys);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetKeyFromName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Input.Keycode GetKeyFromName([MarshalAs(UnmanagedType.LPUTF8Str)] string? name);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetKeyFromName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Input.Keycode GetKeyFromName(NativePtr<byte> name);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetKeyFromScancode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Input.Keycode GetKeyFromScancode(CSDL.Input.Scancode scancode, CSDL.Input.Keymod modstate, CBool keyEvent);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetKeyName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<byte> GetKeyName(CSDL.Input.Keycode key);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetModState"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Input.Keymod GetModState();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetScancodeFromKey"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Input.Scancode GetScancodeFromKey(CSDL.Input.Keycode key, ref CSDL.Input.Keymod modstate);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetScancodeFromKey"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Input.Scancode GetScancodeFromKeyNullable(CSDL.Input.Keycode key, NativePtr<CSDL.Input.Keymod> modstate);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetScancodeFromName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Input.Scancode GetScancodeFromName([MarshalAs(UnmanagedType.LPUTF8Str)] string? name);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetScancodeFromName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Input.Scancode GetScancodeFromName(NativePtr<byte> name);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetScancodeName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<byte> GetScancodeName(CSDL.Input.Scancode scancode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTextInputArea"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetTextInputArea(NativePtr<CSDL.Opaque.SdlWindow> window, out CSDL.Video.Rect rect, NativePtr<int> cursor);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_HasKeyboard"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool HasKeyboard();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_HasScreenKeyboardSupport"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool HasScreenKeyboardSupport();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ResetKeyboard"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void ResetKeyboard();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ScreenKeyboardShown"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ScreenKeyboardShown(NativePtr<CSDL.Opaque.SdlWindow> window);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetModState"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void SetModState(CSDL.Input.Keymod modstate);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetScancodeName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetScancodeName(CSDL.Input.Scancode scancode, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetScancodeName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetScancodeName(CSDL.Input.Scancode scancode, NativePtr<byte> name);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetTextInputArea"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetTextInputArea(NativePtr<CSDL.Opaque.SdlWindow> window, in CSDL.Video.Rect rect, int cursor);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_StartTextInput"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool StartTextInput(NativePtr<CSDL.Opaque.SdlWindow> window);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_StartTextInputWithProperties"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool StartTextInputWithProperties(NativePtr<CSDL.Opaque.SdlWindow> window, CSDL.PropertiesID props);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_StopTextInput"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool StopTextInput(NativePtr<CSDL.Opaque.SdlWindow> window);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_TextInputActive"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool TextInputActive(NativePtr<CSDL.Opaque.SdlWindow> window);

    }
}
