// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Video {
    /// <summary>
    /// <para>A collection of pixels used in software blitting.</para>
    /// </summary>
    /// <remarks>
    /// <para>Pixels are arranged in memory in rows, with the top row first. Each row occupies an amount of memory given by the pitch (sometimes known as the row stride in non-SDL APIs).</para>
    /// <para>Within each row, pixels are arranged from left to right until the width is reached. Each pixel occupies a number of bits appropriate for its format, with most formats representing each pixel as one or more whole bytes (in some indexed formats, instead multiple pixels are packed into each byte), and a byte order given by the format. After encoding all pixels, any remaining bytes to reach the pitch are used as padding to reach a desired alignment, and have undefined contents.</para>
    /// <para>When a surface holds YUV format data, the planes are assumed to be contiguous without padding between them, e.g. a 32x32 surface in NV12 format with a pitch of 32 would consist of 32x32 bytes of Y plane followed by 32x16 bytes of UV plane.</para>
    /// <para>When a surface holds MJPG format data, pixels points at the compressed JPEG image and pitch is the length of that data.</para>
    /// </remarks>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_Surface">SDL_Surface</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Video.Surface.CreateSurface">CreateSurface</see></seealso>
    /// <seealso><see cref="CSDL.Video.Surface.DisposeResource">DisposeResource</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct SurfaceData {
        /// <summary>
        /// <para>The flags of the surface, read-only</para>
        /// </summary>
        public CSDL.Video.SurfaceFlags Flags;

        /// <summary>
        /// <para>The format of the surface, read-only</para>
        /// </summary>
        public CSDL.Video.PixelFormat Format;

        /// <summary>
        /// <para>The width of the surface, read-only.</para>
        /// </summary>
        public int W;

        /// <summary>
        /// <para>The height of the surface, read-only.</para>
        /// </summary>
        public int H;

        /// <summary>
        /// <para>The distance in bytes between rows of pixels, read-only</para>
        /// </summary>
        public int Pitch;

        /// <summary>
        /// <para>A pointer to the pixels of the surface, the pixels are writeable if non-NULL</para>
        /// </summary>
        public nint Pixels;

        /// <summary>
        /// <para>Application reference count, used when freeing surface</para>
        /// </summary>
        public int Refcount;

        /// <summary>
        /// <para>Reserved for internal use</para>
        /// </summary>
        private nint _reserved;
    }
}
