// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>A callback used to free resources when a property is deleted.</para>
    /// </summary>
    /// <param name="userData">an app-defined pointer passed to the callback.</param>
    /// <param name="value">the pointer assigned to the property to clean up.</param>
    /// <remarks>
    /// <para>This should release any resources associated with <c>value</c> that are no longer needed.</para>
    /// <para>This callback is set per-property. Different properties in the same group can have different cleanup callbacks.</para>
    /// <para>This callback will be called _during_ <see cref="CSDL.Properties.PointerProperty.SetWithCleanup">SetWithCleanup</see> if the function fails for any reason.</para>
    /// </remarks>
    /// <threadSafety>
    /// <para>This callback may fire without any locks held; if this is a concern, the app should provide its own locking.</para>
    /// </threadSafety>
    /// <version>
    /// <para>This datatype is available since SDL 3.2.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_CleanupPropertyCallback">SDL_CleanupPropertyCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Properties.PointerProperty.SetWithCleanup">SetWithCleanup</see></seealso>
    public delegate void CleanupPropertyCallback(object? userData, nint value);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void SDL_CleanupPropertyCallbackNative(nint userData, nint value);

    internal static class CleanupPropertyCallbackWrapper {
        public static SDL_CleanupPropertyCallbackNative Create(CleanupPropertyCallback fn) {
            return (userDataPtr, valuePtr) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    nint value = valuePtr;
                    fn(userData, value);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return;
                }
            };
        }
    }

    /// <summary>
    /// <para>A callback used to enumerate all the properties in a group of properties.</para>
    /// </summary>
    /// <param name="userData">an app-defined pointer passed to the callback.</param>
    /// <param name="props">the <see cref="CSDL.PropertiesID">PropertiesID</see> that is being enumerated.</param>
    /// <param name="name">the next property name in the enumeration.</param>
    /// <remarks>
    /// <para>This callback is called from <see cref="CSDL.Properties.PropertyGroup.EnumerateProperties">EnumerateProperties</see>, and is called once per property in the set.</para>
    /// </remarks>
    /// <threadSafety>
    /// <para><see cref="CSDL.Properties.PropertyGroup.EnumerateProperties">EnumerateProperties</see> holds a lock on <c>props</c> during this callback.</para>
    /// </threadSafety>
    /// <version>
    /// <para>This datatype is available since SDL 3.2.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_EnumeratePropertiesCallback">SDL_EnumeratePropertiesCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Properties.PropertyGroup.EnumerateProperties">EnumerateProperties</see></seealso>
    public delegate void EnumeratePropertiesCallback(object? userData, CSDL.PropertiesID props, string name);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void SDL_EnumeratePropertiesCallbackNative(nint userData, CSDL.PropertiesID props, nint name);

    internal static class EnumeratePropertiesCallbackWrapper {
        public static SDL_EnumeratePropertiesCallbackNative Create(EnumeratePropertiesCallback fn) {
            return (userDataPtr, propsRaw, namePtr) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    CSDL.PropertiesID props = propsRaw;
                    string name = Marshal.PtrToStringUTF8(namePtr);
                    fn(userData, props, name);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return;
                }
            };
        }
    }

}
