// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>Definition of the timer ID type.</para>
    /// </summary>
    /// <since>This datatype is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_TimerID">SDL_TimerID</seealso></SDLWiki>
    public readonly record struct TimerID(uint Value) {
        public static implicit operator uint(TimerID id) => id.Value;
        public static implicit operator TimerID(uint value) => new(value);
        public override string ToString() => Value.ToString();
    }
}
