// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL {
    internal static partial class SDL {
        [LibraryImport(SDLLibrary, EntryPoint = "SDL_AddTimer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.TimerID AddTimer(uint interval, SDL_TimerCallbackNative callback, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_AddTimerNS"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.TimerID AddTimerNS(ulong interval, SDL_NSTimerCallbackNative callback, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_Delay"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void Delay(uint ms);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_DelayNS"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void DelayNS(ulong ns);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_DelayPrecise"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void DelayPrecise(ulong ns);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetPerformanceCounter"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial ulong GetPerformanceCounter();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetPerformanceFrequency"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial ulong GetPerformanceFrequency();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTicks"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial ulong GetTicks();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTicksNS"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial ulong GetTicksNS();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RemoveTimer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RemoveTimer(CSDL.TimerID id);

    }
}
