// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL.Video {
    internal static partial class SDL {
        [LibraryImport(SDLLibrary, EntryPoint = "SDL_AddVulkanRenderSemaphores"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool AddVulkanRenderSemaphores(NativePtr<CSDL.Opaque.SdlRenderer> renderer, uint waitStageMask, long waitSemaphore, long signalSemaphore);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ConvertEventToRenderCoordinates"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool ConvertEventToRenderCoordinates(NativePtr<CSDL.Opaque.SdlRenderer> renderer, ref CSDL.Event @event);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateGPURenderer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlRenderer> CreateGPURenderer(NativePtr<CSDL.Opaque.SdlGPUDevice> device, NativePtr<CSDL.Opaque.SdlWindow> window);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateGPURenderState"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlGPURenderState> CreateGPURenderState(NativePtr<CSDL.Opaque.SdlRenderer> renderer, in CSDL.Video.GPURenderStateCreateInfo createinfo);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateRenderer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlRenderer> CreateRenderer(NativePtr<CSDL.Opaque.SdlWindow> window, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateRenderer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlRenderer> CreateRenderer(NativePtr<CSDL.Opaque.SdlWindow> window, NativePtr<byte> name);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateRendererWithProperties"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlRenderer> CreateRendererWithProperties(CSDL.PropertiesID props);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateSoftwareRenderer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlRenderer> CreateSoftwareRenderer(NativePtr<CSDL.Video.SurfaceData> surface);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Video.TextureData> CreateTexture(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.Video.PixelFormat format, CSDL.Video.TextureAccess access, int w, int h);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateTextureFromSurface"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Video.TextureData> CreateTextureFromSurface(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.SurfaceData> surface);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CreateTextureWithProperties"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Video.TextureData> CreateTextureWithProperties(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.PropertiesID props);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_DestroyGPURenderState"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void DestroyGPURenderState(NativePtr<CSDL.Opaque.SdlGPURenderState> state);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_DestroyRenderer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void DestroyRenderer(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_DestroyTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void DestroyTexture(NativePtr<CSDL.Video.TextureData> texture);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_FlushRenderer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool FlushRenderer(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GDKResumeRenderer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void GDKResumeRenderer(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GDKSuspendRenderer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void GDKSuspendRenderer(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCurrentRenderOutputSize"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetCurrentRenderOutputSize(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out int w, out int h);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetDefaultTextureScaleMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetDefaultTextureScaleMode(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out CSDL.Video.ScaleMode scaleMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetGPURendererDevice"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlGPUDevice> GetGPURendererDevice(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetNumRenderDrivers"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial int GetNumRenderDrivers();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderClipRect"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderClipRect(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out CSDL.Video.Rect rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderColorScale"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderColorScale(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out float scale);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderDrawBlendMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderDrawBlendMode(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out CSDL.Video.BlendMode blendMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderDrawColor"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderDrawColor(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out byte r, out byte g, out byte b, out byte a);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderDrawColorFloat"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderDrawColorFloat(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out float r, out float g, out float b, out float a);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderDriver"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<byte> GetRenderDriver(int index);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlRenderer> GetRenderer(NativePtr<CSDL.Opaque.SdlWindow> window);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRendererFromTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlRenderer> GetRendererFromTexture(NativePtr<CSDL.Video.TextureData> texture);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRendererName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<byte> GetRendererName(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRendererProperties"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.PropertiesID GetRendererProperties(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderLogicalPresentation"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderLogicalPresentation(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out int w, out int h, out CSDL.Video.RendererLogicalPresentation mode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderLogicalPresentationRect"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderLogicalPresentationRect(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out CSDL.Video.FRect rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderMetalCommandEncoder"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial IntPtr GetRenderMetalCommandEncoder(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderMetalLayer"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial IntPtr GetRenderMetalLayer(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderOutputSize"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderOutputSize(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out int w, out int h);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderSafeArea"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderSafeArea(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out CSDL.Video.Rect rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderScale"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderScale(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out float scaleX, out float scaleY);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderTarget"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Video.TextureData> GetRenderTarget(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderTextureAddressMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderTextureAddressMode(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out CSDL.Video.TextureAddressMode uMode, out CSDL.Video.TextureAddressMode vMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderViewport"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderViewport(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out CSDL.Video.Rect rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderVSync"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetRenderVSync(NativePtr<CSDL.Opaque.SdlRenderer> renderer, out int vsync);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetRenderWindow"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlWindow> GetRenderWindow(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTextureAlphaMod"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetTextureAlphaMod(NativePtr<CSDL.Video.TextureData> texture, out byte alpha);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTextureAlphaModFloat"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetTextureAlphaModFloat(NativePtr<CSDL.Video.TextureData> texture, out float alpha);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTextureBlendMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetTextureBlendMode(NativePtr<CSDL.Video.TextureData> texture, out CSDL.Video.BlendMode blendMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTextureColorMod"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetTextureColorMod(NativePtr<CSDL.Video.TextureData> texture, out byte r, out byte g, out byte b);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTextureColorModFloat"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetTextureColorModFloat(NativePtr<CSDL.Video.TextureData> texture, out float r, out float g, out float b);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTexturePalette"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Video.PaletteData> GetTexturePalette(NativePtr<CSDL.Video.TextureData> texture);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTextureProperties"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.PropertiesID GetTextureProperties(NativePtr<CSDL.Video.TextureData> texture);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTextureScaleMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetTextureScaleMode(NativePtr<CSDL.Video.TextureData> texture, out CSDL.Video.ScaleMode scaleMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetTextureSize"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetTextureSize(NativePtr<CSDL.Video.TextureData> texture, out float w, out float h);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LockTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool LockTexture(NativePtr<CSDL.Video.TextureData> texture, in CSDL.Video.Rect rect, out IntPtr pixels, out int pitch);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LockTextureToSurface"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool LockTextureToSurface(NativePtr<CSDL.Video.TextureData> texture, in CSDL.Video.Rect rect, NativePtr<nint> surface);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderClear"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderClear(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderClipEnabled"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderClipEnabled(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderCoordinatesFromWindow"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderCoordinatesFromWindow(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float windowX, float windowY, out float x, out float y);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderCoordinatesToWindow"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderCoordinatesToWindow(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float x, float y, out float windowX, out float windowY);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderDebugText"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderDebugText(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float x, float y, [MarshalAs(UnmanagedType.LPUTF8Str)] string? str);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderDebugText"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderDebugText(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float x, float y, NativePtr<byte> str);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderDebugTextFormat"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderDebugTextFormat(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float x, float y, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderDebugTextFormat"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderDebugTextFormat(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float x, float y, NativePtr<byte> fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderFillRect"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderFillRect(NativePtr<CSDL.Opaque.SdlRenderer> renderer, in CSDL.Video.FRect rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderFillRect"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool RenderFillRectNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.Video.FRect* rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderFillRects"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderFillRects(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.FRect> rects, int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderFillRects"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderFillRects(NativePtr<CSDL.Opaque.SdlRenderer> renderer, ReadOnlySpan<CSDL.Video.FRect> rects, int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderGeometry"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderGeometry(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, NativePtr<CSDL.Video.Vertex> vertices, int numVertices, NativePtr<int> indices, int numIndices);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderGeometry"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderGeometry(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, ReadOnlySpan<CSDL.Video.Vertex> vertices, int numVertices, ReadOnlySpan<int> indices, int numIndices);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderGeometryRaw"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderGeometryRaw(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, NativePtr<float> xy, int xyStride, NativePtr<CSDL.Video.FColor> color, int colorStride, NativePtr<float> uv, int uvStride, int numVertices, IntPtr indices, int numIndices, int sizeIndices);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderGeometryRaw"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderGeometryRaw(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, ReadOnlySpan<float> xy, int xyStride, ReadOnlySpan<CSDL.Video.FColor> color, int colorStride, NativePtr<float> uv, int uvStride, int numVertices, IntPtr indices, int numIndices, int sizeIndices);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderLine"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderLine(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float x1, float y1, float x2, float y2);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderLines"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderLines(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.FPoint> points, int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderLines"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderLines(NativePtr<CSDL.Opaque.SdlRenderer> renderer, ReadOnlySpan<CSDL.Video.FPoint> points, int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderPoint"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderPoint(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float x, float y);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderPoints"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderPoints(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.FPoint> points, int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderPoints"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderPoints(NativePtr<CSDL.Opaque.SdlRenderer> renderer, ReadOnlySpan<CSDL.Video.FPoint> points, int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderPresent"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderPresent(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderReadPixels"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Video.SurfaceData> RenderReadPixels(NativePtr<CSDL.Opaque.SdlRenderer> renderer, in CSDL.Video.Rect rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderReadPixels"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial NativePtr<CSDL.Video.SurfaceData> RenderReadPixelsNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.Video.Rect* rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderRect"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderRect(NativePtr<CSDL.Opaque.SdlRenderer> renderer, in CSDL.Video.FRect rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderRect"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool RenderRectNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.Video.FRect* rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderRects"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderRects(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.FRect> rects, int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderRects"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderRects(NativePtr<CSDL.Opaque.SdlRenderer> renderer, ReadOnlySpan<CSDL.Video.FRect> rects, int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderTexture(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, in CSDL.Video.FRect srcrect, in CSDL.Video.FRect dstrect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool RenderTextureNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, CSDL.Video.FRect* srcrect, CSDL.Video.FRect* dstrect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTexture9Grid"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderTexture9Grid(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, in CSDL.Video.FRect srcrect, float leftWidth, float rightWidth, float topHeight, float bottomHeight, float scale, in CSDL.Video.FRect dstrect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTexture9Grid"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool RenderTexture9GridNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, CSDL.Video.FRect* srcrect, float leftWidth, float rightWidth, float topHeight, float bottomHeight, float scale, CSDL.Video.FRect* dstrect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTexture9GridTiled"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderTexture9GridTiled(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, in CSDL.Video.FRect srcrect, float leftWidth, float rightWidth, float topHeight, float bottomHeight, float scale, in CSDL.Video.FRect dstrect, float tileScale);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTexture9GridTiled"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool RenderTexture9GridTiledNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, CSDL.Video.FRect* srcrect, float leftWidth, float rightWidth, float topHeight, float bottomHeight, float scale, CSDL.Video.FRect* dstrect, float tileScale);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTextureAffine"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderTextureAffine(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, in CSDL.Video.FRect srcrect, in CSDL.Video.FPoint origin, in CSDL.Video.FPoint right, in CSDL.Video.FPoint down);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTextureAffine"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool RenderTextureAffineNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, CSDL.Video.FRect* srcrect, CSDL.Video.FPoint* origin, CSDL.Video.FPoint* right, CSDL.Video.FPoint* down);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTextureRotated"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderTextureRotated(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, in CSDL.Video.FRect srcrect, in CSDL.Video.FRect dstrect, double angle, in CSDL.Video.FPoint center, CSDL.Video.FlipMode flip);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTextureRotated"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool RenderTextureRotatedNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, CSDL.Video.FRect* srcrect, CSDL.Video.FRect* dstrect, double angle, in CSDL.Video.FPoint center, CSDL.Video.FlipMode flip);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTextureTiled"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderTextureTiled(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, in CSDL.Video.FRect srcrect, float scale, in CSDL.Video.FRect dstrect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderTextureTiled"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool RenderTextureTiledNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture, CSDL.Video.FRect* srcrect, float scale, CSDL.Video.FRect* dstrect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RenderViewportSet"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RenderViewportSet(NativePtr<CSDL.Opaque.SdlRenderer> renderer);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetDefaultTextureScaleMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetDefaultTextureScaleMode(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.Video.ScaleMode scaleMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetGPURenderState"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetGPURenderState(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Opaque.SdlGPURenderState> state);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetGPURenderStateFragmentUniforms"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetGPURenderStateFragmentUniforms(NativePtr<CSDL.Opaque.SdlGPURenderState> state, uint slotIndex, IntPtr data, uint length);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetGPURenderStateSamplerBindings"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetGPURenderStateSamplerBindings(NativePtr<CSDL.Opaque.SdlGPURenderState> state, int numSamplerBindings, NativePtr<CSDL.GPU.GPUTextureSamplerBinding> samplerBindings);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetGPURenderStateSamplerBindings"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetGPURenderStateSamplerBindings(NativePtr<CSDL.Opaque.SdlGPURenderState> state, int numSamplerBindings, ReadOnlySpan<CSDL.GPU.GPUTextureSamplerBinding> samplerBindings);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetGPURenderStateStorageBuffers"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetGPURenderStateStorageBuffers(NativePtr<CSDL.Opaque.SdlGPURenderState> state, int numStorageBuffers, NativePtr<nint> storageBuffers);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetGPURenderStateStorageTextures"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetGPURenderStateStorageTextures(NativePtr<CSDL.Opaque.SdlGPURenderState> state, int numStorageTextures, NativePtr<nint> storageTextures);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderClipRect"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderClipRect(NativePtr<CSDL.Opaque.SdlRenderer> renderer, in CSDL.Video.Rect rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderClipRect"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool SetRenderClipRectNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.Video.Rect* rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderColorScale"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderColorScale(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float scale);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderDrawBlendMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderDrawBlendMode(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.Video.BlendMode blendMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderDrawColor"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderDrawColor(NativePtr<CSDL.Opaque.SdlRenderer> renderer, byte r, byte g, byte b, byte a);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderDrawColorFloat"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderDrawColorFloat(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float r, float g, float b, float a);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderLogicalPresentation"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderLogicalPresentation(NativePtr<CSDL.Opaque.SdlRenderer> renderer, int w, int h, CSDL.Video.RendererLogicalPresentation mode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderScale"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderScale(NativePtr<CSDL.Opaque.SdlRenderer> renderer, float scaleX, float scaleY);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderTarget"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderTarget(NativePtr<CSDL.Opaque.SdlRenderer> renderer, NativePtr<CSDL.Video.TextureData> texture);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderTextureAddressMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderTextureAddressMode(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.Video.TextureAddressMode uMode, CSDL.Video.TextureAddressMode vMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderViewport"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderViewport(NativePtr<CSDL.Opaque.SdlRenderer> renderer, in CSDL.Video.Rect rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderViewport"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool SetRenderViewportNullable(NativePtr<CSDL.Opaque.SdlRenderer> renderer, CSDL.Video.Rect* rect);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetRenderVSync"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetRenderVSync(NativePtr<CSDL.Opaque.SdlRenderer> renderer, int vsync);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetTextureAlphaMod"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetTextureAlphaMod(NativePtr<CSDL.Video.TextureData> texture, byte alpha);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetTextureAlphaModFloat"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetTextureAlphaModFloat(NativePtr<CSDL.Video.TextureData> texture, float alpha);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetTextureBlendMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetTextureBlendMode(NativePtr<CSDL.Video.TextureData> texture, CSDL.Video.BlendMode blendMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetTextureColorMod"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetTextureColorMod(NativePtr<CSDL.Video.TextureData> texture, byte r, byte g, byte b);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetTextureColorModFloat"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetTextureColorModFloat(NativePtr<CSDL.Video.TextureData> texture, float r, float g, float b);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetTexturePalette"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetTexturePalette(NativePtr<CSDL.Video.TextureData> texture, NativePtr<CSDL.Video.PaletteData> palette);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetTextureScaleMode"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetTextureScaleMode(NativePtr<CSDL.Video.TextureData> texture, CSDL.Video.ScaleMode scaleMode);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_UnlockTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void UnlockTexture(NativePtr<CSDL.Video.TextureData> texture);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_UpdateNVTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool UpdateNVTexture(NativePtr<CSDL.Video.TextureData> texture, NativePtr<CSDL.Video.Rect> rect, NativePtr<byte> yplane, int ypitch, NativePtr<byte> uVplane, int uVpitch);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_UpdateTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool UpdateTexture(NativePtr<CSDL.Video.TextureData> texture, in CSDL.Video.Rect rect, IntPtr pixels, int pitch);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_UpdateTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial CBool UpdateTextureNullable(NativePtr<CSDL.Video.TextureData> texture, CSDL.Video.Rect* rect, IntPtr pixels, int pitch);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_UpdateYUVTexture"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool UpdateYUVTexture(NativePtr<CSDL.Video.TextureData> texture, NativePtr<CSDL.Video.Rect> rect, NativePtr<byte> yplane, int ypitch, NativePtr<byte> uplane, int upitch, NativePtr<byte> vplane, int vpitch);

    }
}
