// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Mixer {
    /// <summary>
    /// <para>A callback that fires when a <c>MIX_Group</c> has completed mixing.</para>
    /// </summary>
    /// <param name="userData">an opaque pointer provided by the app for its personal use.</param>
    /// <param name="group">the group that is being mixed.</param>
    /// <param name="spec">the format of the data in <c>pcm</c>.</param>
    /// <param name="pcm">the raw PCM data in float32 format.</param>
    /// <param name="samples">the number of float values pointed to by <c>pcm</c>.</param>
    /// <remarks>
    /// <para>This callback is fired when a mixing group has finished mixing: all tracks in the group have mixed into a single buffer and are prepared to be mixed into all other groups for the final mix output.</para>
    /// <para>The audio data passed through here is _not_ const data; the app is permitted to change it in any way it likes, and those changes will propagate through the mixing pipeline.</para>
    /// <para>An audiospec is provided. Different groups might be in different formats, and an app needs to be able to handle that, but SDL_mixer always does its mixing work in 32-bit float samples, even if the inputs or final output are not floating point. As such, <c>spec->format</c> will always be <see cref="CSDL.Audio.AudioFormats.F32">F32</see> and <c>pcm</c> hardcoded to be a float pointer.</para>
    /// <para><c>samples</c> is the number of float values pointed to by <c>pcm</c>: samples, not sample frames! There are no promises how many samples will be provided per-callback, and this number can vary wildly from call to call, depending on many factors.</para>
    /// </remarks>
    /// <version>
    /// <para>This datatype is available since SDL_mixer 3.0.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_GroupMixCallback">MIX_GroupMixCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Mixer.Group.SetPostMixCallback">SetPostMixCallback</see></seealso>
    public delegate void GroupMixCallback(object? userData, nint group, in CSDL.Audio.AudioSpec spec, System.Span<float> pcm, int samples);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void MIX_GroupMixCallbackNative(nint userData, nint group, nint spec, nint pcm, int samples);

    internal static class GroupMixCallbackWrapper {
        public static unsafe MIX_GroupMixCallbackNative Create(GroupMixCallback fn) {
            return (userDataPtr, groupPtr, specPtr, pcmPtr, samples) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    nint group = groupPtr;
                    ref CSDL.Audio.AudioSpec spec = ref System.Runtime.CompilerServices.Unsafe.AsRef<CSDL.Audio.AudioSpec>((void*)specPtr);
                    System.Span<float> pcm = new System.Span<float>((void*)pcmPtr, samples);
                    fn(userData, group, in spec, pcm, samples);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return;
                }
            };
        }
    }

    /// <summary>
    /// <para>A callback that fires when all mixing has completed.</para>
    /// </summary>
    /// <param name="userData">an opaque pointer provided by the app for its personal use.</param>
    /// <param name="mixer">the mixer that is generating audio.</param>
    /// <param name="spec">the format of the data in <c>pcm</c>.</param>
    /// <param name="pcm">the raw PCM data in float32 format.</param>
    /// <param name="samples">the number of float values pointed to by <c>pcm</c>.</param>
    /// <remarks>
    /// <para>This callback is fired when the mixer has completed all its work. If this mixer was created with <see cref="CSDL.Mixer.Mixer(CSDL.Audio.AudioDeviceID,CSDL.Audio.AudioSpec?)">AudioSpec?)</see>, the data provided by this callback is what is being sent to the audio hardware, minus last conversions for format requirements. If this mixer was created with <see cref="CSDL.Mixer.Mixer(CSDL.Audio.AudioSpec)">AudioSpec)</see>, this is what is being output from <see cref="CSDL.Mixer.Mixer.Generate">Generate</see>, after final conversions.</para>
    /// <para>The audio data passed through here is _not_ const data; the app is permitted to change it in any way it likes, and those changes will replace the final mixer pipeline output.</para>
    /// <para>An audiospec is provided. SDL_mixer always does its mixing work in 32-bit float samples, even if the inputs or final output are not floating point. As such, <c>spec->format</c> will always be <see cref="CSDL.Audio.AudioFormats.F32">F32</see> and <c>pcm</c> hardcoded to be a float pointer.</para>
    /// <para><c>samples</c> is the number of float values pointed to by <c>pcm</c>: samples, not sample frames! There are no promises how many samples will be provided per-callback, and this number can vary wildly from call to call, depending on many factors.</para>
    /// </remarks>
    /// <version>
    /// <para>This datatype is available since SDL_mixer 3.0.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PostMixCallback">MIX_PostMixCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Mixer.Mixer.SetPostMixCallback">SetPostMixCallback</see></seealso>
    public delegate void PostMixCallback(object? userData, nint mixer, in CSDL.Audio.AudioSpec spec, System.Span<float> pcm, int samples);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void MIX_PostMixCallbackNative(nint userData, nint mixer, nint spec, nint pcm, int samples);

    internal static class PostMixCallbackWrapper {
        public static unsafe MIX_PostMixCallbackNative Create(PostMixCallback fn) {
            return (userDataPtr, mixerPtr, specPtr, pcmPtr, samples) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    nint mixer = mixerPtr;
                    ref CSDL.Audio.AudioSpec spec = ref System.Runtime.CompilerServices.Unsafe.AsRef<CSDL.Audio.AudioSpec>((void*)specPtr);
                    System.Span<float> pcm = new System.Span<float>((void*)pcmPtr, samples);
                    fn(userData, mixer, in spec, pcm, samples);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return;
                }
            };
        }
    }

    /// <summary>
    /// <para>A callback that fires when a <c>MIX_Track</c> is mixing at various stages.</para>
    /// </summary>
    /// <param name="userData">an opaque pointer provided by the app for its personal use.</param>
    /// <param name="track">the track that is being mixed.</param>
    /// <param name="spec">the format of the data in <c>pcm</c>.</param>
    /// <param name="pcm">the raw PCM data in float32 format.</param>
    /// <param name="samples">the number of float values pointed to by <c>pcm</c>.</param>
    /// <remarks>
    /// <para>This callback is fired for different parts of the mixing pipeline, and gives the app visbility into the audio data that is being generated at various stages.</para>
    /// <para>The audio data passed through here is _not_ const data; the app is permitted to change it in any way it likes, and those changes will propagate through the mixing pipeline.</para>
    /// <para>An audiospec is provided. Different tracks might be in different formats, and an app needs to be able to handle that, but SDL_mixer always does its mixing work in 32-bit float samples, even if the inputs or final output are not floating point. As such, <c>spec->format</c> will always be <see cref="CSDL.Audio.AudioFormats.F32">F32</see> and <c>pcm</c> hardcoded to be a float pointer.</para>
    /// <para><c>samples</c> is the number of float values pointed to by <c>pcm</c>: samples, not sample frames! There are no promises how many samples will be provided per-callback, and this number can vary wildly from call to call, depending on many factors.</para>
    /// <para>Making changes to the track during this callback is undefined behavior. Change the data in <c>pcm</c> but not the track itself.</para>
    /// </remarks>
    /// <version>
    /// <para>This datatype is available since SDL_mixer 3.0.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_TrackMixCallback">MIX_TrackMixCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Mixer.Track.SetRawCallback">SetRawCallback</see></seealso>
    /// <seealso><see cref="CSDL.Mixer.Track.SetCookedCallback">SetCookedCallback</see></seealso>
    public delegate void TrackMixCallback(object? userData, nint track, in CSDL.Audio.AudioSpec spec, System.Span<float> pcm, int samples);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void MIX_TrackMixCallbackNative(nint userData, nint track, nint spec, nint pcm, int samples);

    internal static class TrackMixCallbackWrapper {
        public static unsafe MIX_TrackMixCallbackNative Create(TrackMixCallback fn) {
            return (userDataPtr, trackPtr, specPtr, pcmPtr, samples) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    nint track = trackPtr;
                    ref CSDL.Audio.AudioSpec spec = ref System.Runtime.CompilerServices.Unsafe.AsRef<CSDL.Audio.AudioSpec>((void*)specPtr);
                    System.Span<float> pcm = new System.Span<float>((void*)pcmPtr, samples);
                    fn(userData, track, in spec, pcm, samples);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return;
                }
            };
        }
    }

    /// <summary>
    /// <para>A callback that fires when a <c>MIX_Track</c> is stopped.</para>
    /// </summary>
    /// <param name="userData">an opaque pointer provided by the app for its personal use.</param>
    /// <param name="track">the track that has stopped.</param>
    /// <remarks>
    /// <para>This callback is fired when a track completes playback, either because it ran out of data to mix (and all loops were completed as well), or it was explicitly stopped by the app. Pausing a track will not fire this callback.</para>
    /// <para>It is legal to adjust the track, including changing its input and restarting it. If this is done because it ran out of data in the middle of mixing, the mixer will start mixing the new track state in its current run without any gap in the audio.</para>
    /// <para>This callback will not fire when a playing track is destroyed.</para>
    /// </remarks>
    /// <version>
    /// <para>This datatype is available since SDL_mixer 3.0.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_TrackStoppedCallback">MIX_TrackStoppedCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Mixer.Track.SetStoppedCallback">SetStoppedCallback</see></seealso>
    public delegate void TrackStoppedCallback(object? userData, nint track);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void MIX_TrackStoppedCallbackNative(nint userData, nint track);

    internal static class TrackStoppedCallbackWrapper {
        public static MIX_TrackStoppedCallbackNative Create(TrackStoppedCallback fn) {
            return (userDataPtr, trackPtr) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    nint track = trackPtr;
                    fn(userData, track);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return;
                }
            };
        }
    }

}
