// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Mixer {
    public static partial class Macros {
        /// <summary>
        /// <para>The current major version of SDL_mixer headers.</para>
        /// </summary>
        /// <remarks>
        /// <para>If this were SDL_mixer version 3.2.1, this value would be 3.</para>
        /// </remarks>
        /// <since>This macro is available since SDL_mixer 3.0.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MIXER_MAJOR_VERSION">SDL_MIXER_MAJOR_VERSION</seealso></SDLWiki>
        public const uint MixerMajorVersion = 3;

        /// <summary>
        /// <para>The current micro (or patchlevel) version of the SDL_mixer headers.</para>
        /// </summary>
        /// <remarks>
        /// <para>If this were SDL_mixer version 3.2.1, this value would be 1.</para>
        /// </remarks>
        /// <since>This macro is available since SDL_mixer 3.0.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MIXER_MICRO_VERSION">SDL_MIXER_MICRO_VERSION</seealso></SDLWiki>
        public const uint MixerMicroVersion = 0;

        /// <summary>
        /// <para>The current minor version of the SDL_mixer headers.</para>
        /// </summary>
        /// <remarks>
        /// <para>If this were SDL_mixer version 3.2.1, this value would be 2.</para>
        /// </remarks>
        /// <since>This macro is available since SDL_mixer 3.0.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MIXER_MINOR_VERSION">SDL_MIXER_MINOR_VERSION</seealso></SDLWiki>
        public const uint MixerMinorVersion = 3;

        /// <summary>
        /// <para>This is the current version number macro of the SDL_mixer headers.</para>
        /// </summary>
        /// <since>This macro is available since SDL_mixer 3.0.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MIXER_VERSION">SDL_MIXER_VERSION</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Mixer.Mixer.Version">Version</see></seealso>
        // TODO: Unsupported constant macro 'SDL_MIXER_VERSION'.

        /// <summary>
        /// <para>This macro will evaluate to true if compiled with SDL_mixer at least X.Y.Z.</para>
        /// </summary>
        /// <since>This macro is available since SDL_mixer 3.0.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MIXER_VERSION_ATLEAST">SDL_MIXER_VERSION_ATLEAST</seealso></SDLWiki>
        public static bool MixerVersionAtleast(uint x, uint y, uint z) => ((MixerMajorVersion >= x) && (MixerMajorVersion > x || MixerMinorVersion >= y) && (MixerMajorVersion > x || MixerMinorVersion > y || MixerMicroVersion >= z));

    }
}
