// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Mixer {
    /// <summary>
    /// <para>3D coordinates for <see cref="CSDL.Mixer.Track.Set3DPosition">Set3DPosition</see>.</para>
    /// </summary>
    /// <remarks>
    /// <para>The coordinates use a "right-handed" coordinate system, like OpenGL and OpenAL.</para>
    /// </remarks>
    /// <since>This struct is available since SDL_mixer 3.0.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_Point3D">MIX_Point3D</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Mixer.Track.Set3DPosition">Set3DPosition</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Point3D {
        /// <summary>
        /// <para>X coordinate (negative left, positive right).</para>
        /// </summary>
        public float X;

        /// <summary>
        /// <para>Y coordinate (negative down, positive up).</para>
        /// </summary>
        public float Y;

        /// <summary>
        /// <para>Z coordinate (negative forward, positive back).</para>
        /// </summary>
        public float Z;
    }
}
