// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Mixer {
    public static partial class Props {
        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Load">Load</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_AUDIO_DECODER_STRING">MIX_PROP_AUDIO_DECODER_STRING</seealso></SDLWiki>
        public const string AudioDecoderString = "SDL_mixer.audio.decoder";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Load">Load</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_AUDIO_LOAD_CLOSEIO_BOOLEAN">MIX_PROP_AUDIO_LOAD_CLOSEIO_BOOLEAN</seealso></SDLWiki>
        public const string AudioLoadCloseioBoolean = "SDL_mixer.audio.load.closeio";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Load">Load</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_AUDIO_LOAD_IGNORE_LOOPS_BOOLEAN">MIX_PROP_AUDIO_LOAD_IGNORE_LOOPS_BOOLEAN</seealso></SDLWiki>
        public const string AudioLoadIgnoreLoopsBoolean = "SDL_mixer.audio.load.ignore_loops";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Load">Load</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_AUDIO_LOAD_IOSTREAM_POINTER">MIX_PROP_AUDIO_LOAD_IOSTREAM_POINTER</seealso></SDLWiki>
        public const string AudioLoadIostreamPointer = "SDL_mixer.audio.load.iostream";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Load">Load</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_AUDIO_LOAD_PREDECODE_BOOLEAN">MIX_PROP_AUDIO_LOAD_PREDECODE_BOOLEAN</seealso></SDLWiki>
        public const string AudioLoadPredecodeBoolean = "SDL_mixer.audio.load.predecode";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Load">Load</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_AUDIO_LOAD_PREFERRED_MIXER_POINTER">MIX_PROP_AUDIO_LOAD_PREFERRED_MIXER_POINTER</seealso></SDLWiki>
        public const string AudioLoadPreferredMixerPointer = "SDL_mixer.audio.load.preferred_mixer";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Load">Load</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_AUDIO_LOAD_SKIP_METADATA_TAGS_BOOLEAN">MIX_PROP_AUDIO_LOAD_SKIP_METADATA_TAGS_BOOLEAN</seealso></SDLWiki>
        public const string AudioLoadSkipMetadataTagsBoolean = "SDL_mixer.audio.load.skip_metadata_tags";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_METADATA_ALBUM_STRING">MIX_PROP_METADATA_ALBUM_STRING</seealso></SDLWiki>
        public const string MetadataAlbumString = "SDL_mixer.metadata.album";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_METADATA_ARTIST_STRING">MIX_PROP_METADATA_ARTIST_STRING</seealso></SDLWiki>
        public const string MetadataArtistString = "SDL_mixer.metadata.artist";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_METADATA_COPYRIGHT_STRING">MIX_PROP_METADATA_COPYRIGHT_STRING</seealso></SDLWiki>
        public const string MetadataCopyrightString = "SDL_mixer.metadata.copyright";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_METADATA_DURATION_FRAMES_NUMBER">MIX_PROP_METADATA_DURATION_FRAMES_NUMBER</seealso></SDLWiki>
        public const string MetadataDurationFramesNumber = "SDL_mixer.metadata.duration_frames";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_METADATA_DURATION_INFINITE_BOOLEAN">MIX_PROP_METADATA_DURATION_INFINITE_BOOLEAN</seealso></SDLWiki>
        public const string MetadataDurationInfiniteBoolean = "SDL_mixer.metadata.duration_infinite";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_METADATA_TITLE_STRING">MIX_PROP_METADATA_TITLE_STRING</seealso></SDLWiki>
        public const string MetadataTitleString = "SDL_mixer.metadata.title";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_METADATA_TOTAL_TRACKS_NUMBER">MIX_PROP_METADATA_TOTAL_TRACKS_NUMBER</seealso></SDLWiki>
        public const string MetadataTotalTracksNumber = "SDL_mixer.metadata.total_tracks";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_METADATA_TRACK_NUMBER">MIX_PROP_METADATA_TRACK_NUMBER</seealso></SDLWiki>
        public const string MetadataTrackNumber = "SDL_mixer.metadata.track";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Audio.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_METADATA_YEAR_NUMBER">MIX_PROP_METADATA_YEAR_NUMBER</seealso></SDLWiki>
        public const string MetadataYearNumber = "SDL_mixer.metadata.year";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Mixer.Properties">Properties</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_MIXER_DEVICE_NUMBER">MIX_PROP_MIXER_DEVICE_NUMBER</seealso></SDLWiki>
        public const string MixerDeviceNumber = "SDL_mixer.mixer.device";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_APPEND_SILENCE_FRAMES_NUMBER">MIX_PROP_PLAY_APPEND_SILENCE_FRAMES_NUMBER</seealso></SDLWiki>
        public const string PlayAppendSilenceFramesNumber = "SDL_mixer.play.append_silence_frames";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_APPEND_SILENCE_MILLISECONDS_NUMBER">MIX_PROP_PLAY_APPEND_SILENCE_MILLISECONDS_NUMBER</seealso></SDLWiki>
        public const string PlayAppendSilenceMillisecondsNumber = "SDL_mixer.play.append_silence_milliseconds";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_FADE_IN_FRAMES_NUMBER">MIX_PROP_PLAY_FADE_IN_FRAMES_NUMBER</seealso></SDLWiki>
        public const string PlayFadeInFramesNumber = "SDL_mixer.play.fade_in_frames";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_FADE_IN_MILLISECONDS_NUMBER">MIX_PROP_PLAY_FADE_IN_MILLISECONDS_NUMBER</seealso></SDLWiki>
        public const string PlayFadeInMillisecondsNumber = "SDL_mixer.play.fade_in_milliseconds";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_FADE_IN_START_GAIN_FLOAT">MIX_PROP_PLAY_FADE_IN_START_GAIN_FLOAT</seealso></SDLWiki>
        public const string PlayFadeInStartGainFloat = "SDL_mixer.play.fade_in_start_gain";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_HALT_WHEN_EXHAUSTED_BOOLEAN">MIX_PROP_PLAY_HALT_WHEN_EXHAUSTED_BOOLEAN</seealso></SDLWiki>
        public const string PlayHaltWhenExhaustedBoolean = "SDL_mixer.play.halt_when_exhausted";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_LOOPS_NUMBER">MIX_PROP_PLAY_LOOPS_NUMBER</seealso></SDLWiki>
        public const string PlayLoopsNumber = "SDL_mixer.play.loops";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_LOOP_START_FRAME_NUMBER">MIX_PROP_PLAY_LOOP_START_FRAME_NUMBER</seealso></SDLWiki>
        public const string PlayLoopStartFrameNumber = "SDL_mixer.play.loop_start_frame";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_LOOP_START_MILLISECOND_NUMBER">MIX_PROP_PLAY_LOOP_START_MILLISECOND_NUMBER</seealso></SDLWiki>
        public const string PlayLoopStartMillisecondNumber = "SDL_mixer.play.loop_start_millisecond";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_MAX_FRAME_NUMBER">MIX_PROP_PLAY_MAX_FRAME_NUMBER</seealso></SDLWiki>
        public const string PlayMaxFrameNumber = "SDL_mixer.play.max_frame";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_MAX_MILLISECONDS_NUMBER">MIX_PROP_PLAY_MAX_MILLISECONDS_NUMBER</seealso></SDLWiki>
        public const string PlayMaxMillisecondsNumber = "SDL_mixer.play.max_milliseconds";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_START_FRAME_NUMBER">MIX_PROP_PLAY_START_FRAME_NUMBER</seealso></SDLWiki>
        public const string PlayStartFrameNumber = "SDL_mixer.play.start_frame";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_START_MILLISECOND_NUMBER">MIX_PROP_PLAY_START_MILLISECOND_NUMBER</seealso></SDLWiki>
        public const string PlayStartMillisecondNumber = "SDL_mixer.play.start_millisecond";

        /// <summary>
        /// <para>Please refer to <see cref="CSDL.Mixer.Track.Play">Play</see> for details.</para>
        /// </summary>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_mixer/MIX_PROP_PLAY_START_ORDER_NUMBER">MIX_PROP_PLAY_START_ORDER_NUMBER</seealso></SDLWiki>
        public const string PlayStartOrderNumber = "SDL_mixer.play.start_order";

    }
}
