// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Internal.Docs {
    internal static partial class Events {
        /// <summary>
        /// <para>Add a callback to be triggered when an event is added to the event queue.</para>
        /// </summary>
        /// <remarks>
        /// <para><c>filter</c> will be called when an event happens, and its return value is ignored.</para>
        /// <para>**WARNING**: Be very careful of what you do in the event filter function, as it may run in a different thread!</para>
        /// <para>If the quit event is generated by a signal (e.g. SIGINT), it will bypass the internal queue and be delivered to the watch callback immediately, and arrive at the next event poll.</para>
        /// <para>Note: the callback is called for events posted by the user through <see cref="CSDL.Events.PushEvent">PushEvent</see>, but not for disabled events, nor for events by a filter callback set with <see cref="CSDL.Events.SetEventFilter">SetEventFilter</see>, nor for events posted by the user through <see cref="CSDL.Events.Peep">Peep</see>.</para>
        /// </remarks>
        /// <param name="filter">an <c>SDL_EventFilter</c> function to call when an event happens.</param>
        /// <param name="userdata">a pointer that is passed to <c>filter</c>.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_AddEventWatch">SDL_AddEventWatch</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.RemoveWatch">RemoveWatch</see></seealso>
        /// <seealso><see cref="CSDL.Events.SetEventFilter">SetEventFilter</see></seealso>
        public static extern void AddEventWatch();

        /// <summary>
        /// <para>Query the state of processing events by type.</para>
        /// </summary>
        /// <param name="type">the type of event; see <see cref="CSDL.EventType">EventType</see> for details.</param>
        /// <returns>
        /// <para>(bool) Returns true if the event is being processed, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_EventEnabled">SDL_EventEnabled</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.EnabledEvents.Enabled">Enabled</see></seealso>
        public static extern void EventEnabled();

        /// <summary>
        /// <para>Run a specific filter function on the current event queue, removing any events for which the filter returns false.</para>
        /// </summary>
        /// <remarks>
        /// <para>See <see cref="CSDL.Events.SetEventFilter">SetEventFilter</see> for more information. Unlike <see cref="CSDL.Events.SetEventFilter">SetEventFilter</see>, this function does not change the filter permanently, it only uses the supplied filter until this function returns.</para>
        /// </remarks>
        /// <param name="filter">the <c>SDL_EventFilter</c> function to call when an event happens.</param>
        /// <param name="userdata">a pointer that is passed to <c>filter</c>.</param>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_FilterEvents">SDL_FilterEvents</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.GetFilter">GetFilter</see></seealso>
        /// <seealso><see cref="CSDL.Events.SetEventFilter">SetEventFilter</see></seealso>
        public static extern void FilterEvents();

        /// <summary>
        /// <para>Clear events of a specific type from the event queue.</para>
        /// </summary>
        /// <remarks>
        /// <para>This will unconditionally remove any events from the queue that match <c>type</c>. If you need to remove a range of event types, use <see cref="CSDL.Events.Flush">Flush</see> instead.</para>
        /// <para>It's also normal to just ignore events you don't care about in your event loop without calling this function.</para>
        /// <para>This function only affects currently queued events. If you want to make sure that all pending OS events are flushed, you can call <see cref="CSDL.Events.Pump">Pump</see> on the main thread immediately before the flush call.</para>
        /// <para>If you have user events with custom data that needs to be freed, you should use <see cref="CSDL.Events.Peep">Peep</see> to remove and clean up those events before calling this function.</para>
        /// </remarks>
        /// <param name="type">the type of event to be cleared; see <see cref="CSDL.EventType">EventType</see> for details.</param>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_FlushEvent">SDL_FlushEvent</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.Flush">Flush</see></seealso>
        public static extern void FlushEvent();

        /// <summary>
        /// <para>Clear events of a range of types from the event queue.</para>
        /// </summary>
        /// <remarks>
        /// <para>This will unconditionally remove any events from the queue that are in the range of <c>minType</c> to <c>maxType</c>, inclusive. If you need to remove a single event type, use <see cref="CSDL.Events.Flush">Flush</see> instead.</para>
        /// <para>It's also normal to just ignore events you don't care about in your event loop without calling this function.</para>
        /// <para>This function only affects currently queued events. If you want to make sure that all pending OS events are flushed, you can call <see cref="CSDL.Events.Pump">Pump</see> on the main thread immediately before the flush call.</para>
        /// </remarks>
        /// <param name="minType">the low end of event type to be cleared, inclusive; see <see cref="CSDL.EventType">EventType</see> for details.</param>
        /// <param name="maxType">the high end of event type to be cleared, inclusive; see <see cref="CSDL.EventType">EventType</see> for details.</param>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_FlushEvents">SDL_FlushEvents</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.Flush">Flush</see></seealso>
        public static extern void FlushEvents();

        /// <summary>
        /// <para>Generate an English description of an event.</para>
        /// </summary>
        /// <remarks>
        /// <para>This will fill <c>buf</c> with a null-terminated string that might look something like this:</para>
        /// <code>
        /// SDL_EVENT_MOUSE_MOTION (timestamp=1140256324 windowid=2 which=0 state=0 x=492.99 y=139.09 xrel=52 yrel=6)
        /// </code>
        /// <para>The exact format of the string is not guaranteed; it is intended for logging purposes, to be read by a human, and not parsed by a computer.</para>
        /// <para>The returned value follows the same rules as <c>SDL_snprintf</c>: <c>buf</c> will always be NULL-terminated (unless <c>buflen</c> is zero), and will be truncated if <c>buflen</c> is too small. The return code is the number of bytes needed for the complete string, not counting the NULL-terminator, whether the string was truncated or not. Unlike <c>SDL_snprintf</c>, though, this function never returns -1.</para>
        /// </remarks>
        /// <param name="event">an event to describe. May be NULL.</param>
        /// <param name="buf">the buffer to fill with the description string. May be NULL.</param>
        /// <param name="buflen">the maximum bytes that can be written to <c>buf</c>.</param>
        /// <returns>
        /// <para>(int) Returns number of bytes needed for the full string, not counting the null-terminator byte.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.4.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetEventDescription">SDL_GetEventDescription</seealso></SDLWiki>
        public static extern void GetEventDescription();

        /// <summary>
        /// <para>Query the current event filter.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function can be used to "chain" filters, by saving the existing filter before replacing it with a function that will call that saved filter.</para>
        /// </remarks>
        /// <param name="filter">the current callback function will be stored here.</param>
        /// <param name="userdata">the pointer that is passed to the current event filter will be stored here.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false if there is no event filter set.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetEventFilter">SDL_GetEventFilter</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.SetEventFilter">SetEventFilter</see></seealso>
        public static extern void GetEventFilter();

        /// <summary>
        /// <para>Get window associated with an event.</para>
        /// </summary>
        /// <param name="event">an event containing a <c>windowID</c>.</param>
        /// <returns>
        /// <para>(<c>SDL_Window</c> *) Returns the associated window on success or NULL if there is none.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetWindowFromEvent">SDL_GetWindowFromEvent</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.PollEvent">PollEvent</see></seealso>
        /// <seealso><see cref="CSDL.Events.Wait">Wait</see></seealso>
        /// <seealso><see cref="CSDL.Events.WaitTimeout">WaitTimeout</see></seealso>
        public static extern void GetWindowFromEvent();

        /// <summary>
        /// <para>Check for the existence of a certain event type in the event queue.</para>
        /// </summary>
        /// <remarks>
        /// <para>If you need to check for a range of event types, use <see cref="CSDL.Events.Has">Has</see> instead.</para>
        /// </remarks>
        /// <param name="type">the type of event to be queried; see <see cref="CSDL.EventType">EventType</see> for details.</param>
        /// <returns>
        /// <para>(bool) Returns true if events matching <c>type</c> are present, or false if events matching <c>type</c> are not present.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasEvent">SDL_HasEvent</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.Has">Has</see></seealso>
        public static extern void HasEvent();

        /// <summary>
        /// <para>Check for the existence of certain event types in the event queue.</para>
        /// </summary>
        /// <remarks>
        /// <para>If you need to check for a single event type, use <see cref="CSDL.Events.Has">Has</see> instead.</para>
        /// </remarks>
        /// <param name="minType">the low end of event type to be queried, inclusive; see <see cref="CSDL.EventType">EventType</see> for details.</param>
        /// <param name="maxType">the high end of event type to be queried, inclusive; see <see cref="CSDL.EventType">EventType</see> for details.</param>
        /// <returns>
        /// <para>(bool) Returns true if events with type >= <c>minType</c> and &lt;= <c>maxType</c> are present, or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasEvents">SDL_HasEvents</seealso></SDLWiki>
        /// <seealso><see cref="HasEvents"/></seealso>
        public static extern void HasEvents();

        /// <summary>
        /// <para>Check the event queue for messages and optionally return them.</para>
        /// </summary>
        /// <remarks>
        /// <para><c>action</c> may be any of the following:</para>
        /// <list type="bullet">
        /// <item><description><see cref="CSDL.EventAction.Addevent">Addevent</see>: up to <c>numevents</c> events will be added to the back of the event queue.</description></item>
        /// <item><description><see cref="CSDL.EventAction.Peekevent">Peekevent</see>: <c>numevents</c> events at the front of the event queue, within the specified minimum and maximum type, will be returned to the caller and will _not_ be removed from the queue. If you pass NULL for <c>events</c>, then <c>numevents</c> is ignored and the total number of matching events will be returned.</description></item>
        /// <item><description><see cref="CSDL.EventAction.Getevent">Getevent</see>: up to <c>numevents</c> events at the front of the event queue, within the specified minimum and maximum type, will be returned to the caller and will be removed from the queue.</description></item>
        /// </list>
        /// <para>You may have to call <see cref="CSDL.Events.Pump">Pump</see> before calling this function. Otherwise, the events may not be ready to be filtered when you call <see cref="PeepEvents"/>.</para>
        /// </remarks>
        /// <param name="events">destination buffer for the retrieved events, may be NULL to leave the events in the queue and return the number of events that would have been stored.</param>
        /// <param name="numevents">if action is <see cref="CSDL.EventAction.Addevent">Addevent</see>, the number of events to add back to the event queue; if action is <see cref="CSDL.EventAction.Peekevent">Peekevent</see> or <see cref="CSDL.EventAction.Getevent">Getevent</see>, the maximum number of events to retrieve.</param>
        /// <param name="action">action to take; see <c>#remarks</c> for details.</param>
        /// <param name="minType">minimum value of the event type to be considered; <see cref="CSDL.EventType.First">First</see> is a safe choice.</param>
        /// <param name="maxType">maximum value of the event type to be considered; <see cref="CSDL.EventType.Last">Last</see> is a safe choice.</param>
        /// <returns>
        /// <para>(int) Returns the number of events actually stored or -1 on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PeepEvents">SDL_PeepEvents</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.PollEvent">PollEvent</see></seealso>
        /// <seealso><see cref="CSDL.Events.Pump">Pump</see></seealso>
        /// <seealso><see cref="CSDL.Events.PushEvent">PushEvent</see></seealso>
        public static extern void PeepEvents();

        /// <summary>
        /// <para>Poll for currently pending events.</para>
        /// </summary>
        /// <remarks>
        /// <para>If <c>event</c> is not NULL, the next event is removed from the queue and stored in the <see cref="CSDL.Event">Event</see> structure pointed to by <c>event</c>.</para>
        /// <para>If <c>event</c> is NULL, it simply returns true if there is an event in the queue, but will not remove it from the queue.</para>
        /// <para>As this function may implicitly call <see cref="CSDL.Events.Pump">Pump</see>, you can only call this function in the thread that initialized the video subsystem.</para>
        /// <para><see cref="PollEvent"/> is the favored way of receiving system events since it can be done from the main loop and does not suspend the main loop while waiting on an event to be posted.</para>
        /// <para>The common practice is to fully process the event queue once every frame, usually as a first step before updating the game's state:</para>
        /// <code language="c">
        /// while (game_is_still_running) {
        ///     SDL_Event event;
        ///     while (SDL_PollEvent(&amp;event)) {  // poll until all events are handled!
        ///         // decide what to do with this event.
        ///     }
        /// 
        ///     // update game state, draw the current frame
        /// }
        /// </code>
        /// <para>Note that Windows (and possibly other platforms) has a quirk about how it handles events while dragging/resizing a window, which can cause this function to block for significant amounts of time. Technical explanations and solutions are discussed on the wiki:</para>
        /// <para>https://wiki.libsdl.org/SDL3/AppFreezeDuringDrag</para>
        /// </remarks>
        /// <param name="event">the <see cref="CSDL.Event">Event</see> structure to be filled with the next event from the queue, or NULL.</param>
        /// <returns>
        /// <para>(bool) Returns true if this got an event or false if there are none available.</para>
        /// </returns>
        /// <threadsafety>This function should only be called on the main thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PollEvent">SDL_PollEvent</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.PushEvent">PushEvent</see></seealso>
        /// <seealso><see cref="CSDL.Events.Wait">Wait</see></seealso>
        /// <seealso><see cref="CSDL.Events.WaitTimeout">WaitTimeout</see></seealso>
        public static extern void PollEvent();

        /// <summary>
        /// <para>Pump the event loop, gathering events from the input devices.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function updates the event queue and internal input device state.</para>
        /// <para><see cref="PumpEvents"/> gathers all the pending input information from devices and places it in the event queue. Without calls to <see cref="PumpEvents"/> no events would ever be placed on the queue. Often the need for calls to <see cref="PumpEvents"/> is hidden from the user since <see cref="CSDL.Events.PollEvent">PollEvent</see> and <see cref="CSDL.Events.Wait">Wait</see> implicitly call <see cref="PumpEvents"/>. However, if you are not polling or waiting for events (e.g. you are filtering them), then you must call <see cref="PumpEvents"/> to force an event queue update.</para>
        /// </remarks>
        /// <threadsafety>This function should only be called on the main thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PumpEvents">SDL_PumpEvents</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.PollEvent">PollEvent</see></seealso>
        /// <seealso><see cref="CSDL.Events.Wait">Wait</see></seealso>
        public static extern void PumpEvents();

        /// <summary>
        /// <para>Add an event to the event queue.</para>
        /// </summary>
        /// <remarks>
        /// <para>The event queue can actually be used as a two way communication channel. Not only can events be read from the queue, but the user can also push their own events onto it. <c>event</c> is a pointer to the event structure you wish to push onto the queue. The event is copied into the queue, and the caller may dispose of the memory pointed to after <see cref="PushEvent"/> returns.</para>
        /// <para>Note: Pushing device input events onto the queue doesn't modify the state of the device within SDL.</para>
        /// <para>Note: Events pushed onto the queue with <see cref="PushEvent"/> get passed through the event filter but events added with <see cref="CSDL.Events.Peep">Peep</see> do not.</para>
        /// <para>For pushing application-specific events, please use <see cref="CSDL.Events.Register">Register</see> to get an event type that does not conflict with other code that also wants its own custom event types.</para>
        /// </remarks>
        /// <param name="event">the <see cref="CSDL.Event">Event</see> to be added to the queue.</param>
        /// <returns>
        /// <para>(bool) Returns true on success, false if the event was filtered or on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information. A common reason for error is the event queue being full.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PushEvent">SDL_PushEvent</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.Peep">Peep</see></seealso>
        /// <seealso><see cref="CSDL.Events.PollEvent">PollEvent</see></seealso>
        /// <seealso><see cref="CSDL.Events.Register">Register</see></seealso>
        public static extern void PushEvent();

        /// <summary>
        /// <para>Allocate a set of user-defined events, and return the beginning event number for that set of events.</para>
        /// </summary>
        /// <param name="numevents">the number of events to be allocated.</param>
        /// <returns>
        /// <para>(<c>Uint32</c>) Returns the beginning event number, or 0 if numevents is invalid or if there are not enough user-defined events left.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_RegisterEvents">SDL_RegisterEvents</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.PushEvent">PushEvent</see></seealso>
        public static extern void RegisterEvents();

        /// <summary>
        /// <para>Remove an event watch callback added with <see cref="CSDL.Events.AddWatch">AddWatch</see>.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function takes the same input as <see cref="CSDL.Events.AddWatch">AddWatch</see> to identify and delete the corresponding callback.</para>
        /// </remarks>
        /// <param name="filter">the function originally passed to <see cref="CSDL.Events.AddWatch">AddWatch</see>.</param>
        /// <param name="userdata">the pointer originally passed to <see cref="CSDL.Events.AddWatch">AddWatch</see>.</param>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_RemoveEventWatch">SDL_RemoveEventWatch</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.AddWatch">AddWatch</see></seealso>
        public static extern void RemoveEventWatch();

        /// <summary>
        /// <para>Set the state of processing events by type.</para>
        /// </summary>
        /// <param name="type">the type of event; see <see cref="CSDL.EventType">EventType</see> for details.</param>
        /// <param name="enabled">whether to process the event or not.</param>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SetEventEnabled">SDL_SetEventEnabled</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.EnabledEvents.EventEnabled">EventEnabled</see></seealso>
        public static extern void SetEventEnabled();

        /// <summary>
        /// <para>Set up a filter to process all events before they are added to the internal event queue.</para>
        /// </summary>
        /// <remarks>
        /// <para>If you just want to see events without modifying them or preventing them from being queued, you should use <see cref="CSDL.Events.AddWatch">AddWatch</see> instead.</para>
        /// <para>If the filter function returns true when called, then the event will be added to the internal queue. If it returns false, then the event will be dropped from the queue, but the internal state will still be updated. This allows selective filtering of dynamically arriving events.</para>
        /// <para>**WARNING**: Be very careful of what you do in the event filter function, as it may run in a different thread! The exception is handling of <see cref="CSDL.EventType.WindowExposed">WindowExposed</see>, which is guaranteed to be sent from the OS on the main thread and you are expected to redraw your window in response to this event.</para>
        /// <para>On platforms that support it, if the quit event is generated by an interrupt signal (e.g. pressing Ctrl-C), it will be delivered to the application at the next event poll.</para>
        /// <para>Note: Disabled events never make it to the event filter function; see <see cref="CSDL.Events.EnabledEvents.Enabled">Enabled</see>.</para>
        /// <para>Note: Events pushed onto the queue with <see cref="CSDL.Events.PushEvent">PushEvent</see> get passed through the event filter, but events pushed onto the queue with <see cref="CSDL.Events.Peep">Peep</see> do not.</para>
        /// </remarks>
        /// <param name="filter">a function to call when an event happens.</param>
        /// <param name="userdata">a pointer that is passed to <c>filter</c>.</param>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SetEventFilter">SDL_SetEventFilter</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.AddWatch">AddWatch</see></seealso>
        /// <seealso><see cref="CSDL.Events.EnabledEvents.Enabled">Enabled</see></seealso>
        /// <seealso><see cref="CSDL.Events.GetFilter">GetFilter</see></seealso>
        /// <seealso><see cref="CSDL.Events.Peep">Peep</see></seealso>
        /// <seealso><see cref="CSDL.Events.PushEvent">PushEvent</see></seealso>
        public static extern void SetEventFilter();

        /// <summary>
        /// <para>Wait indefinitely for the next available event.</para>
        /// </summary>
        /// <remarks>
        /// <para>If <c>event</c> is not NULL, the next event is removed from the queue and stored in the <see cref="CSDL.Event">Event</see> structure pointed to by <c>event</c>.</para>
        /// <para>As this function may implicitly call <see cref="CSDL.Events.Pump">Pump</see>, you can only call this function in the thread that initialized the video subsystem.</para>
        /// </remarks>
        /// <param name="event">the <see cref="CSDL.Event">Event</see> structure to be filled in with the next event from the queue, or NULL.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false if there was an error while waiting for events; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>This function should only be called on the main thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_WaitEvent">SDL_WaitEvent</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.PollEvent">PollEvent</see></seealso>
        /// <seealso><see cref="CSDL.Events.PushEvent">PushEvent</see></seealso>
        /// <seealso><see cref="CSDL.Events.WaitTimeout">WaitTimeout</see></seealso>
        public static extern void WaitEvent();

        /// <summary>
        /// <para>Wait until the specified timeout (in milliseconds) for the next available event.</para>
        /// </summary>
        /// <remarks>
        /// <para>If <c>event</c> is not NULL, the next event is removed from the queue and stored in the <see cref="CSDL.Event">Event</see> structure pointed to by <c>event</c>.</para>
        /// <para>As this function may implicitly call <see cref="CSDL.Events.Pump">Pump</see>, you can only call this function in the thread that initialized the video subsystem.</para>
        /// <para>The timeout is not guaranteed, the actual wait time could be longer due to system scheduling.</para>
        /// </remarks>
        /// <param name="event">the <see cref="CSDL.Event">Event</see> structure to be filled in with the next event from the queue, or NULL.</param>
        /// <param name="timeoutMS">the maximum number of milliseconds to wait for the next available event, or -1 to wait indefinitely.</param>
        /// <returns>
        /// <para>(bool) Returns true if this got an event or false if the timeout elapsed without any events available.</para>
        /// </returns>
        /// <threadsafety>This function should only be called on the main thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_WaitEventTimeout">SDL_WaitEventTimeout</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Events.PollEvent">PollEvent</see></seealso>
        /// <seealso><see cref="CSDL.Events.PushEvent">PushEvent</see></seealso>
        /// <seealso><see cref="CSDL.Events.Wait">Wait</see></seealso>
        public static extern void WaitEventTimeout();
    }
}
