// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL {
    internal static partial class SDL {
        [LibraryImport(SDLLibrary, EntryPoint = "SDL_AddEventWatch"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool AddEventWatch(SDL_EventFilterNative filter, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_EventEnabled"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool EventEnabled(uint type);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_FilterEvents"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void FilterEvents(SDL_EventFilterNative filter, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_FlushEvent"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void FlushEvent(uint type);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_FlushEvents"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void FlushEvents(uint minType, uint maxType);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetEventDescription"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial int GetEventDescription(in CSDL.Event @event, NativePtr<byte> buf, int buflen);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetEventDescription"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial int GetEventDescriptionNullable(CSDL.Event* @event, NativePtr<byte> buf, int buflen);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetEventDescription"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial int GetEventDescription(in CSDL.Event @event, Span<byte> buf, int buflen);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetEventFilter"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetEventFilter(out SDL_EventFilterNative filter, out IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetWindowFromEvent"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlWindow> GetWindowFromEvent(in CSDL.Event @event);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_HasEvent"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool HasEvent(uint type);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_HasEvents"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool HasEvents(uint minType, uint maxType);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_PeepEvents"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial int PeepEvents(NativePtr<CSDL.Event> events, int numevents, CSDL.EventAction action, uint minType, uint maxType);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_PeepEvents"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial int PeepEvents(Span<CSDL.Event> events, int numevents, CSDL.EventAction action, uint minType, uint maxType);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_PollEvent"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool PollEvent(out CSDL.Event @event);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_PumpEvents"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void PumpEvents();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_PushEvent"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool PushEvent(ref CSDL.Event @event);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RegisterEvents"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial uint RegisterEvents(int numevents);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RemoveEventWatch"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void RemoveEventWatch(SDL_EventFilterNative filter, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetEventEnabled"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void SetEventEnabled(uint type, CBool enabled);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetEventFilter"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void SetEventFilter(SDL_EventFilterNative filter, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WaitEvent"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WaitEvent(out CSDL.Event @event);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_WaitEventTimeout"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool WaitEventTimeout(out CSDL.Event @event, int timeoutMs);

    }
}
