// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>Joystick trackball motion event structure (event.jball.*)</para>
    /// </summary>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_JoyBallEvent">SDL_JoyBallEvent</seealso></SDLWiki>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct JoyBallEvent {
        /// <summary>
        /// <para>SDL_EVENT_JOYSTICK_BALL_MOTION</para>
        /// </summary>
        public CSDL.EventType Type;

        private uint _reserved;

        /// <summary>
        /// <para>In nanoseconds, populated using SDL_GetTicksNS()</para>
        /// </summary>
        public ulong Timestamp;

        /// <summary>
        /// <para>The joystick instance id</para>
        /// </summary>
        public CSDL.Input.JoystickID Which;

        /// <summary>
        /// <para>The joystick trackball index</para>
        /// </summary>
        public byte Ball;

        private byte _padding1;

        private byte _padding2;

        private byte _padding3;

        /// <summary>
        /// <para>The relative motion in the X direction</para>
        /// </summary>
        public short Xrel;

        /// <summary>
        /// <para>The relative motion in the Y direction</para>
        /// </summary>
        public short Yrel;
    }
}
