// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>Mouse button event structure (event.button.*)</para>
    /// </summary>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MouseButtonEvent">SDL_MouseButtonEvent</seealso></SDLWiki>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct MouseButtonEvent {
        /// <summary>
        /// <para>SDL_EVENT_MOUSE_BUTTON_DOWN or SDL_EVENT_MOUSE_BUTTON_UP</para>
        /// </summary>
        public CSDL.EventType Type;

        private uint _reserved;

        /// <summary>
        /// <para>In nanoseconds, populated using SDL_GetTicksNS()</para>
        /// </summary>
        public ulong Timestamp;

        /// <summary>
        /// <para>The window with mouse focus, if any</para>
        /// </summary>
        public CSDL.Video.WindowID WindowID;

        /// <summary>
        /// <para>The mouse instance id in relative mode, SDL_TOUCH_MOUSEID for touch events, or 0</para>
        /// </summary>
        public CSDL.Input.MouseID Which;

        /// <summary>
        /// <para>The mouse button index</para>
        /// </summary>
        public byte Button;

        private CBool _down;

        /// <summary>
        /// <para>true if the button is pressed</para>
        /// </summary>
        public bool Down { readonly get => _down; set => _down = value; }

        /// <summary>
        /// <para>1 for single-click, 2 for double-click, etc.</para>
        /// </summary>
        public byte Clicks;

        private byte _padding;

        /// <summary>
        /// <para>X coordinate, relative to window</para>
        /// </summary>
        public float X;

        /// <summary>
        /// <para>Y coordinate, relative to window</para>
        /// </summary>
        public float Y;
    }
}
