// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>Notification dialog event structure (event.notification.*)</para>
    /// </summary>
    /// <remarks>
    /// <para>An <see cref="ActionID"/> value of 'default' for an <see cref="CSDL.EventType.NotificationActionInvoked">NotificationActionInvoked</see> event indicates that the notification was interacted with without selecting a specific action (e.g. the body of the notification was clicked on).</para>
    /// </remarks>
    /// <since>This struct is available since SDL 3.6.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_NotificationEvent">SDL_NotificationEvent</seealso></SDLWiki>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct NotificationEvent {
        /// <summary>
        /// <para>SDL_EVENT_NOTIFICATION_ACTION_INVOKED</para>
        /// </summary>
        public CSDL.EventType Type;

        private uint _reserved;

        /// <summary>
        /// <para>In nanoseconds, populated using SDL_GetTicksNS()</para>
        /// </summary>
        public ulong Timestamp;

        /// <summary>
        /// <para>The ID of the notification that generated this event.</para>
        /// </summary>
        public CSDL.NotificationID Which;

        /// <summary>
        /// <para>The identifier string of the action invoked in the notification dialog.</para>
        /// </summary>
        private nint _actionID;

        public string ActionID => Marshal.PtrToStringUTF8(_actionID);
    }
}
