// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>This is a unique identifier for a system notification.</para>
    /// </summary>
    /// <remarks>
    /// <para>The value 0 is an invalid notification ID.</para>
    /// </remarks>
    /// <since>This datatype is available since SDL 3.6.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_NotificationID">SDL_NotificationID</seealso></SDLWiki>
    public readonly record struct NotificationID(uint Value) {
        public static implicit operator uint(NotificationID id) => id.Value;
        public static implicit operator NotificationID(uint value) => new(value);
        public override string ToString() => Value.ToString();
    }
}
