// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>Pressure-sensitive pen motion event structure (event.pmotion.*)</para>
    /// </summary>
    /// <remarks>
    /// <para>Depending on the hardware, you may get motion events when the pen is not touching a tablet, for tracking a pen even when it isn't drawing. You should listen for <see cref="CSDL.EventType.PenDown">PenDown</see> and <see cref="CSDL.EventType.PenUp">PenUp</see> events, or check <c>pen_state &amp; SDL_PEN_INPUT_DOWN</c> to decide if a pen is "drawing" when dealing with pen motion.</para>
    /// </remarks>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PenMotionEvent">SDL_PenMotionEvent</seealso></SDLWiki>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct PenMotionEvent {
        /// <summary>
        /// <para>SDL_EVENT_PEN_MOTION</para>
        /// </summary>
        public CSDL.EventType Type;

        private uint _reserved;

        /// <summary>
        /// <para>In nanoseconds, populated using SDL_GetTicksNS()</para>
        /// </summary>
        public ulong Timestamp;

        /// <summary>
        /// <para>The window with pen focus, if any</para>
        /// </summary>
        public CSDL.Video.WindowID WindowID;

        /// <summary>
        /// <para>The pen instance id</para>
        /// </summary>
        public CSDL.Input.PenID Which;

        /// <summary>
        /// <para>Complete pen input state at time of event</para>
        /// </summary>
        public CSDL.Input.PenInputFlags PenState;

        /// <summary>
        /// <para>X coordinate, relative to window</para>
        /// </summary>
        public float X;

        /// <summary>
        /// <para>Y coordinate, relative to window</para>
        /// </summary>
        public float Y;
    }
}
