// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>Pinch event structure (event.pinch.*)</para>
    /// </summary>
    /// <remarks>
    /// <para>span_(x/y) and focus_(x/y) are only available for pinch gestures on mobile devices</para>
    /// </remarks>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PinchFingerEvent">SDL_PinchFingerEvent</seealso></SDLWiki>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct PinchFingerEvent {
        /// <summary>
        /// <para>::SDL_EVENT_PINCH_BEGIN or ::SDL_EVENT_PINCH_UPDATE or ::SDL_EVENT_PINCH_END</para>
        /// </summary>
        public CSDL.EventType Type;

        private uint _reserved;

        /// <summary>
        /// <para>In nanoseconds, populated using SDL_GetTicksNS()</para>
        /// </summary>
        public ulong Timestamp;

        /// <summary>
        /// <para>The scale change since the last SDL_EVENT_PINCH_UPDATE. Scale &lt; 1 is "zoom out". Scale > 1 is "zoom in".</para>
        /// </summary>
        public float Scale;

        /// <summary>
        /// <para>The window underneath the finger, if any</para>
        /// </summary>
        public CSDL.Video.WindowID WindowID;

        /// <summary>
        /// <para>On mobile devices for BEGIN and UPDATE events, the average X distance between each of the pointers forming the pinch in window coordinates. Otherwise, -1.</para>
        /// </summary>
        public float SpanX;

        /// <summary>
        /// <para>On mobile devices for BEGIN and UPDATE events, the average Y distance between each of the pointers forming the pinch in window coordinates. Otherwise, -1.</para>
        /// </summary>
        public float SpanY;

        /// <summary>
        /// <para>On mobile devices for BEGIN and UPDATE events, the X coordinate of the current gesture's focal point in window coordinates. Otherwise, -1.</para>
        /// </summary>
        public float FocusX;

        /// <summary>
        /// <para>On mobile devices for BEGIN and UPDATE events, the Y coordinate of the current gesture's focal point in window coordinates. Otherwise, -1.</para>
        /// </summary>
        public float FocusY;
    }
}
