// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Video {
    /// <summary>
    /// <para>An EGL integer attribute, used when creating an EGL surface.</para>
    /// </summary>
    /// <since>This datatype is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_EGLint">SDL_EGLint</seealso></SDLWiki>
    public readonly record struct EGLint(int Value) {
        public static implicit operator int(EGLint id) => id.Value;
        public static implicit operator EGLint(int value) => new(value);
        public override string ToString() => Value.ToString();
    }
}
