// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Video {
    /// <summary>
    /// <para>Possible flags to be set for the <see cref="CSDL.Video.GLAttr.ContextFlags">ContextFlags</see> attribute.</para>
    /// </summary>
    /// <since>This datatype is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GLContextFlag">SDL_GLContextFlag</seealso></SDLWiki>
    [System.Flags]
    public enum GLContextFlag : uint {
        DebugFlag = 0x0001,
        ForwardCompatibleFlag = 0x0002,
        RobustAccessFlag = 0x0004,
        ResetIsolationFlag = 0x0008,
    }
}
