// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Video {
    /// <summary>
    /// <para>Possible values to be set <see cref="CSDL.Video.GLAttr.ContextResetNotification">ContextResetNotification</see> attribute.</para>
    /// </summary>
    /// <since>This datatype is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GLContextResetNotification">SDL_GLContextResetNotification</seealso></SDLWiki>
    [System.Flags]
    public enum GLContextResetNotification : uint {
        NoNotification = 0x0000,
        LoseContext = 0x0001,
    }
}
