// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Video {
    /// <summary>
    /// <para>Window progress state</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.8</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_ProgressState">SDL_ProgressState</seealso></SDLWiki>
    public enum ProgressState {
        /// <summary>
        /// <para>An invalid progress state indicating an error; check SDL_GetError()</para>
        /// </summary>
        Invalid = -1,
        /// <summary>
        /// <para>No progress bar is shown</para>
        /// </summary>
        None,
        /// <summary>
        /// <para>The progress bar is shown in a indeterminate state</para>
        /// </summary>
        Indeterminate,
        /// <summary>
        /// <para>The progress bar is shown in a normal state</para>
        /// </summary>
        Normal,
        /// <summary>
        /// <para>The progress bar is shown in a paused state</para>
        /// </summary>
        Paused,
        /// <summary>
        /// <para>The progress bar is shown in a state indicating the application had an error</para>
        /// </summary>
        Error,
    }
}
