// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Video {
    /// <summary>
    /// <para>EGL platform attribute initialization callback.</para>
    /// </summary>
    /// <param name="userData">an app-controlled pointer that is passed to the callback.</param>
    /// <returns>
    /// <para>Returns a newly-allocated array of attributes, terminated with <c>EGL_NONE</c>.</para>
    /// </returns>
    /// <remarks>
    /// <para>This is called when SDL is attempting to create an EGL context, to let the app add extra attributes to its eglGetPlatformDisplay() call.</para>
    /// <para>The callback should return a pointer to an EGL attribute array terminated with <c>EGL_NONE</c>. If this function returns NULL, the <see cref="CSDL.Video.Window(string,int,int,WindowFlags)">Window(string,int,int,WindowFlags)</see> process will fail gracefully.</para>
    /// <para>The returned pointer should be allocated with <see cref="CSDL.Memory.Malloc">Malloc</see> and will be passed to <see cref="CSDL.Memory.Free">Free</see>.</para>
    /// <para>The arrays returned by each callback will be appended to the existing attribute arrays defined by SDL.</para>
    /// </remarks>
    /// <version>
    /// <para>This datatype is available since SDL 3.2.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_EGLAttribArrayCallback">SDL_EGLAttribArrayCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Video.EGL.SetAttributeCallbacks">SetAttributeCallbacks</see></seealso>
    public delegate NativePtr<CSDL.Video.EGLAttrib> EGLAttribArrayCallback(object? userData);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate nint SDL_EGLAttribArrayCallbackNative(nint userData);

    internal static class EGLAttribArrayCallbackWrapper {
        public static SDL_EGLAttribArrayCallbackNative Create(EGLAttribArrayCallback fn) {
            return (userDataPtr) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    var result = fn(userData);
                    return result;
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return default;
                }
            };
        }
    }

    /// <summary>
    /// <para>EGL surface/context attribute initialization callback types.</para>
    /// </summary>
    /// <param name="userData">an app-controlled pointer that is passed to the callback.</param>
    /// <param name="display">the EGL display to be used.</param>
    /// <param name="config">the EGL config to be used.</param>
    /// <returns>
    /// <para>Returns a newly-allocated array of attributes, terminated with <c>EGL_NONE</c>.</para>
    /// </returns>
    /// <remarks>
    /// <para>This is called when SDL is attempting to create an EGL surface, to let the app add extra attributes to its eglCreateWindowSurface() or eglCreateContext calls.</para>
    /// <para>For convenience, the EGLDisplay and EGLConfig to use are provided to the callback.</para>
    /// <para>The callback should return a pointer to an EGL attribute array terminated with <c>EGL_NONE</c>. If this function returns NULL, the <see cref="CSDL.Video.Window(string,int,int,WindowFlags)">Window(string,int,int,WindowFlags)</see> process will fail gracefully.</para>
    /// <para>The returned pointer should be allocated with <see cref="CSDL.Memory.Malloc">Malloc</see> and will be passed to <see cref="CSDL.Memory.Free">Free</see>.</para>
    /// <para>The arrays returned by each callback will be appended to the existing attribute arrays defined by SDL.</para>
    /// </remarks>
    /// <version>
    /// <para>This datatype is available since SDL 3.2.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_EGLIntArrayCallback">SDL_EGLIntArrayCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Video.EGL.SetAttributeCallbacks">SetAttributeCallbacks</see></seealso>
    public delegate NativePtr<CSDL.Video.EGLint> EGLIntArrayCallback(object? userData, CSDL.Opaque.SdlEGLDisplay display, CSDL.Opaque.SdlEGLConfig config);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate nint SDL_EGLIntArrayCallbackNative(nint userData, CSDL.Opaque.SdlEGLDisplay display, CSDL.Opaque.SdlEGLConfig config);

    internal static class EGLIntArrayCallbackWrapper {
        public static SDL_EGLIntArrayCallbackNative Create(EGLIntArrayCallback fn) {
            return (userDataPtr, displayRaw, configRaw) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    CSDL.Opaque.SdlEGLDisplay display = displayRaw;
                    CSDL.Opaque.SdlEGLConfig config = configRaw;
                    var result = fn(userData, display, config);
                    return result;
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return default;
                }
            };
        }
    }

    /// <summary>
    /// <para>Callback used for hit-testing.</para>
    /// </summary>
    /// <param name="win">the <c>SDL_Window</c> where hit-testing was set on.</param>
    /// <param name="area">an <see cref="CSDL.Video.Point">Point</see> which should be hit-tested.</param>
    /// <param name="data">what was passed as <c>callback_data</c> to <see cref="CSDL.Video.Window.SetHitTest">SetHitTest</see>.</param>
    /// <returns>
    /// <para>Returns an <see cref="CSDL.Video.HitTestResult">HitTestResult</see> value.</para>
    /// </returns>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HitTest">SDL_HitTest</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Video.Window.SetHitTest">SetHitTest</see></seealso>
    public delegate CSDL.Video.HitTestResult HitTest(CSDL.Video.Window win, in CSDL.Video.Point area, nint data);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate CSDL.Video.HitTestResult SDL_HitTestNative(nint win, nint area, nint data);

    internal static class HitTestWrapper {
        public static unsafe SDL_HitTestNative Create(HitTest fn) {
            return (winPtr, areaPtr, dataPtr) => {
                try {
                    CSDL.Video.Window win = new CSDL.Video.Window(winPtr, false);
                    ref CSDL.Video.Point area = ref System.Runtime.CompilerServices.Unsafe.AsRef<CSDL.Video.Point>((void*)areaPtr);
                    nint data = dataPtr;
                    var result = fn(win, in area, data);
                    win.Dispose();
                    return result;
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return default;
                }
            };
        }
    }

}
