// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>A callback that fires when an SDL assertion fails.</para>
    /// </summary>
    /// <param name="data">a pointer to the <see cref="CSDL.AssertData">AssertData</see> structure corresponding to the current assertion.</param>
    /// <param name="userData">what was passed as <c>userdata</c> to <see cref="CSDL.Assert.SetHandler">SetHandler</see>.</param>
    /// <returns>
    /// <para>Returns an <see cref="CSDL.AssertState">AssertState</see> value indicating how to handle the failure.</para>
    /// </returns>
    /// <threadSafety>
    /// <para>This callback may be called from any thread that triggers an assert at any time.</para>
    /// </threadSafety>
    /// <version>
    /// <para>This datatype is available since SDL 3.2.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_AssertionHandler">SDL_AssertionHandler</seealso></SDLWiki>
    public delegate CSDL.AssertState AssertionHandler(in CSDL.AssertData data, object? userData);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate CSDL.AssertState SDL_AssertionHandlerNative(nint data, nint userData);

    internal static class AssertionHandlerWrapper {
        public static unsafe SDL_AssertionHandlerNative Create(AssertionHandler fn) {
            return (dataPtr, userDataPtr) => {
                try {
                    ref CSDL.AssertData data = ref System.Runtime.CompilerServices.Unsafe.AsRef<CSDL.AssertData>((void*)dataPtr);
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    return fn(in data, userData);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return default;
                }
            };
        }
    }

}
