// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Video {
    /// <summary>
    /// <para>Colorspace color primaries, as described by https://www.itu.int/rec/T-REC-H.273-201612-S/en</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_ColorPrimaries">SDL_ColorPrimaries</seealso></SDLWiki>
    public enum ColorPrimaries {
        Unknown = 0,
        /// <summary>
        /// <para>ITU-R BT.709-6</para>
        /// </summary>
        Bt709 = 1,
        Unspecified = 2,
        /// <summary>
        /// <para>ITU-R BT.470-6 System M</para>
        /// </summary>
        Bt470M = 4,
        /// <summary>
        /// <para>ITU-R BT.470-6 System B, G / ITU-R BT.601-7 625</para>
        /// </summary>
        Bt470Bg = 5,
        /// <summary>
        /// <para>ITU-R BT.601-7 525, SMPTE 170M</para>
        /// </summary>
        Bt601 = 6,
        /// <summary>
        /// <para>SMPTE 240M, functionally the same as SDL_COLOR_PRIMARIES_BT601</para>
        /// </summary>
        Smpte240 = 7,
        /// <summary>
        /// <para>Generic film (color filters using Illuminant C)</para>
        /// </summary>
        GenericFilm = 8,
        /// <summary>
        /// <para>ITU-R BT.2020-2 / ITU-R BT.2100-0</para>
        /// </summary>
        Bt2020 = 9,
        /// <summary>
        /// <para>SMPTE ST 428-1</para>
        /// </summary>
        Xyz = 10,
        /// <summary>
        /// <para>SMPTE RP 431-2</para>
        /// </summary>
        Smpte431 = 11,
        /// <summary>
        /// <para>SMPTE EG 432-1 / DCI P3</para>
        /// </summary>
        Smpte432 = 12,
        /// <summary>
        /// <para>EBU Tech. 3213-E</para>
        /// </summary>
        Ebu3213 = 22,
        Custom = 31,
    }
}
