// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Internal.Docs {
    public static partial class Pixels {
        /// <summary>
        /// <para>Create a palette structure with the specified number of color entries.</para>
        /// </summary>
        /// <remarks>
        /// <para>The palette entries are initialized to white.</para>
        /// </remarks>
        /// <param name="ncolors">represents the number of color entries in the color palette.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Video.Palette">Palette</see> *) Returns a new <see cref="CSDL.Video.Palette">Palette</see> structure on success or NULL on failure (e.g. if there wasn't enough memory); call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_CreatePalette">SDL_CreatePalette</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.Palette.DisposeResource">DisposeResource</see></seealso>
        /// <seealso><see cref="CSDL.Video.Palette.SetColors">SetColors</see></seealso>
        /// <seealso><see cref="CSDL.Video.Surface.SetPalette">SetPalette</see></seealso>
        public static extern void CreatePalette();

        /// <summary>
        /// <para>Free a palette created with <see cref="CSDL.Video.Palette(int)">Palette(int)</see>.</para>
        /// </summary>
        /// <param name="palette">the <see cref="CSDL.Video.Palette">Palette</see> structure to be freed.</param>
        /// <threadsafety>It is safe to call this function from any thread, as long as the palette is not modified or destroyed in another thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_DestroyPalette">SDL_DestroyPalette</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.Palette(int)">Palette(int)</see></seealso>
        public static extern void DestroyPalette();

        /// <summary>
        /// <para>Convert one of the enumerated pixel formats to a bpp value and RGBA masks.</para>
        /// </summary>
        /// <param name="format">one of the <see cref="CSDL.Video.PixelFormat">PixelFormat</see> values.</param>
        /// <param name="bpp">a bits per pixel value; usually 15, 16, or 32.</param>
        /// <param name="Rmask">a pointer filled in with the red mask for the format.</param>
        /// <param name="Gmask">a pointer filled in with the green mask for the format.</param>
        /// <param name="Bmask">a pointer filled in with the blue mask for the format.</param>
        /// <param name="Amask">a pointer filled in with the alpha mask for the format.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetMasksForPixelFormat">SDL_GetMasksForPixelFormat</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.PixelFormatExtensions.FromMasks">FromMasks</see></seealso>
        public static extern void GetMasksForPixelFormat();

        /// <summary>
        /// <para>Create an <see cref="CSDL.Video.PixelFormatDetails">PixelFormatDetails</see> structure corresponding to a pixel format.</para>
        /// </summary>
        /// <remarks>
        /// <para>Returned structure may come from a shared global cache (i.e. not newly allocated), and hence should not be modified, especially the palette. Weird errors such as <c>Blit combination not supported</c> may occur.</para>
        /// </remarks>
        /// <param name="format">one of the <see cref="CSDL.Video.PixelFormat">PixelFormat</see> values.</param>
        /// <returns>
        /// <para>(const <see cref="CSDL.Video.PixelFormatDetails">PixelFormatDetails</see> *) Returns a pointer to a <see cref="CSDL.Video.PixelFormatDetails">PixelFormatDetails</see> structure or NULL on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetPixelFormatDetails">SDL_GetPixelFormatDetails</seealso></SDLWiki>
        public static extern void GetPixelFormatDetails();

        /// <summary>
        /// <para>Convert a bpp value and RGBA masks to an enumerated pixel format.</para>
        /// </summary>
        /// <remarks>
        /// <para>This will return <see cref="CSDL.Video.PixelFormat.Unknown">Unknown</see> if the conversion wasn't possible.</para>
        /// </remarks>
        /// <param name="bpp">a bits per pixel value; usually 15, 16, or 32.</param>
        /// <param name="Rmask">the red mask for the format.</param>
        /// <param name="Gmask">the green mask for the format.</param>
        /// <param name="Bmask">the blue mask for the format.</param>
        /// <param name="Amask">the alpha mask for the format.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Video.PixelFormat">PixelFormat</see>) Returns the <see cref="CSDL.Video.PixelFormat">PixelFormat</see> value corresponding to the format masks, or <see cref="CSDL.Video.PixelFormat.Unknown">Unknown</see> if there isn't a match.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetPixelFormatForMasks">SDL_GetPixelFormatForMasks</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.PixelFormatExtensions.TryGetMasks">TryGetMasks</see></seealso>
        public static extern void GetPixelFormatForMasks();

        /// <summary>
        /// <para>Get the human readable name of a pixel format.</para>
        /// </summary>
        /// <param name="format">the pixel format to query.</param>
        /// <returns>
        /// <para>(const char *) Returns the human readable name of the specified pixel format or "<see cref="CSDL.Video.PixelFormat.Unknown">Unknown</see>" if the format isn't recognized.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetPixelFormatName">SDL_GetPixelFormatName</seealso></SDLWiki>
        public static extern void GetPixelFormatName();

        /// <summary>
        /// <para>Get RGB values from a pixel in the specified format.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function uses the entire 8-bit [0..255] range when converting color components from pixel formats with less than 8-bits per RGB component (e.g., a completely white pixel in 16-bit RGB565 format would return [0xff, 0xff, 0xff] not [0xf8, 0xfc, 0xf8]).</para>
        /// </remarks>
        /// <param name="pixelvalue">a pixel value.</param>
        /// <param name="format">a pointer to <see cref="CSDL.Video.PixelFormatDetails">PixelFormatDetails</see> describing the pixel format.</param>
        /// <param name="palette">an optional palette for indexed formats, may be NULL.</param>
        /// <param name="r">a pointer filled in with the red component, may be NULL.</param>
        /// <param name="g">a pointer filled in with the green component, may be NULL.</param>
        /// <param name="b">a pointer filled in with the blue component, may be NULL.</param>
        /// <threadsafety>It is safe to call this function from any thread, as long as the palette is not modified.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetRGB">SDL_GetRGB</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.PixelFormatExtensions.GetDetails">GetDetails</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.GetRGBA">GetRGBA</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.MapRGB">MapRGB</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.MapRGBA">MapRGBA</see></seealso>
        public static extern void GetRGB();

        /// <summary>
        /// <para>Get RGBA values from a pixel in the specified format.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function uses the entire 8-bit [0..255] range when converting color components from pixel formats with less than 8-bits per RGB component (e.g., a completely white pixel in 16-bit RGB565 format would return [0xff, 0xff, 0xff] not [0xf8, 0xfc, 0xf8]).</para>
        /// <para>If the format has no alpha component, the alpha will be returned as 0xff (100% opaque).</para>
        /// </remarks>
        /// <param name="pixelvalue">a pixel value.</param>
        /// <param name="format">a pointer to <see cref="CSDL.Video.PixelFormatDetails">PixelFormatDetails</see> describing the pixel format.</param>
        /// <param name="palette">an optional palette for indexed formats, may be NULL.</param>
        /// <param name="r">a pointer filled in with the red component, may be NULL.</param>
        /// <param name="g">a pointer filled in with the green component, may be NULL.</param>
        /// <param name="b">a pointer filled in with the blue component, may be NULL.</param>
        /// <param name="a">a pointer filled in with the alpha component, may be NULL.</param>
        /// <threadsafety>It is safe to call this function from any thread, as long as the palette is not modified.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetRGBA">SDL_GetRGBA</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.PixelFormatExtensions.GetDetails">GetDetails</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.GetRGB">GetRGB</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.MapRGB">MapRGB</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.MapRGBA">MapRGBA</see></seealso>
        public static extern void GetRGBA();

        /// <summary>
        /// <para>Map an RGB triple to an opaque pixel value for a given pixel format.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function maps the RGB color value to the specified pixel format and returns the pixel value best approximating the given RGB color value for the given pixel format.</para>
        /// <para>If the format has a palette (8-bit) the index of the closest matching color in the palette will be returned.</para>
        /// <para>If the specified pixel format has an alpha component it will be returned as all 1 bits (fully opaque).</para>
        /// <para>If the pixel format bpp (color depth) is less than 32-bpp then the unused upper bits of the return value can safely be ignored (e.g., with a 16-bpp format the return value can be assigned to a <c>Uint16</c>, and similarly a Uint8 for an 8-bpp format).</para>
        /// </remarks>
        /// <param name="format">a pointer to <see cref="CSDL.Video.PixelFormatDetails">PixelFormatDetails</see> describing the pixel format.</param>
        /// <param name="palette">an optional palette for indexed formats, may be NULL.</param>
        /// <param name="r">the red component of the pixel in the range 0-255.</param>
        /// <param name="g">the green component of the pixel in the range 0-255.</param>
        /// <param name="b">the blue component of the pixel in the range 0-255.</param>
        /// <returns>
        /// <para>(<c>Uint32</c>) Returns a pixel value.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread, as long as the palette is not modified.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MapRGB">SDL_MapRGB</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.PixelFormatExtensions.GetDetails">GetDetails</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.GetRGB">GetRGB</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.MapRGBA">MapRGBA</see></seealso>
        /// <seealso><see cref="CSDL.Video.Surface.MapRGB">MapRGB</see></seealso>
        public static extern void MapRGB();

        /// <summary>
        /// <para>Map an RGBA quadruple to a pixel value for a given pixel format.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function maps the RGBA color value to the specified pixel format and returns the pixel value best approximating the given RGBA color value for the given pixel format.</para>
        /// <para>If the specified pixel format has no alpha component the alpha value will be ignored (as it will be in formats with a palette).</para>
        /// <para>If the format has a palette (8-bit) the index of the closest matching color in the palette will be returned.</para>
        /// <para>If the pixel format bpp (color depth) is less than 32-bpp then the unused upper bits of the return value can safely be ignored (e.g., with a 16-bpp format the return value can be assigned to a <c>Uint16</c>, and similarly a Uint8 for an 8-bpp format).</para>
        /// </remarks>
        /// <param name="format">a pointer to <see cref="CSDL.Video.PixelFormatDetails">PixelFormatDetails</see> describing the pixel format.</param>
        /// <param name="palette">an optional palette for indexed formats, may be NULL.</param>
        /// <param name="r">the red component of the pixel in the range 0-255.</param>
        /// <param name="g">the green component of the pixel in the range 0-255.</param>
        /// <param name="b">the blue component of the pixel in the range 0-255.</param>
        /// <param name="a">the alpha component of the pixel in the range 0-255.</param>
        /// <returns>
        /// <para>(<c>Uint32</c>) Returns a pixel value.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread, as long as the palette is not modified.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MapRGBA">SDL_MapRGBA</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.PixelFormatExtensions.GetDetails">GetDetails</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.GetRGBA">GetRGBA</see></seealso>
        /// <seealso><see cref="CSDL.Video.PixelFormatDetails.MapRGB">MapRGB</see></seealso>
        /// <seealso><see cref="CSDL.Video.Surface.MapRGBA">MapRGBA</see></seealso>
        public static extern void MapRGBA();

        /// <summary>
        /// <para>Map an RGB triple to an opaque pixel value for a surface.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function maps the RGB color value to the specified pixel format and returns the pixel value best approximating the given RGB color value for the given pixel format.</para>
        /// <para>If the surface has a palette, the index of the closest matching color in the palette will be returned.</para>
        /// <para>If the surface pixel format has an alpha component it will be returned as all 1 bits (fully opaque).</para>
        /// <para>If the pixel format bpp (color depth) is less than 32-bpp then the unused upper bits of the return value can safely be ignored (e.g., with a 16-bpp format the return value can be assigned to a <c>Uint16</c>, and similarly a Uint8 for an 8-bpp format).</para>
        /// </remarks>
        /// <param name="surface">the surface to use for the pixel format and palette.</param>
        /// <param name="r">the red component of the pixel in the range 0-255.</param>
        /// <param name="g">the green component of the pixel in the range 0-255.</param>
        /// <param name="b">the blue component of the pixel in the range 0-255.</param>
        /// <returns>
        /// <para>(<c>Uint32</c>) Returns a pixel value.</para>
        /// </returns>
        /// <threadsafety>This function can be called on different threads with different surfaces.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MapSurfaceRGB">SDL_MapSurfaceRGB</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.Surface.MapRGBA">MapRGBA</see></seealso>
        public static extern void MapSurfaceRGB();

        /// <summary>
        /// <para>Map an RGBA quadruple to a pixel value for a surface.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function maps the RGBA color value to the specified pixel format and returns the pixel value best approximating the given RGBA color value for the given pixel format.</para>
        /// <para>If the surface pixel format has no alpha component the alpha value will be ignored (as it will be in formats with a palette).</para>
        /// <para>If the surface has a palette, the index of the closest matching color in the palette will be returned.</para>
        /// <para>If the pixel format bpp (color depth) is less than 32-bpp then the unused upper bits of the return value can safely be ignored (e.g., with a 16-bpp format the return value can be assigned to a <c>Uint16</c>, and similarly a Uint8 for an 8-bpp format).</para>
        /// </remarks>
        /// <param name="surface">the surface to use for the pixel format and palette.</param>
        /// <param name="r">the red component of the pixel in the range 0-255.</param>
        /// <param name="g">the green component of the pixel in the range 0-255.</param>
        /// <param name="b">the blue component of the pixel in the range 0-255.</param>
        /// <param name="a">the alpha component of the pixel in the range 0-255.</param>
        /// <returns>
        /// <para>(<c>Uint32</c>) Returns a pixel value.</para>
        /// </returns>
        /// <threadsafety>This function can be called on different threads with different surfaces.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_MapSurfaceRGBA">SDL_MapSurfaceRGBA</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Video.Surface.MapRGB">MapRGB</see></seealso>
        public static extern void MapSurfaceRGBA();

        /// <summary>
        /// <para>Set a range of colors in a palette.</para>
        /// </summary>
        /// <param name="palette">the <see cref="CSDL.Video.Palette">Palette</see> structure to modify.</param>
        /// <param name="colors">an array of <see cref="CSDL.Video.Color">Color</see> structures to copy into the palette.</param>
        /// <param name="firstcolor">the index of the first palette entry to modify.</param>
        /// <param name="ncolors">the number of entries to modify.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread, as long as the palette is not modified or destroyed in another thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SetPaletteColors">SDL_SetPaletteColors</seealso></SDLWiki>
        public static extern void SetPaletteColors();
    }
}
