// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Video {
    /// <summary>
    /// <para>Colorspace transfer characteristics.</para>
    /// </summary>
    /// <remarks>
    /// <para>These are as described by https://www.itu.int/rec/T-REC-H.273-201612-S/en</para>
    /// </remarks>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_TransferCharacteristics">SDL_TransferCharacteristics</seealso></SDLWiki>
    public enum TransferCharacteristics {
        Unknown = 0,
        /// <summary>
        /// <para>Rec. ITU-R BT.709-6 / ITU-R BT1361</para>
        /// </summary>
        Bt709 = 1,
        Unspecified = 2,
        /// <summary>
        /// <para>ITU-R BT.470-6 System M / ITU-R BT1700 625 PAL &amp; SECAM</para>
        /// </summary>
        Gamma22 = 4,
        /// <summary>
        /// <para>ITU-R BT.470-6 System B, G</para>
        /// </summary>
        Gamma28 = 5,
        /// <summary>
        /// <para>SMPTE ST 170M / ITU-R BT.601-7 525 or 625</para>
        /// </summary>
        Bt601 = 6,
        /// <summary>
        /// <para>SMPTE ST 240M</para>
        /// </summary>
        Smpte240 = 7,
        Linear = 8,
        Log100 = 9,
        LOG100SQRT10 = 10,
        /// <summary>
        /// <para>IEC 61966-2-4</para>
        /// </summary>
        Iec61966 = 11,
        /// <summary>
        /// <para>ITU-R BT1361 Extended Colour Gamut</para>
        /// </summary>
        Bt1361 = 12,
        /// <summary>
        /// <para>IEC 61966-2-1 (sRGB or sYCC)</para>
        /// </summary>
        SRGB = 13,
        /// <summary>
        /// <para>ITU-R BT2020 for 10-bit system</para>
        /// </summary>
        BT202010BIT = 14,
        /// <summary>
        /// <para>ITU-R BT2020 for 12-bit system</para>
        /// </summary>
        BT202012BIT = 15,
        /// <summary>
        /// <para>SMPTE ST 2084 for 10-, 12-, 14- and 16-bit systems</para>
        /// </summary>
        Pq = 16,
        /// <summary>
        /// <para>SMPTE ST 428-1</para>
        /// </summary>
        Smpte428 = 17,
        /// <summary>
        /// <para>ARIB STD-B67, known as "hybrid log-gamma" (HLG)</para>
        /// </summary>
        Hlg = 18,
        Custom = 31,
    }
}
