// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Video {
    /// <summary>
    /// <para>Callback function that will be called when the clipboard is cleared, or when new data is set.</para>
    /// </summary>
    /// <param name="userData">a pointer to the provided user data.</param>
    /// <version>
    /// <para>This function is available since SDL 3.2.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_ClipboardCleanupCallback">SDL_ClipboardCleanupCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Video.Clipboard.SetData">SetData</see></seealso>
    public delegate void ClipboardCleanupCallback(object? userData);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void SDL_ClipboardCleanupCallbackNative(nint userData);

    internal static class ClipboardCleanupCallbackWrapper {
        public static SDL_ClipboardCleanupCallbackNative Create(ClipboardCleanupCallback fn) {
            return (userDataPtr) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    fn(userData);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return;
                }
            };
        }
    }

    /// <summary>
    /// <para>Callback function that will be called when data for the specified mime-type is requested by the OS.</para>
    /// </summary>
    /// <param name="userData">a pointer to the provided user data.</param>
    /// <param name="mimeType">the requested mime-type.</param>
    /// <param name="size">a pointer filled in with the length of the returned data.</param>
    /// <returns>
    /// <para>Returns a pointer to the data for the provided mime-type. Returning NULL or setting the length to 0 will cause zero length data to be sent to the "receiver", which should be able to handle this. The returned data will not be freed, so it needs to be retained and dealt with internally.</para>
    /// </returns>
    /// <remarks>
    /// <para>The callback function is called with NULL as the mime_type when the clipboard is cleared or new data is set. The clipboard is automatically cleared in <see cref="CSDL.Init.Quit">Quit</see>.</para>
    /// </remarks>
    /// <version>
    /// <para>This function is available since SDL 3.2.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_ClipboardDataCallback">SDL_ClipboardDataCallback</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Video.Clipboard.SetData">SetData</see></seealso>
    public delegate nint ClipboardDataCallback(object? userData, string mimeType, out nint size);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate nint SDL_ClipboardDataCallbackNative(nint userData, nint mimeType, out nint size);

    internal static class ClipboardDataCallbackWrapper {
        public static SDL_ClipboardDataCallbackNative Create(ClipboardDataCallback fn) {
            return (nint userDataPtr, nint mimeTypePtr, out nint sizePtr) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    string mimeType = Marshal.PtrToStringUTF8(mimeTypePtr);
                    return fn(userData, mimeType, out sizePtr);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    sizePtr = default;
                    return default;
                }
            };
        }
    }

}
