// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Input {
    public static partial class Macros {
        /// <summary>
        /// <para>The <see cref="CSDL.Input.MouseID">MouseID</see> for mouse events simulated with touch input.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_TOUCH_MOUSEID">SDL_TOUCH_MOUSEID</seealso></SDLWiki>
        // TODO: Unsupported constant macro 'SDL_TOUCH_MOUSEID'.

    }
}
