// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Input {
    /// <summary>
    /// <para>Pen axis indices.</para>
    /// </summary>
    /// <remarks>
    /// <para>These are the valid values for the <c>axis</c> field in <see cref="CSDL.PenAxisEvent">PenAxisEvent</see>. All axes are either normalised to 0..1 or report a (positive or negative) angle in degrees, with 0.0 representing the centre. Not all pens/backends support all axes: unsupported axes are always zero.</para>
    /// <para>To convert angles for tilt and rotation into vector representation, use <c>SDL_sinf</c> on the XTILT, YTILT, or ROTATION component, for example:</para>
    /// <para><c>SDL_sinf(xtilt * SDL_PI_F / 180.0)</c>.</para>
    /// </remarks>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PenAxis">SDL_PenAxis</seealso></SDLWiki>
    public enum PenAxis {
        /// <summary>
        /// <para>Pen pressure. Unidirectional: 0 to 1.0</para>
        /// </summary>
        Pressure,
        /// <summary>
        /// <para>Pen horizontal tilt angle. Bidirectional: -90.0 to 90.0 (left-to-right).</para>
        /// </summary>
        Xtilt,
        /// <summary>
        /// <para>Pen vertical tilt angle. Bidirectional: -90.0 to 90.0 (top-to-down).</para>
        /// </summary>
        Ytilt,
        /// <summary>
        /// <para>Pen distance to drawing surface. Unidirectional: 0.0 to 1.0</para>
        /// </summary>
        Distance,
        /// <summary>
        /// <para>Pen barrel rotation. Bidirectional: -180 to 179.9 (clockwise, 0 is facing up, -180.0 is facing down).</para>
        /// </summary>
        Rotation,
        /// <summary>
        /// <para>Pen finger wheel or slider (e.g., Airbrush Pen). Unidirectional: 0 to 1.0</para>
        /// </summary>
        Slider,
        /// <summary>
        /// <para>Pressure from squeezing the pen ("barrel pressure").</para>
        /// </summary>
        TangentialPressure,
        /// <summary>
        /// <para>Total known pen axis types in this version of SDL. This number may grow in future releases!</para>
        /// </summary>
        Count,
    }
}
