// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL {
    internal static partial class SDL {




        [LibraryImport(SDLLibrary, EntryPoint = "SDL_EnterAppMainCallbacks"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial int EnterAppMainCallbacks(int argc, NativePtr<nint> argv, SDL_AppInit_funcNative appinit, SDL_AppIterate_funcNative appiter, SDL_AppEvent_funcNative appevent, SDL_AppQuit_funcNative appquit);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GDKSuspendComplete"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void GDKSuspendComplete();


        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RegisterApp"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RegisterApp([MarshalAs(UnmanagedType.LPUTF8Str)] string? name, uint style, IntPtr hInst);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RegisterApp"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool RegisterApp(NativePtr<byte> name, uint style, IntPtr hInst);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_RunApp"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial int RunApp(int argc, NativePtr<nint> argv, SDL_main_funcNative mainFunction, IntPtr reserved);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetMainReady"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void SetMainReady();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_UnregisterApp"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void UnregisterApp();

    }
}
