// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Audio {
    /// <summary>
    /// <para>Format specifier for audio data.</para>
    /// </summary>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_AudioSpec">SDL_AudioSpec</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Audio.AudioFormat">AudioFormat</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct AudioSpec {
        /// <summary>
        /// <para>Audio data format</para>
        /// </summary>
        public CSDL.Audio.AudioFormat Format;

        /// <summary>
        /// <para>Number of channels: 1 mono, 2 stereo, etc</para>
        /// </summary>
        public int Channels;

        /// <summary>
        /// <para>sample rate: sample frames per second</para>
        /// </summary>
        public int Freq;
    }
}
