// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Input {
    /// <summary>
    /// <para>Information about a connected HID device</para>
    /// </summary>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_hid_device_info">SDL_hid_device_info</seealso></SDLWiki>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct hid_device_info {
        /// <summary>
        /// <para>Platform-specific device path</para>
        /// </summary>
        public nint Path;

        /// <summary>
        /// <para>Device Vendor ID</para>
        /// </summary>
        public ushort VendorID;

        /// <summary>
        /// <para>Device Product ID</para>
        /// </summary>
        public ushort ProductID;

        /// <summary>
        /// <para>Serial Number</para>
        /// </summary>
        public nint SerialNumber;

        /// <summary>
        /// <para>Device Release Number in binary-coded decimal, also known as Device Version Number</para>
        /// </summary>
        public ushort ReleaseNumber;

        /// <summary>
        /// <para>Manufacturer String</para>
        /// </summary>
        public nint ManufacturerString;

        /// <summary>
        /// <para>Product string</para>
        /// </summary>
        public nint ProductString;

        /// <summary>
        /// <para>Usage Page for this Device/Interface (Windows/Mac/hidraw only)</para>
        /// </summary>
        public ushort UsagePage;

        /// <summary>
        /// <para>Usage for this Device/Interface (Windows/Mac/hidraw only)</para>
        /// </summary>
        public ushort Usage;

        /// <summary>
        /// <para>The USB interface which this logical device represents. Valid only if the device is a USB HID device. Set to -1 in all other cases.</para>
        /// </summary>
        public int InterfaceNumber;

        /// <summary>
        /// <para>Additional information about the USB interface. Valid on libusb and Android implementations.</para>
        /// </summary>
        public int InterfaceClass;

        public int InterfaceSubclass;

        public int InterfaceProtocol;

        /// <summary>
        /// <para>Underlying bus type</para>
        /// </summary>
        public CSDL.Input.HidBusType BusType;

        public NativePtr<CSDL.Input.hid_device_info> Next;
    }
}
