// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.GPU {
    /// <summary>
    /// <para>Specifies a comparison operator for depth, stencil and sampler operations.</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUCompareOp">SDL_GPUCompareOp</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUGraphicsPipeline(GPUDevice,in GPUGraphicsPipelineCreateInfo)">GPUGraphicsPipeline(GPUDevice,in GPUGraphicsPipelineCreateInfo)</see></seealso>
    public enum GPUCompareOp {
        Invalid,
        /// <summary>
        /// <para>The comparison always evaluates false.</para>
        /// </summary>
        Never,
        /// <summary>
        /// <para>The comparison evaluates reference &lt; test.</para>
        /// </summary>
        Less,
        /// <summary>
        /// <para>The comparison evaluates reference == test.</para>
        /// </summary>
        Equal,
        /// <summary>
        /// <para>The comparison evaluates reference &lt;= test.</para>
        /// </summary>
        LessOrEqual,
        /// <summary>
        /// <para>The comparison evaluates reference > test.</para>
        /// </summary>
        Greater,
        /// <summary>
        /// <para>The comparison evaluates reference != test.</para>
        /// </summary>
        NotEqual,
        /// <summary>
        /// <para>The comparison evaluates reference >= test.</para>
        /// </summary>
        GreaterOrEqual,
        /// <summary>
        /// <para>The comparison always evaluates true.</para>
        /// </summary>
        Always,
    }
}
