// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>Specifies which color components are written in a graphics pipeline.</para>
    /// </summary>
    /// <since>This datatype is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUColorComponentFlags">SDL_GPUColorComponentFlags</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUGraphicsPipeline(GPUDevice,in GPUGraphicsPipelineCreateInfo)">GPUGraphicsPipeline(GPUDevice,in GPUGraphicsPipelineCreateInfo)</see></seealso>
    [System.Flags]
    public enum GPUColorComponentFlags : byte {
        /// <summary>
        /// <para>the red component</para>
        /// </summary>
        R = (1 << 0),
        /// <summary>
        /// <para>the green component</para>
        /// </summary>
        G = (1 << 1),
        /// <summary>
        /// <para>the blue component</para>
        /// </summary>
        B = (1 << 2),
        /// <summary>
        /// <para>the alpha component</para>
        /// </summary>
        A = (1 << 3),
    }
}
