// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>A structure specifying the descriptions of render targets used in a graphics pipeline.</para>
    /// </summary>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUGraphicsPipelineTargetInfo">SDL_GPUGraphicsPipelineTargetInfo</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUGraphicsPipelineCreateInfo">GPUGraphicsPipelineCreateInfo</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUColorTargetDescription">GPUColorTargetDescription</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUTextureFormat">GPUTextureFormat</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct GPUGraphicsPipelineTargetInfo {
        /// <summary>
        /// <para>A pointer to an array of color target descriptions.</para>
        /// </summary>
        public nint ColorTargetDescriptions;

        /// <summary>
        /// <para>The number of color target descriptions in the above array.</para>
        /// </summary>
        public uint NumColorTargets;

        /// <summary>
        /// <para>The pixel format of the depth-stencil target. Ignored if has_depth_stencil_target is false.</para>
        /// </summary>
        public CSDL.GPU.GPUTextureFormat DepthStencilFormat;

        private CBool _hasDepthStencilTarget;

        /// <summary>
        /// <para>true specifies that the pipeline uses a depth-stencil target.</para>
        /// </summary>
        public bool HasDepthStencilTarget { readonly get => _hasDepthStencilTarget; set => _hasDepthStencilTarget = value; }

        private byte _padding1;

        private byte _padding2;

        private byte _padding3;
    }
}
