// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>A structure specifying the parameters of an indirect draw command.</para>
    /// </summary>
    /// <remarks>
    /// <para>Note that the <see cref="FirstVertex"/> and <see cref="FirstInstance"/> parameters are NOT compatible with built-in vertex/instance ID variables in shaders (for example, SV_VertexID); GPU APIs and shader languages do not define these built-in variables consistently, so if your shader depends on them, the only way to keep behavior consistent and portable is to always pass 0 for the correlating parameter in the draw calls.</para>
    /// </remarks>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUIndirectDrawCommand">SDL_GPUIndirectDrawCommand</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPURenderPass.DrawIndirect">DrawIndirect</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct GPUIndirectDrawCommand {
        /// <summary>
        /// <para>The number of vertices to draw.</para>
        /// </summary>
        public uint NumVertices;

        /// <summary>
        /// <para>The number of instances to draw.</para>
        /// </summary>
        public uint NumInstances;

        /// <summary>
        /// <para>The index of the first vertex to draw.</para>
        /// </summary>
        public uint FirstVertex;

        /// <summary>
        /// <para>The ID of the first instance to draw.</para>
        /// </summary>
        public uint FirstInstance;
    }
}
