// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.GPU {
    /// <summary>
    /// <para>Specifies how the contents of a texture attached to a render pass are treated at the beginning of the render pass.</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPULoadOp">SDL_GPULoadOp</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUCommandBuffer.BeginRenderPass">BeginRenderPass</see></seealso>
    public enum GPULoadOp {
        /// <summary>
        /// <para>The previous contents of the texture will be preserved.</para>
        /// </summary>
        Load,
        /// <summary>
        /// <para>The contents of the texture will be cleared to a color.</para>
        /// </summary>
        Clear,
        /// <summary>
        /// <para>The previous contents of the texture need not be preserved. The contents will be undefined.</para>
        /// </summary>
        DontCare,
    }
}
