// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>A structure specifying the parameters of the graphics pipeline multisample state.</para>
    /// </summary>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUMultisampleState">SDL_GPUMultisampleState</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUGraphicsPipelineCreateInfo">GPUGraphicsPipelineCreateInfo</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct GPUMultisampleState {
        /// <summary>
        /// <para>The number of samples to be used in rasterization.</para>
        /// </summary>
        public CSDL.GPU.GPUSampleCount SampleCount;

        /// <summary>
        /// <para>Reserved for future use. Must be set to 0.</para>
        /// </summary>
        public uint SampleMask;

        private CBool _enableMask;

        /// <summary>
        /// <para>Reserved for future use. Must be set to false.</para>
        /// </summary>
        public bool EnableMask { readonly get => _enableMask; set => _enableMask = value; }

        private CBool _enableAlphaToCoverage;

        /// <summary>
        /// <para>true enables the alpha-to-coverage feature.</para>
        /// </summary>
        public bool EnableAlphaToCoverage { readonly get => _enableAlphaToCoverage; set => _enableAlphaToCoverage = value; }

        private byte _padding2;

        private byte _padding3;
    }
}
