// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.GPU {
    /// <summary>
    /// <para>Specifies how the contents of a texture attached to a render pass are treated at the end of the render pass.</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUStoreOp">SDL_GPUStoreOp</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUCommandBuffer.BeginRenderPass">BeginRenderPass</see></seealso>
    public enum GPUStoreOp {
        /// <summary>
        /// <para>The contents generated during the render pass will be written to memory.</para>
        /// </summary>
        Store,
        /// <summary>
        /// <para>The contents generated during the render pass are not needed and may be discarded. The contents will be undefined.</para>
        /// </summary>
        DontCare,
        /// <summary>
        /// <para>The multisample contents generated during the render pass will be resolved to a non-multisample texture. The contents in the multisample texture may then be discarded and will be undefined.</para>
        /// </summary>
        Resolve,
        /// <summary>
        /// <para>The multisample contents generated during the render pass will be resolved to a non-multisample texture. The contents in the multisample texture will be written to memory.</para>
        /// </summary>
        ResolveAndStore,
    }
}
