// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.GPU {
    /// <summary>
    /// <para>Specifies behavior of texture sampling when the coordinates exceed the 0-1 range.</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUSamplerAddressMode">SDL_GPUSamplerAddressMode</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUSampler(GPUDevice,GPUSamplerCreateInfo)">GPUSampler(GPUDevice,GPUSamplerCreateInfo)</see></seealso>
    public enum GPUSamplerAddressMode {
        /// <summary>
        /// <para>Specifies that the coordinates will wrap around.</para>
        /// </summary>
        Repeat,
        /// <summary>
        /// <para>Specifies that the coordinates will wrap around mirrored.</para>
        /// </summary>
        MirroredRepeat,
        /// <summary>
        /// <para>Specifies that the coordinates will clamp to the 0-1 range.</para>
        /// </summary>
        ClampToEdge,
    }
}
