// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.GPU {
    /// <summary>
    /// <para>Specifies which stage a shader program corresponds to.</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUShaderStage">SDL_GPUShaderStage</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUShader(GPUDevice,GPUShaderCreateInfo)">GPUShader(GPUDevice,GPUShaderCreateInfo)</see></seealso>
    public enum GPUShaderStage {
        Vertex,
        Fragment,
    }
}
