// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>A structure specifying the parameters of a sampler.</para>
    /// </summary>
    /// <remarks>
    /// <para>Note that mip_lod_bias is a no-op for the Metal driver. For Metal, LOD bias must be applied via shader instead.</para>
    /// </remarks>
    /// <since>This function is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUSamplerCreateInfo">SDL_GPUSamplerCreateInfo</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUSampler(GPUDevice,GPUSamplerCreateInfo)">GPUSampler(GPUDevice,GPUSamplerCreateInfo)</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUFilter">GPUFilter</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUSamplerMipmapMode">GPUSamplerMipmapMode</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUSamplerAddressMode">GPUSamplerAddressMode</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUCompareOp">GPUCompareOp</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct GPUSamplerCreateInfo {
        /// <summary>
        /// <para>The minification filter to apply to lookups.</para>
        /// </summary>
        public CSDL.GPU.GPUFilter MinFilter;

        /// <summary>
        /// <para>The magnification filter to apply to lookups.</para>
        /// </summary>
        public CSDL.GPU.GPUFilter MagFilter;

        /// <summary>
        /// <para>The mipmap filter to apply to lookups.</para>
        /// </summary>
        public CSDL.GPU.GPUSamplerMipmapMode MipmapMode;

        /// <summary>
        /// <para>The addressing mode for U coordinates outside [0, 1).</para>
        /// </summary>
        public CSDL.GPU.GPUSamplerAddressMode AddressModeU;

        /// <summary>
        /// <para>The addressing mode for V coordinates outside [0, 1).</para>
        /// </summary>
        public CSDL.GPU.GPUSamplerAddressMode AddressModeV;

        /// <summary>
        /// <para>The addressing mode for W coordinates outside [0, 1).</para>
        /// </summary>
        public CSDL.GPU.GPUSamplerAddressMode AddressModeW;

        /// <summary>
        /// <para>The bias to be added to mipmap LOD calculation.</para>
        /// </summary>
        public float MipLodBias;

        /// <summary>
        /// <para>The anisotropy value clamp used by the sampler. If enable_anisotropy is false, this is ignored.</para>
        /// </summary>
        public float MaxAnisotropy;

        /// <summary>
        /// <para>The comparison operator to apply to fetched data before filtering.</para>
        /// </summary>
        public CSDL.GPU.GPUCompareOp CompareOp;

        /// <summary>
        /// <para>Clamps the minimum of the computed LOD value.</para>
        /// </summary>
        public float MinLod;

        /// <summary>
        /// <para>Clamps the maximum of the computed LOD value.</para>
        /// </summary>
        public float MaxLod;

        private CBool _enableAnisotropy;

        /// <summary>
        /// <para>true to enable anisotropic filtering.</para>
        /// </summary>
        public bool EnableAnisotropy { readonly get => _enableAnisotropy; set => _enableAnisotropy = value; }

        private CBool _enableCompare;

        /// <summary>
        /// <para>true to enable comparison against a reference value during lookups.</para>
        /// </summary>
        public bool EnableCompare { readonly get => _enableCompare; set => _enableCompare = value; }

        private byte _padding1;

        private byte _padding2;

        /// <summary>
        /// <para>A properties ID for extensions. Should be 0 if no extensions are needed.</para>
        /// </summary>
        public CSDL.PropertiesID Props;
    }
}
