// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>A structure specifying a region of a texture.</para>
    /// </summary>
    /// <remarks>
    /// <para>Used when transferring data to or from a texture.</para>
    /// </remarks>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUTextureRegion">SDL_GPUTextureRegion</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPURenderer.UploadToTexture">UploadToTexture</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPURenderer.DownloadFromTexture">DownloadFromTexture</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUTexture(GPUDevice,GPUTextureCreateInfo)">GPUTexture(GPUDevice,GPUTextureCreateInfo)</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct GPUTextureRegion {
        /// <summary>
        /// <para>The texture used in the copy operation.</para>
        /// </summary>
        public nint Texture;

        /// <summary>
        /// <para>The mip level index to transfer.</para>
        /// </summary>
        public uint MipLevel;

        /// <summary>
        /// <para>The layer index to transfer.</para>
        /// </summary>
        public uint Layer;

        /// <summary>
        /// <para>The left offset of the region.</para>
        /// </summary>
        public uint X;

        /// <summary>
        /// <para>The top offset of the region.</para>
        /// </summary>
        public uint Y;

        /// <summary>
        /// <para>The front offset of the region.</para>
        /// </summary>
        public uint Z;

        /// <summary>
        /// <para>The width of the region.</para>
        /// </summary>
        public uint W;

        /// <summary>
        /// <para>The height of the region.</para>
        /// </summary>
        public uint H;

        /// <summary>
        /// <para>The depth of the region.</para>
        /// </summary>
        public uint D;
    }
}
