// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>A structure specifying parameters related to transferring data to or from a texture.</para>
    /// </summary>
    /// <remarks>
    /// <para>If either of <see cref="PixelsPerRow"/> or <see cref="RowsPerLayer"/> is zero, then width and height of passed <see cref="CSDL.GPU.GPUTextureRegion">GPUTextureRegion</see> to <see cref="CSDL.GPU.GPURenderer.UploadToTexture">UploadToTexture</see> or <see cref="CSDL.GPU.GPURenderer.DownloadFromTexture">DownloadFromTexture</see> are used as default values respectively and data is considered to be tightly packed.</para>
    /// <para>**WARNING**: On some older/integrated hardware, Direct3D 12 requires texture data row pitch to be 256 byte aligned, and offsets to be aligned to 512 bytes. If they are not, SDL will make a temporary copy of the data that is properly aligned, but this adds overhead to the transfer process. Apps can avoid this by aligning their data appropriately, or using a different GPU backend than Direct3D 12.</para>
    /// </remarks>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUTextureTransferInfo">SDL_GPUTextureTransferInfo</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPURenderer.UploadToTexture">UploadToTexture</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPURenderer.DownloadFromTexture">DownloadFromTexture</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct GPUTextureTransferInfo {
        /// <summary>
        /// <para>The transfer buffer used in the transfer operation.</para>
        /// </summary>
        public nint TransferBuffer;

        /// <summary>
        /// <para>The starting byte of the image data in the transfer buffer.</para>
        /// </summary>
        public uint Offset;

        /// <summary>
        /// <para>The number of pixels from one row to the next.</para>
        /// </summary>
        public uint PixelsPerRow;

        /// <summary>
        /// <para>The number of rows from one layer/depth-slice to the next.</para>
        /// </summary>
        public uint RowsPerLayer;
    }
}
