// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>A structure specifying the parameters of a transfer buffer.</para>
    /// </summary>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUTransferBufferCreateInfo">SDL_GPUTransferBufferCreateInfo</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUTransferBufferUsage">GPUTransferBufferUsage</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUTransferBuffer(GPUDevice,GPUTransferBufferCreateInfo)">GPUTransferBuffer(GPUDevice,GPUTransferBufferCreateInfo)</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct GPUTransferBufferCreateInfo {
        /// <summary>
        /// <para>How the transfer buffer is intended to be used by the client.</para>
        /// </summary>
        public CSDL.GPU.GPUTransferBufferUsage Usage;

        /// <summary>
        /// <para>The size in bytes of the transfer buffer.</para>
        /// </summary>
        public uint Size;

        /// <summary>
        /// <para>A properties ID for extensions. Should be 0 if no extensions are needed.</para>
        /// </summary>
        public CSDL.PropertiesID Props;
    }
}
