// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>A structure specifying a vertex attribute.</para>
    /// </summary>
    /// <remarks>
    /// <para>All vertex attribute locations provided to an <see cref="CSDL.GPU.GPUVertexInputState">GPUVertexInputState</see> must be unique.</para>
    /// </remarks>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUVertexAttribute">SDL_GPUVertexAttribute</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUVertexBufferDescription">GPUVertexBufferDescription</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUVertexInputState">GPUVertexInputState</see></seealso>
    /// <seealso><see cref="CSDL.GPU.GPUVertexElementFormat">GPUVertexElementFormat</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct GPUVertexAttribute {
        /// <summary>
        /// <para>The shader input location index.</para>
        /// </summary>
        public uint Location;

        /// <summary>
        /// <para>The binding slot of the associated vertex buffer.</para>
        /// </summary>
        public uint BufferSlot;

        /// <summary>
        /// <para>The size and type of the attribute data.</para>
        /// </summary>
        public CSDL.GPU.GPUVertexElementFormat Format;

        /// <summary>
        /// <para>The byte offset of this attribute relative to the start of the vertex element.</para>
        /// </summary>
        public uint Offset;
    }
}
