// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.GPU {
    /// <summary>
    /// <para>A structure specifying a viewport.</para>
    /// </summary>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUViewport">SDL_GPUViewport</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPURenderPass.SetViewport">SetViewport</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct GPUViewport {
        /// <summary>
        /// <para>The left offset of the viewport.</para>
        /// </summary>
        public float X;

        /// <summary>
        /// <para>The top offset of the viewport.</para>
        /// </summary>
        public float Y;

        /// <summary>
        /// <para>The width of the viewport.</para>
        /// </summary>
        public float W;

        /// <summary>
        /// <para>The height of the viewport.</para>
        /// </summary>
        public float H;

        /// <summary>
        /// <para>The minimum depth of the viewport.</para>
        /// </summary>
        public float MinDepth;

        /// <summary>
        /// <para>The maximum depth of the viewport.</para>
        /// </summary>
        public float MaxDepth;
    }
}
