// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.GPU {
    /// <summary>
    /// <para>Specifies the format of a vertex attribute.</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GPUVertexElementFormat">SDL_GPUVertexElementFormat</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.GPU.GPUGraphicsPipeline(GPUDevice,in GPUGraphicsPipelineCreateInfo)">GPUGraphicsPipeline(GPUDevice,in GPUGraphicsPipelineCreateInfo)</see></seealso>
    public enum GPUVertexElementFormat {
        Invalid,
        Int,
        Int2,
        Int3,
        Int4,
        Uint,
        Uint2,
        Uint3,
        Uint4,
        Float,
        Float2,
        Float3,
        Float4,
        Byte2,
        Byte4,
        Ubyte2,
        Ubyte4,
        BYTE2Norm,
        BYTE4Norm,
        UBYTE2Norm,
        UBYTE4Norm,
        Short2,
        Short4,
        Ushort2,
        Ushort4,
        SHORT2Norm,
        SHORT4Norm,
        USHORT2Norm,
        USHORT4Norm,
        Half2,
        Half4,
    }
}
