// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Input {
    /// <summary>
    /// <para>Standard gamepad types.</para>
    /// </summary>
    /// <remarks>
    /// <para>This type does not necessarily map to first-party controllers from Microsoft/Sony/Nintendo; in many cases, third-party controllers can report as these, either because they were designed for a specific console, or they simply most closely match that console's controllers (does it have A/B/X/Y buttons or X/O/Square/Triangle? Does it have a touchpad? etc).</para>
    /// </remarks>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GamepadType">SDL_GamepadType</seealso></SDLWiki>
    public enum GamepadType {
        Unknown = 0,
        Standard,
        Xbox360,
        Xboxone,
        Ps3,
        Ps4,
        Ps5,
        NintendoSwitchPro,
        NintendoSwitchJoyconLeft,
        NintendoSwitchJoyconRight,
        NintendoSwitchJoyconPair,
        Gamecube,
        Steam,
        Count,
    }
}
