// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Input {
    /// <summary>
    /// <para>The list of capsense types on a gamepad</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.6.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GamepadCapSenseType">SDL_GamepadCapSenseType</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Input.GamepadDevice.HasCapSense">HasCapSense</see></seealso>
    /// <seealso><see cref="CSDL.Input.GamepadDevice.GetCapSense">GetCapSense</see></seealso>
    public enum GamepadCapSenseType {
        Invalid = -1,
        /// <summary>
        /// <para>Activated by touching the top of the left thumbstick</para>
        /// </summary>
        LeftStick,
        /// <summary>
        /// <para>Activated by touching the top of the right thumbstick</para>
        /// </summary>
        RightStick,
        /// <summary>
        /// <para>Activated by gripping the left handle of the controller</para>
        /// </summary>
        LeftGrip,
        /// <summary>
        /// <para>Activated by gripping the right handle of the controller</para>
        /// </summary>
        RightGrip,
        Count,
    }
}
