// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Internal.Docs {
    internal static partial class Gamepad {
        /// <summary>
        /// <para>Add support for gamepads that SDL is unaware of or change the binding of an existing gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>The mapping string has the format "GUID,name,mapping", where GUID is the string value from <see cref="CSDL.GUIDData.ToString">ToString</see>, name is the human readable string for the device and mappings are gamepad mappings to joystick ones. Under Windows there is a reserved GUID of "xinput" that covers all XInput devices. The mapping format for joystick is:</para>
        /// <list type="bullet">
        /// <item><description><c>bX</c>: a joystick button, index X</description></item>
        /// <item><description><c>hX.Y</c>: hat X with value Y</description></item>
        /// <item><description><c>aX</c>: axis X of the joystick</description></item>
        /// </list>
        /// <para>Buttons can be used as a gamepad axes and vice versa.</para>
        /// <para>If a device with this GUID is already plugged in, SDL will generate an <see cref="CSDL.EventType.GamepadAdded">GamepadAdded</see> event.</para>
        /// <para>This string shows an example of a valid mapping for a gamepad:</para>
        /// <code language="c">
        /// "341a3608000000000000504944564944,Afterglow PS3 Controller,a:b1,b:b2,y:b3,x:b0,start:b9,guide:b12,back:b8,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7"
        /// </code>
        /// </remarks>
        /// <param name="mapping">the mapping string.</param>
        /// <returns>
        /// <para>(int) Returns 1 if a new mapping is added, 0 if an existing mapping is updated, -1 on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_AddGamepadMapping">SDL_AddGamepadMapping</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.AddMappingsFromFile">AddMappingsFromFile</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.AddMappingsFromIO">AddMappingsFromIO</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Mapping">Mapping</see></seealso>
        /// <seealso><c>SDL_GetGamepadMappingForGUID</c></seealso>
        /// <seealso><see cref="CSDL.Hints.Gamecontrollerconfig">Gamecontrollerconfig</see></seealso>
        /// <seealso><see cref="CSDL.Hints.GamecontrollerconfigFile">GamecontrollerconfigFile</see></seealso>
        /// <seealso><see cref="CSDL.EventType.GamepadAdded">GamepadAdded</see></seealso>
        public static extern void AddGamepadMapping();

        /// <summary>
        /// <para>Load a set of gamepad mappings from a file.</para>
        /// </summary>
        /// <remarks>
        /// <para>You can call this function several times, if needed, to load different database files.</para>
        /// <para>If a new mapping is loaded for an already known gamepad GUID, the later version will overwrite the one currently loaded.</para>
        /// <para>Any new mappings for already plugged in controllers will generate <see cref="CSDL.EventType.GamepadAdded">GamepadAdded</see> events.</para>
        /// <para>Mappings not belonging to the current platform or with no platform field specified will be ignored (i.e. mappings for Linux will be ignored in Windows, etc).</para>
        /// </remarks>
        /// <param name="file">the mappings file to load.</param>
        /// <returns>
        /// <para>(int) Returns the number of mappings added or -1 on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_AddGamepadMappingsFromFile">SDL_AddGamepadMappingsFromFile</seealso></SDLWiki>
        /// <seealso><c>SDL_AddGamepadMapping</c></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.AddMappingsFromIO">AddMappingsFromIO</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Mapping">Mapping</see></seealso>
        /// <seealso><c>SDL_GetGamepadMappingForGUID</c></seealso>
        /// <seealso><see cref="CSDL.Hints.Gamecontrollerconfig">Gamecontrollerconfig</see></seealso>
        /// <seealso><see cref="CSDL.Hints.GamecontrollerconfigFile">GamecontrollerconfigFile</see></seealso>
        /// <seealso><see cref="CSDL.EventType.GamepadAdded">GamepadAdded</see></seealso>
        public static extern void AddGamepadMappingsFromFile();

        /// <summary>
        /// <para>Load a set of gamepad mappings from an <see cref="CSDL.File.IOStream">IOStream</see>.</para>
        /// </summary>
        /// <remarks>
        /// <para>You can call this function several times, if needed, to load different database files.</para>
        /// <para>If a new mapping is loaded for an already known gamepad GUID, the later version will overwrite the one currently loaded.</para>
        /// <para>Any new mappings for already plugged in controllers will generate <see cref="CSDL.EventType.GamepadAdded">GamepadAdded</see> events.</para>
        /// <para>Mappings not belonging to the current platform or with no platform field specified will be ignored (i.e. mappings for Linux will be ignored in Windows, etc).</para>
        /// <para>This function will load the text database entirely in memory before processing it, so take this into consideration if you are in a memory constrained environment.</para>
        /// </remarks>
        /// <param name="src">the data stream for the mappings to be added.</param>
        /// <param name="closeio">if true, calls <see cref="CSDL.File.IOStream.DisposeResource">DisposeResource</see> on <c>src</c> before returning, even in the case of an error.</param>
        /// <returns>
        /// <para>(int) Returns the number of mappings added or -1 on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_AddGamepadMappingsFromIO">SDL_AddGamepadMappingsFromIO</seealso></SDLWiki>
        /// <seealso><c>SDL_AddGamepadMapping</c></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.AddMappingsFromFile">AddMappingsFromFile</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Mapping">Mapping</see></seealso>
        /// <seealso><c>SDL_GetGamepadMappingForGUID</c></seealso>
        /// <seealso><see cref="CSDL.Hints.Gamecontrollerconfig">Gamecontrollerconfig</see></seealso>
        /// <seealso><see cref="CSDL.Hints.GamecontrollerconfigFile">GamecontrollerconfigFile</see></seealso>
        /// <seealso><see cref="CSDL.EventType.GamepadAdded">GamepadAdded</see></seealso>
        public static extern void AddGamepadMappingsFromIO();

        /// <summary>
        /// <para>Close a gamepad previously opened with <see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see>.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad identifier previously returned by <see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see>.</param>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_CloseGamepad">SDL_CloseGamepad</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see></seealso>
        public static extern void CloseGamepad();

        /// <summary>
        /// <para>Check if a gamepad has been opened and is currently connected.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad identifier previously returned by <see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see>.</param>
        /// <returns>
        /// <para>(bool) Returns true if the gamepad has been opened and is currently connected, or false if not.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GamepadConnected">SDL_GamepadConnected</seealso></SDLWiki>
        public static extern void GamepadConnected();

        /// <summary>
        /// <para>Query the state of gamepad event processing.</para>
        /// </summary>
        /// <remarks>
        /// <para>If gamepad events are disabled, you must call <see cref="CSDL.Input.Gamepads.Update">Update</see> yourself and check the state of the gamepad when you want gamepad information.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true if gamepad events are being processed, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GamepadEventsEnabled">SDL_GamepadEventsEnabled</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.EventsEnabled">EventsEnabled</see></seealso>
        public static extern void GamepadEventsEnabled();

        /// <summary>
        /// <para>Query whether a gamepad has a given axis.</para>
        /// </summary>
        /// <remarks>
        /// <para>This merely reports whether the gamepad's mapping defined this axis, as that is all the information SDL has about the physical device.</para>
        /// </remarks>
        /// <param name="gamepad">a gamepad.</param>
        /// <param name="axis">an axis enum value (an <see cref="CSDL.Input.GamepadAxis">GamepadAxis</see> value).</param>
        /// <returns>
        /// <para>(bool) Returns true if the gamepad has this axis, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GamepadHasAxis">SDL_GamepadHasAxis</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.HasButton">HasButton</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetAxis">GetAxis</see></seealso>
        public static extern void GamepadHasAxis();

        /// <summary>
        /// <para>Query whether a gamepad has a given button.</para>
        /// </summary>
        /// <remarks>
        /// <para>This merely reports whether the gamepad's mapping defined this button, as that is all the information SDL has about the physical device.</para>
        /// </remarks>
        /// <param name="gamepad">a gamepad.</param>
        /// <param name="button">a button enum value (an <see cref="CSDL.Input.GamepadButton">GamepadButton</see> value).</param>
        /// <returns>
        /// <para>(bool) Returns true if the gamepad has this button, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GamepadHasButton">SDL_GamepadHasButton</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.HasAxis">HasAxis</see></seealso>
        public static extern void GamepadHasButton();

        /// <summary>
        /// <para>Return whether a gamepad has a particular capsense.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad to query.</param>
        /// <param name="type">the type of capsense to query.</param>
        /// <returns>
        /// <para>(bool) Returns true if the capsense exists, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.6.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GamepadHasCapSense">SDL_GamepadHasCapSense</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetCapSense">GetCapSense</see></seealso>
        public static extern void GamepadHasCapSense();

        /// <summary>
        /// <para>Return whether a gamepad has a particular sensor.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad to query.</param>
        /// <param name="type">the type of sensor to query.</param>
        /// <returns>
        /// <para>(bool) Returns true if the sensor exists, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GamepadHasSensor">SDL_GamepadHasSensor</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetSensorData">GetSensorData</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetSensorDataRate">GetSensorDataRate</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.SetSensorEnabled">SetSensorEnabled</see></seealso>
        public static extern void GamepadHasSensor();

        /// <summary>
        /// <para>Query whether sensor data reporting is enabled for a gamepad.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad to query.</param>
        /// <param name="type">the type of sensor to query.</param>
        /// <returns>
        /// <para>(bool) Returns true if the sensor is enabled, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GamepadSensorEnabled">SDL_GamepadSensorEnabled</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.SetSensorEnabled">SetSensorEnabled</see></seealso>
        public static extern void GamepadSensorEnabled();

        /// <summary>
        /// <para>Return the sfSymbolsName for a given axis on a gamepad on Apple platforms.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad to query.</param>
        /// <param name="axis">an axis on the gamepad.</param>
        /// <returns>
        /// <para>(const char *) Returns the sfSymbolsName or NULL if the name can't be found.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadAppleSFSymbolsNameForAxis">SDL_GetGamepadAppleSFSymbolsNameForAxis</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetAppleSFSymbolsName">GetAppleSFSymbolsName</see></seealso>
        public static extern void GetGamepadAppleSFSymbolsNameForAxis();

        /// <summary>
        /// <para>Return the sfSymbolsName for a given button on a gamepad on Apple platforms.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad to query.</param>
        /// <param name="button">a button on the gamepad.</param>
        /// <returns>
        /// <para>(const char *) Returns the sfSymbolsName or NULL if the name can't be found.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadAppleSFSymbolsNameForButton">SDL_GetGamepadAppleSFSymbolsNameForButton</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetAppleSFSymbolsName">GetAppleSFSymbolsName</see></seealso>
        public static extern void GetGamepadAppleSFSymbolsNameForButton();

        /// <summary>
        /// <para>Get the current state of an axis control on a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>The axis indices start at index 0.</para>
        /// <para>For thumbsticks, the state is a value ranging from -32768 (up/left) to 32767 (down/right).</para>
        /// <para>Triggers range from 0 when released to 32767 when fully pressed, and never return a negative value. Note that this differs from the value reported by the lower-level <see cref="CSDL.Input.JoystickDevice.GetAxis">GetAxis</see>, which normally uses the full range.</para>
        /// <para>Note that for invalid gamepads or axes, this will return 0. Zero is also a valid value in normal operation; usually it means a centered axis.</para>
        /// </remarks>
        /// <param name="gamepad">a gamepad.</param>
        /// <param name="axis">an axis index (one of the <see cref="CSDL.Input.GamepadAxis">GamepadAxis</see> values).</param>
        /// <returns>
        /// <para>(<c>Sint16</c>) Returns axis state.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadAxis">SDL_GetGamepadAxis</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.HasAxis">HasAxis</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetButton">GetButton</see></seealso>
        public static extern void GetGamepadAxis();

        /// <summary>
        /// <para>Convert a string into <see cref="CSDL.Input.GamepadAxis">GamepadAxis</see> enum.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function is called internally to translate <c>SDL_Gamepad</c> mapping strings for the underlying joystick device into the consistent <c>SDL_Gamepad</c> mapping. You do not normally need to call this function unless you are parsing <c>SDL_Gamepad</c> mappings in your own code.</para>
        /// <para>Note specially that "righttrigger" and "lefttrigger" map to <see cref="CSDL.Input.GamepadAxis.RightTrigger">RightTrigger</see> and <see cref="CSDL.Input.GamepadAxis.LeftTrigger">LeftTrigger</see>, respectively.</para>
        /// </remarks>
        /// <param name="str">string representing a <c>SDL_Gamepad</c> axis.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadAxis">GamepadAxis</see>) Returns the <see cref="CSDL.Input.GamepadAxis">GamepadAxis</see> enum corresponding to the input string, or <see cref="CSDL.Input.GamepadAxis.Invalid">Invalid</see> if no match was found.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadAxisFromString">SDL_GetGamepadAxisFromString</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetAxisString">GetAxisString</see></seealso>
        public static extern void GetGamepadAxisFromString();

        /// <summary>
        /// <para>Get the SDL joystick layer bindings for a gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad.</param>
        /// <param name="count">a pointer filled in with the number of bindings returned.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadBinding">GamepadBinding</see> **) Returns a NULL terminated array of pointers to bindings or NULL on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information. This is a single allocation that should be freed with <see cref="CSDL.Memory.Free">Free</see> when it is no longer needed.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadBindings">SDL_GetGamepadBindings</seealso></SDLWiki>
        public static extern void GetGamepadBindings();

        /// <summary>
        /// <para>Get the current state of a button on a gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad.</param>
        /// <param name="button">a button index (one of the <see cref="CSDL.Input.GamepadButton">GamepadButton</see> values).</param>
        /// <returns>
        /// <para>(bool) Returns true if the button is pressed, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadButton">SDL_GetGamepadButton</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.HasButton">HasButton</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetAxis">GetAxis</see></seealso>
        public static extern void GetGamepadButton();

        /// <summary>
        /// <para>Convert a string into an <see cref="CSDL.Input.GamepadButton">GamepadButton</see> enum.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function is called internally to translate <c>SDL_Gamepad</c> mapping strings for the underlying joystick device into the consistent <c>SDL_Gamepad</c> mapping. You do not normally need to call this function unless you are parsing <c>SDL_Gamepad</c> mappings in your own code.</para>
        /// </remarks>
        /// <param name="str">string representing a <c>SDL_Gamepad</c> button.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadButton">GamepadButton</see>) Returns the <see cref="CSDL.Input.GamepadButton">GamepadButton</see> enum corresponding to the input string, or <see cref="CSDL.Input.GamepadButton.Invalid">Invalid</see> if no match was found.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadButtonFromString">SDL_GetGamepadButtonFromString</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetButtonString">GetButtonString</see></seealso>
        public static extern void GetGamepadButtonFromString();

        /// <summary>
        /// <para>Get the label of a button on a gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad.</param>
        /// <param name="button">a button index (one of the <see cref="CSDL.Input.GamepadButton">GamepadButton</see> values).</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadButtonLabel">GamepadButtonLabel</see>) Returns the <see cref="CSDL.Input.GamepadButtonLabel">GamepadButtonLabel</see> enum corresponding to the button label.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadButtonLabel">SDL_GetGamepadButtonLabel</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetButtonLabel">GetButtonLabel</see></seealso>
        public static extern void GetGamepadButtonLabel();

        /// <summary>
        /// <para>Get the label of a button on a gamepad.</para>
        /// </summary>
        /// <param name="type">the type of gamepad to check.</param>
        /// <param name="button">a button index (one of the <see cref="CSDL.Input.GamepadButton">GamepadButton</see> values).</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadButtonLabel">GamepadButtonLabel</see>) Returns the <see cref="CSDL.Input.GamepadButtonLabel">GamepadButtonLabel</see> enum corresponding to the button label.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadButtonLabelForType">SDL_GetGamepadButtonLabelForType</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetButtonLabel">GetButtonLabel</see></seealso>
        public static extern void GetGamepadButtonLabelForType();

        /// <summary>
        /// <para>Get the current state of a capsense on a gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad.</param>
        /// <param name="type">the type of capsense to query.</param>
        /// <returns>
        /// <para>(bool) Returns true if the capsense is touched, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.6.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadCapSense">SDL_GetGamepadCapSense</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.HasCapSense">HasCapSense</see></seealso>
        public static extern void GetGamepadCapSense();

        /// <summary>
        /// <para>Get the connection state of a gamepad.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.JoystickConnectionState">JoystickConnectionState</see>) Returns the connection state on success or <see cref="CSDL.Input.JoystickConnectionState.Invalid">Invalid</see> on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadConnectionState">SDL_GetGamepadConnectionState</seealso></SDLWiki>
        public static extern void GetGamepadConnectionState();

        /// <summary>
        /// <para>Get the firmware version of an opened gamepad, if available.</para>
        /// </summary>
        /// <remarks>
        /// <para>If the firmware version isn't available this function returns 0.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(<c>Uint16</c>) Returns the gamepad firmware version, or zero if unavailable.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadFirmwareVersion">SDL_GetGamepadFirmwareVersion</seealso></SDLWiki>
        public static extern void GetGamepadFirmwareVersion();

        /// <summary>
        /// <para>Get the <c>SDL_Gamepad</c> associated with a joystick instance ID, if it has been opened.</para>
        /// </summary>
        /// <param name="instance_id">the joystick instance ID of the gamepad.</param>
        /// <returns>
        /// <para>(<c>SDL_Gamepad</c> *) Returns an <c>SDL_Gamepad</c> on success or NULL on failure or if it hasn't been opened yet; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadFromID">SDL_GetGamepadFromID</seealso></SDLWiki>
        public static extern void GetGamepadFromID();

        /// <summary>
        /// <para>Get the <c>SDL_Gamepad</c> associated with a player index.</para>
        /// </summary>
        /// <param name="player_index">the player index, which different from the instance ID.</param>
        /// <returns>
        /// <para>(<c>SDL_Gamepad</c> *) Returns the <c>SDL_Gamepad</c> associated with a player index.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadFromPlayerIndex">SDL_GetGamepadFromPlayerIndex</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetPlayerIndex">GetPlayerIndex</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.PlayerIndex">PlayerIndex</see></seealso>
        public static extern void GetGamepadFromPlayerIndex();

        /// <summary>
        /// <para>Get the implementation-dependent GUID of a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.GUIDData">GUIDData</see>) Returns the GUID of the selected gamepad. If called on an invalid index, this function returns a zero GUID.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadGUIDForID">SDL_GetGamepadGUIDForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.GUIDData.ToString">ToString</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        public static extern void GetGamepadGUIDForID();

        /// <summary>
        /// <para>Get the instance ID of an opened gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad identifier previously returned by <see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see>.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.JoystickID">JoystickID</see>) Returns the instance ID of the specified gamepad on success or 0 on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadID">SDL_GetGamepadID</seealso></SDLWiki>
        public static extern void GetGamepadID();

        /// <summary>
        /// <para>Get the underlying joystick from a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function will give you a <c>SDL_Joystick</c> object, which allows you to use the <c>SDL_Joystick</c> functions with a <c>SDL_Gamepad</c> object. This would be useful for getting a joystick's position at any given time, even if it hasn't moved (moving it would produce an event, which would have the axis' value).</para>
        /// <para>The pointer returned is owned by the <c>SDL_Gamepad</c>. You should not call <see cref="CSDL.Input.JoystickDevice.DisposeResource">DisposeResource</see> on it, for example, since doing so will likely cause SDL to crash.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad object that you want to get a joystick from.</param>
        /// <returns>
        /// <para>(<c>SDL_Joystick</c> *) Returns an <c>SDL_Joystick</c> object, or NULL on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadJoystick">SDL_GetGamepadJoystick</seealso></SDLWiki>
        public static extern void GetGamepadJoystick();

        /// <summary>
        /// <para>Get the current mapping of a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>Details about mappings are discussed with <c>SDL_AddGamepadMapping</c>.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad you want to get the current mapping for.</param>
        /// <returns>
        /// <para>(char *) Returns a string that has the gamepad's mapping or NULL if no mapping is available; call <see cref="CSDL.Error.GetError">GetError</see> for more information. This should be freed with <see cref="CSDL.Memory.Free">Free</see> when it is no longer needed.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadMapping">SDL_GetGamepadMapping</seealso></SDLWiki>
        /// <seealso><c>SDL_AddGamepadMapping</c></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadItem.GetMapping">GetMapping</see></seealso>
        /// <seealso><c>SDL_GetGamepadMappingForGUID</c></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadItem.Mapping">Mapping</see></seealso>
        public static extern void GetGamepadMapping();

        /// <summary>
        /// <para>Get the gamepad mapping string for a given GUID.</para>
        /// </summary>
        /// <param name="guid">a structure containing the GUID for which a mapping is desired.</param>
        /// <returns>
        /// <para>(char *) Returns a mapping string or NULL on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information. This should be freed with <see cref="CSDL.Memory.Free">Free</see> when it is no longer needed.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadMappingForGUID">SDL_GetGamepadMappingForGUID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.JoystickItem.Guid">Guid</see></seealso>
        /// <seealso><see cref="CSDL.Input.JoystickDevice.Guid">Guid</see></seealso>
        public static extern void GetGamepadMappingForGUID();

        /// <summary>
        /// <para>Get the mapping of a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(char *) Returns the mapping string. Returns NULL if no mapping is available. This should be freed with <see cref="CSDL.Memory.Free">Free</see> when it is no longer needed.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadMappingForID">SDL_GetGamepadMappingForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Mapping">Mapping</see></seealso>
        public static extern void GetGamepadMappingForID();

        /// <summary>
        /// <para>Get the current gamepad mappings.</para>
        /// </summary>
        /// <param name="count">a pointer filled in with the number of mappings returned, can be NULL.</param>
        /// <returns>
        /// <para>(char **) Returns an array of the mapping strings, NULL-terminated, or NULL on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information. This is a single allocation that should be freed with <see cref="CSDL.Memory.Free">Free</see> when it is no longer needed.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadMappings">SDL_GetGamepadMappings</seealso></SDLWiki>
        public static extern void GetGamepadMappings();

        /// <summary>
        /// <para>Get the implementation-dependent name for an opened gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad identifier previously returned by <see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see>.</param>
        /// <returns>
        /// <para>(const char *) Returns the implementation dependent name for the gamepad, or NULL if there is no name or the identifier passed is invalid.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadName">SDL_GetGamepadName</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadItem.Name">Name</see></seealso>
        public static extern void GetGamepadName();

        /// <summary>
        /// <para>Get the implementation dependent name of a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(const char *) Returns the name of the selected gamepad. If no name can be found, this function returns NULL; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadNameForID">SDL_GetGamepadNameForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Name">Name</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        public static extern void GetGamepadNameForID();

        /// <summary>
        /// <para>Get the implementation-dependent path for an opened gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad identifier previously returned by <see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see>.</param>
        /// <returns>
        /// <para>(const char *) Returns the implementation dependent path for the gamepad, or NULL if there is no path or the identifier passed is invalid.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadPath">SDL_GetGamepadPath</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadItem.Path">Path</see></seealso>
        public static extern void GetGamepadPath();

        /// <summary>
        /// <para>Get the implementation dependent path of a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(const char *) Returns the path of the selected gamepad. If no path can be found, this function returns NULL; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadPathForID">SDL_GetGamepadPathForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Path">Path</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        public static extern void GetGamepadPathForID();

        /// <summary>
        /// <para>Get the player index of an opened gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>For XInput gamepads this returns the XInput user index.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(int) Returns the player index for gamepad, or -1 if it's not available.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadPlayerIndex">SDL_GetGamepadPlayerIndex</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.PlayerIndex">PlayerIndex</see></seealso>
        public static extern void GetGamepadPlayerIndex();

        /// <summary>
        /// <para>Get the player index of a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(int) Returns the player index of a gamepad, or -1 if it's not available.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadPlayerIndexForID">SDL_GetGamepadPlayerIndexForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetPlayerIndex">GetPlayerIndex</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        public static extern void GetGamepadPlayerIndexForID();

        /// <summary>
        /// <para>Get the battery state of a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>You should never take a battery status as absolute truth. Batteries (especially failing batteries) are delicate hardware, and the values reported here are best estimates based on what that hardware reports. It's not uncommon for older batteries to lose stored power much faster than it reports, or completely drain when reporting it has 20 percent left, etc.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <param name="percent">a pointer filled in with the percentage of battery life left, between 0 and 100, or NULL to ignore. This will be filled in with -1 we can't determine a value or there is no battery.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.PowerState">PowerState</see>) Returns the current battery state.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadPowerInfo">SDL_GetGamepadPowerInfo</seealso></SDLWiki>
        public static extern void GetGamepadPowerInfo();

        /// <summary>
        /// <para>Get the USB product ID of an opened gamepad, if available.</para>
        /// </summary>
        /// <remarks>
        /// <para>If the product ID isn't available this function returns 0.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(<c>Uint16</c>) Returns the USB product ID, or zero if unavailable.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadProduct">SDL_GetGamepadProduct</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadItem.Product">Product</see></seealso>
        public static extern void GetGamepadProduct();

        /// <summary>
        /// <para>Get the USB product ID of a gamepad, if available.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened. If the product ID isn't available this function returns 0.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(<c>Uint16</c>) Returns the USB product ID of the selected gamepad. If called on an invalid index, this function returns zero.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadProductForID">SDL_GetGamepadProductForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Product">Product</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        public static extern void GetGamepadProductForID();

        /// <summary>
        /// <para>Get the product version of an opened gamepad, if available.</para>
        /// </summary>
        /// <remarks>
        /// <para>If the product version isn't available this function returns 0.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(<c>Uint16</c>) Returns the USB product version, or zero if unavailable.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadProductVersion">SDL_GetGamepadProductVersion</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadItem.ProductVersion">ProductVersion</see></seealso>
        public static extern void GetGamepadProductVersion();

        /// <summary>
        /// <para>Get the product version of a gamepad, if available.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened. If the product version isn't available this function returns 0.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(<c>Uint16</c>) Returns the product version of the selected gamepad. If called on an invalid index, this function returns zero.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadProductVersionForID">SDL_GetGamepadProductVersionForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.ProductVersion">ProductVersion</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        public static extern void GetGamepadProductVersionForID();

        /// <summary>
        /// <para>Get the properties associated with an opened gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>These properties are shared with the underlying joystick object.</para>
        /// <para>The following read-only properties are provided by SDL:</para>
        /// <list type="bullet">
        /// <item><description><see cref="CSDL.Props.GamepadCapMonoLedBoolean">GamepadCapMonoLedBoolean</see>: true if this gamepad has an LED that has adjustable brightness</description></item>
        /// <item><description><see cref="CSDL.Props.GamepadCapRGBLedBoolean">GamepadCapRGBLedBoolean</see>: true if this gamepad has an LED that has adjustable color</description></item>
        /// <item><description><see cref="CSDL.Props.GamepadCapPlayerLedBoolean">GamepadCapPlayerLedBoolean</see>: true if this gamepad has a player LED</description></item>
        /// <item><description><see cref="CSDL.Props.GamepadCapRumbleBoolean">GamepadCapRumbleBoolean</see>: true if this gamepad has left/right rumble</description></item>
        /// <item><description><see cref="CSDL.Props.GamepadCapTriggerRumbleBoolean">GamepadCapTriggerRumbleBoolean</see>: true if this gamepad has simple trigger rumble</description></item>
        /// </list>
        /// </remarks>
        /// <param name="gamepad">a gamepad identifier previously returned by <see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see>.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.PropertiesID">PropertiesID</see>) Returns a valid property ID on success or 0 on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadProperties">SDL_GetGamepadProperties</seealso></SDLWiki>
        public static extern void GetGamepadProperties();

        /// <summary>
        /// <para>Get a list of currently connected gamepads.</para>
        /// </summary>
        /// <param name="count">a pointer filled in with the number of gamepads returned, may be NULL.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.JoystickID">JoystickID</see> *) Returns a 0 terminated array of joystick instance IDs or NULL on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information. This should be freed with <see cref="CSDL.Memory.Free">Free</see> when it is no longer needed.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepads">SDL_GetGamepads</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.HasAnyGamepad">HasAnyGamepad</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see></seealso>
        public static extern void GetGamepads();

        /// <summary>
        /// <para>Get the current state of a gamepad sensor.</para>
        /// </summary>
        /// <remarks>
        /// <para>The number of values and interpretation of the data is sensor dependent. See the remarks in <see cref="CSDL.Input.SensorType">SensorType</see> for details for each type of sensor.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad to query.</param>
        /// <param name="type">the type of sensor to query.</param>
        /// <param name="data">a pointer filled with the current sensor state.</param>
        /// <param name="num_values">the number of values to write to data.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadSensorData">SDL_GetGamepadSensorData</seealso></SDLWiki>
        public static extern void GetGamepadSensorData();

        /// <summary>
        /// <para>Get the data rate (number of events per second) of a gamepad sensor.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad to query.</param>
        /// <param name="type">the type of sensor to query.</param>
        /// <returns>
        /// <para>(float) Returns the data rate, or 0.0f if the data rate is not available.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadSensorDataRate">SDL_GetGamepadSensorDataRate</seealso></SDLWiki>
        public static extern void GetGamepadSensorDataRate();

        /// <summary>
        /// <para>Get the serial number of an opened gamepad, if available.</para>
        /// </summary>
        /// <remarks>
        /// <para>Returns the serial number of the gamepad, or NULL if it is not available.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(const char *) Returns the serial number, or NULL if unavailable.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadSerial">SDL_GetGamepadSerial</seealso></SDLWiki>
        public static extern void GetGamepadSerial();

        /// <summary>
        /// <para>Get the Steam Input handle of an opened gamepad, if available.</para>
        /// </summary>
        /// <remarks>
        /// <para>Returns an InputHandle_t for the gamepad that can be used with Steam Input API: https://partner.steamgames.com/doc/api/ISteamInput</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(<c>Uint64</c>) Returns the gamepad handle, or 0 if unavailable.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadSteamHandle">SDL_GetGamepadSteamHandle</seealso></SDLWiki>
        public static extern void GetGamepadSteamHandle();

        /// <summary>
        /// <para>Convert from an <see cref="CSDL.Input.GamepadAxis">GamepadAxis</see> enum to a string.</para>
        /// </summary>
        /// <param name="axis">an enum value for a given <see cref="CSDL.Input.GamepadAxis">GamepadAxis</see>.</param>
        /// <returns>
        /// <para>(const char *) Returns a string for the given axis, or NULL if an invalid axis is specified. The string returned is of the format used by <c>SDL_Gamepad</c> mapping strings.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadStringForAxis">SDL_GetGamepadStringForAxis</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetAxis">GetAxis</see></seealso>
        public static extern void GetGamepadStringForAxis();

        /// <summary>
        /// <para>Convert from an <see cref="CSDL.Input.GamepadButton">GamepadButton</see> enum to a string.</para>
        /// </summary>
        /// <param name="button">an enum value for a given <see cref="CSDL.Input.GamepadButton">GamepadButton</see>.</param>
        /// <returns>
        /// <para>(const char *) Returns a string for the given button, or NULL if an invalid button is specified. The string returned is of the format used by <c>SDL_Gamepad</c> mapping strings.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadStringForButton">SDL_GetGamepadStringForButton</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetButton">GetButton</see></seealso>
        public static extern void GetGamepadStringForButton();

        /// <summary>
        /// <para>Convert from an <see cref="CSDL.Input.GamepadType">GamepadType</see> enum to a string.</para>
        /// </summary>
        /// <param name="type">an enum value for a given <see cref="CSDL.Input.GamepadType">GamepadType</see>.</param>
        /// <returns>
        /// <para>(const char *) Returns a string for the given type, or NULL if an invalid type is specified. The string returned is of the format used by <c>SDL_Gamepad</c> mapping strings.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadStringForType">SDL_GetGamepadStringForType</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetType">GetType</see></seealso>
        public static extern void GetGamepadStringForType();

        /// <summary>
        /// <para>Get the current state of a finger on a touchpad on a gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad.</param>
        /// <param name="touchpad">a touchpad.</param>
        /// <param name="finger">a finger.</param>
        /// <param name="down">a pointer filled with true if the finger is down, false otherwise, may be NULL.</param>
        /// <param name="x">a pointer filled with the x position, normalized 0 to 1, with the origin in the upper left, may be NULL.</param>
        /// <param name="y">a pointer filled with the y position, normalized 0 to 1, with the origin in the upper left, may be NULL.</param>
        /// <param name="pressure">a pointer filled with pressure value, may be NULL.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadTouchpadFinger">SDL_GetGamepadTouchpadFinger</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetNumTouchpadFingers">GetNumTouchpadFingers</see></seealso>
        public static extern void GetGamepadTouchpadFinger();

        /// <summary>
        /// <para>Get the type of an opened gamepad.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadType">GamepadType</see>) Returns the gamepad type, or <see cref="CSDL.Input.GamepadType.Unknown">Unknown</see> if it's not available.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadType">SDL_GetGamepadType</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadItem.Type">Type</see></seealso>
        public static extern void GetGamepadType();

        /// <summary>
        /// <para>Get the type of a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadType">GamepadType</see>) Returns the gamepad type.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadTypeForID">SDL_GetGamepadTypeForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Type">Type</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadItem.RealType">RealType</see></seealso>
        public static extern void GetGamepadTypeForID();

        /// <summary>
        /// <para>Convert a string into <see cref="CSDL.Input.GamepadType">GamepadType</see> enum.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function is called internally to translate <c>SDL_Gamepad</c> mapping strings for the underlying joystick device into the consistent <c>SDL_Gamepad</c> mapping. You do not normally need to call this function unless you are parsing <c>SDL_Gamepad</c> mappings in your own code.</para>
        /// </remarks>
        /// <param name="str">string representing a <see cref="CSDL.Input.GamepadType">GamepadType</see> type.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadType">GamepadType</see>) Returns the <see cref="CSDL.Input.GamepadType">GamepadType</see> enum corresponding to the input string, or <see cref="CSDL.Input.GamepadType.Unknown">Unknown</see> if no match was found.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadTypeFromString">SDL_GetGamepadTypeFromString</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetTypeString">GetTypeString</see></seealso>
        public static extern void GetGamepadTypeFromString();

        /// <summary>
        /// <para>Get the USB vendor ID of an opened gamepad, if available.</para>
        /// </summary>
        /// <remarks>
        /// <para>If the vendor ID isn't available this function returns 0.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(<c>Uint16</c>) Returns the USB vendor ID, or zero if unavailable.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadVendor">SDL_GetGamepadVendor</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadItem.Vendor">Vendor</see></seealso>
        public static extern void GetGamepadVendor();

        /// <summary>
        /// <para>Get the USB vendor ID of a gamepad, if available.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened. If the vendor ID isn't available this function returns 0.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(<c>Uint16</c>) Returns the USB vendor ID of the selected gamepad. If called on an invalid index, this function returns zero.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetGamepadVendorForID">SDL_GetGamepadVendorForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Vendor">Vendor</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        public static extern void GetGamepadVendorForID();

        /// <summary>
        /// <para>Get the number of supported simultaneous fingers on a touchpad on a game gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad.</param>
        /// <param name="touchpad">a touchpad.</param>
        /// <returns>
        /// <para>(int) Returns number of supported simultaneous fingers.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetNumGamepadTouchpadFingers">SDL_GetNumGamepadTouchpadFingers</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetTouchpadFinger">GetTouchpadFinger</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetNumTouchpads">GetNumTouchpads</see></seealso>
        public static extern void GetNumGamepadTouchpadFingers();

        /// <summary>
        /// <para>Get the number of touchpads on a gamepad.</para>
        /// </summary>
        /// <param name="gamepad">a gamepad.</param>
        /// <returns>
        /// <para>(int) Returns number of touchpads.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetNumGamepadTouchpads">SDL_GetNumGamepadTouchpads</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetNumTouchpadFingers">GetNumTouchpadFingers</see></seealso>
        public static extern void GetNumGamepadTouchpads();

        /// <summary>
        /// <para>Get the type of an opened gamepad, ignoring any mapping override.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad object to query.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadType">GamepadType</see>) Returns the gamepad type, or <see cref="CSDL.Input.GamepadType.Unknown">Unknown</see> if it's not available.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetRealGamepadType">SDL_GetRealGamepadType</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadItem.RealType">RealType</see></seealso>
        public static extern void GetRealGamepadType();

        /// <summary>
        /// <para>Get the type of a gamepad, ignoring any mapping override.</para>
        /// </summary>
        /// <remarks>
        /// <para>This can be called before any gamepads are opened.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(<see cref="CSDL.Input.GamepadType">GamepadType</see>) Returns the gamepad type.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GetRealGamepadTypeForID">SDL_GetRealGamepadTypeForID</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadItem.Type">Type</see></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.RealType">RealType</see></seealso>
        public static extern void GetRealGamepadTypeForID();

        /// <summary>
        /// <para>Return whether a gamepad is currently connected.</para>
        /// </summary>
        /// <returns>
        /// <para>(bool) Returns true if a gamepad is connected, false otherwise.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HasGamepad">SDL_HasGamepad</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Gamepads.GetConnectedGamepads">GetConnectedGamepads</see></seealso>
        public static extern void HasGamepad();

        /// <summary>
        /// <para>Check if the given joystick is supported by the gamepad interface.</para>
        /// </summary>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(bool) Returns true if the given joystick is supported by the gamepad interface, false if it isn't or it's an invalid index.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_IsGamepad">SDL_IsGamepad</seealso></SDLWiki>
        /// <seealso><c>SDL_GetJoysticks</c></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice(uint)">GamepadDevice(uint)</see></seealso>
        public static extern void IsGamepad();

        /// <summary>
        /// <para>Open a gamepad for use.</para>
        /// </summary>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <returns>
        /// <para>(<c>SDL_Gamepad</c> *) Returns a gamepad identifier or NULL if an error occurred; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_OpenGamepad">SDL_OpenGamepad</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.DisposeResource">DisposeResource</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadItem.IsGamepad">IsGamepad</see></seealso>
        public static extern void OpenGamepad();

        /// <summary>
        /// <para>Reinitialize the SDL mapping database to its initial state.</para>
        /// </summary>
        /// <remarks>
        /// <para>This will generate gamepad events as needed if device mappings change.</para>
        /// </remarks>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_ReloadGamepadMappings">SDL_ReloadGamepadMappings</seealso></SDLWiki>
        public static extern void ReloadGamepadMappings();

        /// <summary>
        /// <para>Start a rumble effect on a gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>Each call to this function cancels any previous rumble effect, and calling it with 0 intensity stops any rumbling.</para>
        /// <para>This function requires you to process SDL events or call <see cref="CSDL.Input.Joysticks.Update">Update</see> to update rumble state.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad to vibrate.</param>
        /// <param name="low_frequency_rumble">the intensity of the low frequency (left) rumble motor, from 0 to 0xFFFF.</param>
        /// <param name="high_frequency_rumble">the intensity of the high frequency (right) rumble motor, from 0 to 0xFFFF.</param>
        /// <param name="duration_ms">the duration of the rumble effect, in milliseconds.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_RumbleGamepad">SDL_RumbleGamepad</seealso></SDLWiki>
        public static extern void RumbleGamepad();

        /// <summary>
        /// <para>Start a rumble effect in the gamepad's triggers.</para>
        /// </summary>
        /// <remarks>
        /// <para>Each call to this function cancels any previous trigger rumble effect, and calling it with 0 intensity stops any rumbling.</para>
        /// <para>Note that this is rumbling of the _triggers_ and not the gamepad as a whole. This is currently only supported on Xbox One gamepads. If you want the (more common) whole-gamepad rumble, use <see cref="CSDL.Input.GamepadDevice.Rumble">Rumble</see> instead.</para>
        /// <para>This function requires you to process SDL events or call <see cref="CSDL.Input.Joysticks.Update">Update</see> to update rumble state.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad to vibrate.</param>
        /// <param name="left_rumble">the intensity of the left trigger rumble motor, from 0 to 0xFFFF.</param>
        /// <param name="right_rumble">the intensity of the right trigger rumble motor, from 0 to 0xFFFF.</param>
        /// <param name="duration_ms">the duration of the rumble effect, in milliseconds.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_RumbleGamepadTriggers">SDL_RumbleGamepadTriggers</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Rumble">Rumble</see></seealso>
        public static extern void RumbleGamepadTriggers();

        /// <summary>
        /// <para>Send a gamepad specific effect packet.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad to affect.</param>
        /// <param name="data">the data to send to the gamepad.</param>
        /// <param name="size">the size of the data to send to the gamepad.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SendGamepadEffect">SDL_SendGamepadEffect</seealso></SDLWiki>
        public static extern void SendGamepadEffect();

        /// <summary>
        /// <para>Set the state of gamepad event processing.</para>
        /// </summary>
        /// <remarks>
        /// <para>If gamepad events are disabled, you must call <see cref="CSDL.Input.Gamepads.Update">Update</see> yourself and check the state of the gamepad when you want gamepad information.</para>
        /// </remarks>
        /// <param name="enabled">whether to process gamepad events or not.</param>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SetGamepadEventsEnabled">SDL_SetGamepadEventsEnabled</seealso></SDLWiki>
        /// <seealso><c>SDL_GamepadEventsEnabled</c></seealso>
        /// <seealso><see cref="CSDL.Input.Gamepads.Update">Update</see></seealso>
        public static extern void SetGamepadEventsEnabled();

        /// <summary>
        /// <para>Update a gamepad's LED color.</para>
        /// </summary>
        /// <remarks>
        /// <para>An example of a joystick LED is the light on the back of a PlayStation 4's DualShock 4 controller.</para>
        /// <para>For gamepads with a single color LED, the maximum of the RGB values will be used as the LED brightness.</para>
        /// </remarks>
        /// <param name="gamepad">the gamepad to update.</param>
        /// <param name="red">the intensity of the red LED.</param>
        /// <param name="green">the intensity of the green LED.</param>
        /// <param name="blue">the intensity of the blue LED.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SetGamepadLED">SDL_SetGamepadLED</seealso></SDLWiki>
        public static extern void SetGamepadLED();

        /// <summary>
        /// <para>Set the current mapping of a joystick or gamepad.</para>
        /// </summary>
        /// <remarks>
        /// <para>Details about mappings are discussed with <c>SDL_AddGamepadMapping</c>.</para>
        /// </remarks>
        /// <param name="instance_id">the joystick instance ID.</param>
        /// <param name="mapping">the mapping to use for this device, or NULL to clear the mapping.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SetGamepadMapping">SDL_SetGamepadMapping</seealso></SDLWiki>
        /// <seealso><c>SDL_AddGamepadMapping</c></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.Mapping">Mapping</see></seealso>
        public static extern void SetGamepadMapping();

        /// <summary>
        /// <para>Set the player index of an opened gamepad.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad object to adjust.</param>
        /// <param name="player_index">player index to assign to this gamepad, or -1 to clear the player index and turn off player LEDs.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SetGamepadPlayerIndex">SDL_SetGamepadPlayerIndex</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.GetPlayerIndex">GetPlayerIndex</see></seealso>
        public static extern void SetGamepadPlayerIndex();

        /// <summary>
        /// <para>Set whether data reporting for a gamepad sensor is enabled.</para>
        /// </summary>
        /// <param name="gamepad">the gamepad to update.</param>
        /// <param name="type">the type of sensor to enable/disable.</param>
        /// <param name="enabled">whether data reporting should be enabled.</param>
        /// <returns>
        /// <para>(bool) Returns true on success or false on failure; call <see cref="CSDL.Error.GetError">GetError</see> for more information.</para>
        /// </returns>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_SetGamepadSensorEnabled">SDL_SetGamepadSensorEnabled</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.HasSensor">HasSensor</see></seealso>
        /// <seealso><see cref="CSDL.Input.GamepadDevice.SensorEnabled">SensorEnabled</see></seealso>
        public static extern void SetGamepadSensorEnabled();

        /// <summary>
        /// <para>Manually pump gamepad updates if not using the loop.</para>
        /// </summary>
        /// <remarks>
        /// <para>This function is called automatically by the event loop if events are enabled. Under such circumstances, it will not be necessary to call this function.</para>
        /// </remarks>
        /// <threadsafety>It is safe to call this function from any thread.</threadsafety>
        /// <since>This function is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_UpdateGamepads">SDL_UpdateGamepads</seealso></SDLWiki>
        public static extern void UpdateGamepads();
    }
}
