// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.File {
    /// <summary>
    /// <para>Flags for path matching.</para>
    /// </summary>
    /// <since>This datatype is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_GlobFlags">SDL_GlobFlags</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.File.Path.GlobDirectory">GlobDirectory</see></seealso>
    /// <seealso><see cref="CSDL.File.Storage.GlobDirectory">GlobDirectory</see></seealso>
    [System.Flags]
    public enum GlobFlags : uint {
        Caseinsensitive = (1 << 0),
    }
}
