// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.File {
    /// <summary>
    /// <para>Types of filesystem entries.</para>
    /// </summary>
    /// <remarks>
    /// <para>Note that there may be other sorts of items on a filesystem: devices, named pipes, etc. They are currently reported as <see cref="Other"/>.</para>
    /// </remarks>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_PathType">SDL_PathType</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.File.PathInfo">PathInfo</see></seealso>
    public enum PathType {
        /// <summary>
        /// <para>path does not exist</para>
        /// </summary>
        None,
        /// <summary>
        /// <para>a normal file</para>
        /// </summary>
        File,
        /// <summary>
        /// <para>a directory</para>
        /// </summary>
        Directory,
        /// <summary>
        /// <para>something completely different like a device node (not a symlink, those are always followed)</para>
        /// </summary>
        Other,
    }
}
