// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Input {
    /// <summary>
    /// <para>An enum of some common joystick types.</para>
    /// </summary>
    /// <remarks>
    /// <para>In some cases, SDL can identify a low-level joystick as being a certain type of device, and will report it through <see cref="CSDL.Input.JoystickDevice.Type">Type</see> (or <see cref="CSDL.Input.JoystickItem.Type">Type</see>).</para>
    /// <para>This is by no means a complete list of everything that can be plugged into a computer.</para>
    /// <para>You may refer to <a href="https://learn.microsoft.com/en-us/windows/win32/xinput/xinput-and-controller-subtypes">XInput Controller Types</a> table for a general understanding of each joystick type.</para>
    /// </remarks>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_JoystickType">SDL_JoystickType</seealso></SDLWiki>
    public enum JoystickType {
        Unknown,
        Gamepad,
        Wheel,
        ArcadeStick,
        FlightStick,
        DancePad,
        Guitar,
        DrumKit,
        ArcadePad,
        Throttle,
        Count,
    }
}
