// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.Input {
    /// <summary>
    /// <para>An enum that describes the type of a touch device.</para>
    /// </summary>
    /// <since>This enum is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_TouchDeviceType">SDL_TouchDeviceType</seealso></SDLWiki>
    public enum TouchDeviceType {
        Invalid = -1,
        /// <summary>
        /// <para>touch screen with window-relative coordinates</para>
        /// </summary>
        Direct,
        /// <summary>
        /// <para>trackpad with absolute device coordinates</para>
        /// </summary>
        IndirectAbsolute,
        /// <summary>
        /// <para>trackpad with screen cursor-relative coordinates</para>
        /// </summary>
        IndirectRelative,
    }
}
