// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL.Video {
    internal static partial class SDL {
        [LibraryImport(SDLLibrary, EntryPoint = "SDL_AcquireCameraFrame"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Video.SurfaceData> AcquireCameraFrame(NativePtr<CSDL.Opaque.SdlCamera> camera, out ulong timestampNs);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_CloseCamera"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void CloseCamera(NativePtr<CSDL.Opaque.SdlCamera> camera);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCameraDriver"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<byte> GetCameraDriver(int index);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCameraFormat"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool GetCameraFormat(NativePtr<CSDL.Opaque.SdlCamera> camera, ref CSDL.Video.CameraSpec spec);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCameraID"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Video.CameraID GetCameraID(NativePtr<CSDL.Opaque.SdlCamera> camera);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCameraName"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<byte> GetCameraName(CSDL.Video.CameraID instanceID);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCameraPermissionState"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Video.CameraPermissionState GetCameraPermissionState(NativePtr<CSDL.Opaque.SdlCamera> camera);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCameraPosition"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.Video.CameraPosition GetCameraPosition(CSDL.Video.CameraID instanceID);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCameraProperties"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.PropertiesID GetCameraProperties(NativePtr<CSDL.Opaque.SdlCamera> camera);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCameras"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Video.CameraID> GetCameras(out int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCameraSupportedFormats"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial IntPtr GetCameraSupportedFormats(CSDL.Video.CameraID instanceID, out int count);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetCurrentCameraDriver"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<byte> GetCurrentCameraDriver();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetNumCameraDrivers"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial int GetNumCameraDrivers();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_OpenCamera"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial NativePtr<CSDL.Opaque.SdlCamera> OpenCamera(CSDL.Video.CameraID instanceID, in CSDL.Video.CameraSpec spec);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_OpenCamera"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static unsafe partial NativePtr<CSDL.Opaque.SdlCamera> OpenCameraNullable(CSDL.Video.CameraID instanceID, CSDL.Video.CameraSpec* spec);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ReleaseCameraFrame"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void ReleaseCameraFrame(NativePtr<CSDL.Opaque.SdlCamera> camera, NativePtr<CSDL.Video.SurfaceData> frame);

    }
}
