// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL {
    /// <summary>
    /// <para>The prototype for the log output callback function.</para>
    /// </summary>
    /// <param name="userData">what was passed as <c>userdata</c> to <c>SDL_SetLogOutputFunction</c>.</param>
    /// <param name="category">the category of the message.</param>
    /// <param name="priority">the priority of the message.</param>
    /// <param name="message">the message being output.</param>
    /// <remarks>
    /// <para>This function is called by SDL when there is new text to be logged. A mutex is held so that this function is never called by more than one thread at once.</para>
    /// </remarks>
    /// <version>
    /// <para>This datatype is available since SDL 3.2.0</para>
    /// </version>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_LogOutputFunction">SDL_LogOutputFunction</seealso></SDLWiki>
    public delegate void LogOutputFunction(object? userData, int category, CSDL.LogPriority priority, string message);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void SDL_LogOutputFunctionNative(nint userData, int category, CSDL.LogPriority priority, nint message);

    internal static class LogOutputFunctionWrapper {
        public static SDL_LogOutputFunctionNative Create(LogOutputFunction fn) {
            return (userDataPtr, category, priorityRaw, messagePtr) => {
                try {
                    object? userData = CallbackRegistry.GetUserdata(userDataPtr);
                    CSDL.LogPriority priority = priorityRaw;
                    string message = Marshal.PtrToStringUTF8(messagePtr);
                    fn(userData, category, priority, message);
                }
                catch (System.Exception ex) {
                    CSDL.Log.Error(ex, "Managed callback threw an exception.");
                    return;
                }
            };
        }
    }

}
