// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace CSDL {
    internal static partial class SDL {
        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetDefaultLogOutputFunction"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial SDL_LogOutputFunctionNative GetDefaultLogOutputFunction();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetLogOutputFunction"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void GetLogOutputFunction(out SDL_LogOutputFunctionNative callback, out IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_GetLogPriority"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CSDL.LogPriority GetLogPriority(int category);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_Log"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void Log([MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_Log"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void Log(NativePtr<byte> fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogCritical"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogCritical(int category, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogCritical"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogCritical(int category, NativePtr<byte> fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogDebug"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogDebug(int category, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogDebug"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogDebug(int category, NativePtr<byte> fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogError"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogError(int category, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogError"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogError(int category, NativePtr<byte> fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogInfo"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogInfo(int category, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogInfo"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogInfo(int category, NativePtr<byte> fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogMessage"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogMessage(int category, CSDL.LogPriority priority, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogMessage"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogMessage(int category, CSDL.LogPriority priority, NativePtr<byte> fmt);


        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogTrace"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogTrace(int category, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogTrace"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogTrace(int category, NativePtr<byte> fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogVerbose"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogVerbose(int category, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogVerbose"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogVerbose(int category, NativePtr<byte> fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogWarn"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogWarn(int category, [MarshalAs(UnmanagedType.LPUTF8Str)] string? fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_LogWarn"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void LogWarn(int category, NativePtr<byte> fmt);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_ResetLogPriorities"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void ResetLogPriorities();

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetLogOutputFunction"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void SetLogOutputFunction(SDL_LogOutputFunctionNative callback, IntPtr userData);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetLogPriorities"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void SetLogPriorities(CSDL.LogPriority priority);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetLogPriority"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial void SetLogPriority(int category, CSDL.LogPriority priority);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetLogPriorityPrefix"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetLogPriorityPrefix(CSDL.LogPriority priority, [MarshalAs(UnmanagedType.LPUTF8Str)] string? prefix);

        [LibraryImport(SDLLibrary, EntryPoint = "SDL_SetLogPriorityPrefix"), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        internal static partial CBool SetLogPriorityPrefix(CSDL.LogPriority priority, NativePtr<byte> prefix);

    }
}
