// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Input {
    public static partial class Macros {
        /// <summary>
        /// <para>Device can set autocenter.</para>
        /// </summary>
        /// <remarks>
        /// <para>Device supports setting autocenter.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_AUTOCENTER">SDL_HAPTIC_AUTOCENTER</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.HapticDevice.SetAutocenter">SetAutocenter</see></seealso>
        public const uint HapticAutocenter = (1u<<17);

        /// <summary>
        /// <para>Uses cartesian coordinates for the direction.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_CARTESIAN">SDL_HAPTIC_CARTESIAN</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.HapticDirection">HapticDirection</see></seealso>
        public const uint HapticCartesian = 1;

        /// <summary>
        /// <para>Constant effect supported.</para>
        /// </summary>
        /// <remarks>
        /// <para>Constant haptic effect.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_CONSTANT">SDL_HAPTIC_CONSTANT</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticCondition">HapticCondition</see></seealso>
        public const uint HapticConstant = (1u<<0);

        /// <summary>
        /// <para>Custom effect is supported.</para>
        /// </summary>
        /// <remarks>
        /// <para>User defined custom haptic effect.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_CUSTOM">SDL_HAPTIC_CUSTOM</seealso></SDLWiki>
        public const uint HapticCustom = (1u<<15);

        /// <summary>
        /// <para>Damper effect supported - uses axes velocity.</para>
        /// </summary>
        /// <remarks>
        /// <para>Condition haptic effect that simulates dampening. Effect is based on the axes velocity.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_DAMPER">SDL_HAPTIC_DAMPER</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticCondition">HapticCondition</see></seealso>
        public const uint HapticDamper = (1u<<8);

        /// <summary>
        /// <para>Friction effect supported - uses axes movement.</para>
        /// </summary>
        /// <remarks>
        /// <para>Condition haptic effect that simulates friction. Effect is based on the axes movement.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_FRICTION">SDL_HAPTIC_FRICTION</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticCondition">HapticCondition</see></seealso>
        public const uint HapticFriction = (1u<<10);

        /// <summary>
        /// <para>Device can set global gain.</para>
        /// </summary>
        /// <remarks>
        /// <para>Device supports setting the global gain.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_GAIN">SDL_HAPTIC_GAIN</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.HapticDevice.SetGain">SetGain</see></seealso>
        public const uint HapticGain = (1u<<16);

        /// <summary>
        /// <para>Inertia effect supported - uses axes acceleration.</para>
        /// </summary>
        /// <remarks>
        /// <para>Condition haptic effect that simulates inertia. Effect is based on the axes acceleration.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_INERTIA">SDL_HAPTIC_INERTIA</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticCondition">HapticCondition</see></seealso>
        public const uint HapticInertia = (1u<<9);

        /// <summary>
        /// <para>Used to play a device an infinite number of times.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_INFINITY">SDL_HAPTIC_INFINITY</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.HapticDevice.RunEffect">RunEffect</see></seealso>
        public const uint HapticInfinity = 4294967295U;

        /// <summary>
        /// <para>Left/Right effect supported.</para>
        /// </summary>
        /// <remarks>
        /// <para>Haptic effect for direct control over high/low frequency motors.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_LEFTRIGHT">SDL_HAPTIC_LEFTRIGHT</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticLeftRight">HapticLeftRight</see></seealso>
        public const uint HapticLeftright = (1u<<11);

        /// <summary>
        /// <para>Device can be paused.</para>
        /// </summary>
        /// <remarks>
        /// <para>Devices supports being paused.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_PAUSE">SDL_HAPTIC_PAUSE</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.HapticDevice.Pause">Pause</see></seealso>
        /// <seealso><see cref="CSDL.Input.HapticDevice.Resume">Resume</see></seealso>
        public const uint HapticPause = (1u<<19);

        /// <summary>
        /// <para>Uses polar coordinates for the direction.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_POLAR">SDL_HAPTIC_POLAR</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.HapticDirection">HapticDirection</see></seealso>
        public const uint HapticPolar = 0;

        /// <summary>
        /// <para>Ramp effect supported.</para>
        /// </summary>
        /// <remarks>
        /// <para>Ramp haptic effect.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_RAMP">SDL_HAPTIC_RAMP</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticRamp">HapticRamp</see></seealso>
        public const uint HapticRamp = (1u<<6);

        /// <summary>
        /// <para>Reserved for future use.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_RESERVED1">SDL_HAPTIC_RESERVED1</seealso></SDLWiki>
        public const uint HapticRESERVED1 = (1u<<12);

        /// <summary>
        /// <para>Reserved for future use.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_RESERVED2">SDL_HAPTIC_RESERVED2</seealso></SDLWiki>
        public const uint HapticRESERVED2 = (1u<<13);

        /// <summary>
        /// <para>Reserved for future use.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_RESERVED3">SDL_HAPTIC_RESERVED3</seealso></SDLWiki>
        public const uint HapticRESERVED3 = (1u<<14);

        /// <summary>
        /// <para>Sawtoothdown wave effect supported.</para>
        /// </summary>
        /// <remarks>
        /// <para>Periodic haptic effect that simulates saw tooth down waves.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_SAWTOOTHDOWN">SDL_HAPTIC_SAWTOOTHDOWN</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticPeriodic">HapticPeriodic</see></seealso>
        public const uint HapticSawtoothdown = (1u<<5);

        /// <summary>
        /// <para>Sawtoothup wave effect supported.</para>
        /// </summary>
        /// <remarks>
        /// <para>Periodic haptic effect that simulates saw tooth up waves.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_SAWTOOTHUP">SDL_HAPTIC_SAWTOOTHUP</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticPeriodic">HapticPeriodic</see></seealso>
        public const uint HapticSawtoothup = (1u<<4);

        /// <summary>
        /// <para>Sine wave effect supported.</para>
        /// </summary>
        /// <remarks>
        /// <para>Periodic haptic effect that simulates sine waves.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_SINE">SDL_HAPTIC_SINE</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticPeriodic">HapticPeriodic</see></seealso>
        public const uint HapticSine = (1u<<1);

        /// <summary>
        /// <para>Uses spherical coordinates for the direction.</para>
        /// </summary>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_SPHERICAL">SDL_HAPTIC_SPHERICAL</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.HapticDirection">HapticDirection</see></seealso>
        public const uint HapticSpherical = 2;

        /// <summary>
        /// <para>Spring effect supported - uses axes position.</para>
        /// </summary>
        /// <remarks>
        /// <para>Condition haptic effect that simulates a spring. Effect is based on the axes position.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_SPRING">SDL_HAPTIC_SPRING</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticCondition">HapticCondition</see></seealso>
        public const uint HapticSpring = (1u<<7);

        /// <summary>
        /// <para>Square wave effect supported.</para>
        /// </summary>
        /// <remarks>
        /// <para>Periodic haptic effect that simulates square waves.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_SQUARE">SDL_HAPTIC_SQUARE</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticPeriodic">HapticPeriodic</see></seealso>
        public const uint HapticSquare = (1u<<2);

        /// <summary>
        /// <para>Device can be queried for effect status.</para>
        /// </summary>
        /// <remarks>
        /// <para>Device supports querying effect status.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_STATUS">SDL_HAPTIC_STATUS</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.HapticDevice.GetEffectStatus">GetEffectStatus</see></seealso>
        public const uint HapticStatus = (1u<<18);

        /// <summary>
        /// <para>Use this value to play an effect on the steering wheel axis.</para>
        /// </summary>
        /// <remarks>
        /// <para>This provides better compatibility across platforms and devices as SDL will guess the correct axis.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_STEERING_AXIS">SDL_HAPTIC_STEERING_AXIS</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.HapticDirection">HapticDirection</see></seealso>
        public const uint HapticSteeringAxis = 3;

        /// <summary>
        /// <para>Triangle wave effect supported.</para>
        /// </summary>
        /// <remarks>
        /// <para>Periodic haptic effect that simulates triangular waves.</para>
        /// </remarks>
        /// <since>This macro is available since SDL 3.2.0</since>
        /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HAPTIC_TRIANGLE">SDL_HAPTIC_TRIANGLE</seealso></SDLWiki>
        /// <seealso><see cref="CSDL.Input.Macros.HapticPeriodic">HapticPeriodic</see></seealso>
        public const uint HapticTriangle = (1u<<3);

    }
}
