// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Input {
    /// <summary>
    /// <para>Type of haptic effect.</para>
    /// </summary>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HapticEffectType">SDL_HapticEffectType</seealso></SDLWiki>
    public readonly record struct HapticEffectType(ushort Value) {
        public static implicit operator ushort(HapticEffectType id) => id.Value;
        public static implicit operator HapticEffectType(ushort value) => new(value);
        public override string ToString() => Value.ToString();
    }
}
