// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Input {
    /// <summary>
    /// <para>Type of coordinates used for haptic direction.</para>
    /// </summary>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HapticDirectionType">SDL_HapticDirectionType</seealso></SDLWiki>
    public readonly record struct HapticDirectionType(byte Value) {
        public static implicit operator byte(HapticDirectionType id) => id.Value;
        public static implicit operator HapticDirectionType(byte value) => new(value);
        public override string ToString() => Value.ToString();
    }
}
