// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.


using System.Runtime.InteropServices;

namespace CSDL.Input {
    /// <summary>
    /// <para>Structure that represents a haptic direction.</para>
    /// </summary>
    /// <remarks>
    /// <para>This is the direction where the force comes from, instead of the direction in which the force is exerted.</para>
    /// <para>Directions can be specified by:</para>
    /// <list type="bullet">
    /// <item><description><see cref="CSDL.Input.Macros.HapticPolar">HapticPolar</see> : Specified by polar coordinates.</description></item>
    /// <item><description><see cref="CSDL.Input.Macros.HapticCartesian">HapticCartesian</see> : Specified by cartesian coordinates.</description></item>
    /// <item><description><see cref="CSDL.Input.Macros.HapticSpherical">HapticSpherical</see> : Specified by spherical coordinates.</description></item>
    /// </list>
    /// <para>Cardinal directions of the haptic device are relative to the positioning of the device. North is considered to be away from the user.</para>
    /// <para>The following diagram represents the cardinal directions:</para>
    /// <code>
    ///                .--.
    ///                |__| .-------.
    ///                |=.| |.-----.|
    ///                |--| ||     ||
    ///                |  | |'-----'|
    ///                |__|~')_____('
    ///                  [ COMPUTER ]
    /// 
    /// 
    ///                    North (0,-1)
    ///                        ^
    ///                        |
    ///                        |
    ///  (-1,0)  West &lt;----[ HAPTIC ]----> East (1,0)
    ///                        |
    ///                        |
    ///                        v
    ///                     South (0,1)
    /// 
    /// 
    ///                     [ USER ]
    ///                       \|||/
    ///                       (o o)
    ///                 ---ooO-(_)-Ooo---
    /// </code>
    /// <para>If type is <see cref="CSDL.Input.Macros.HapticPolar">HapticPolar</see>, direction is encoded by hundredths of a degree starting north and turning clockwise. <see cref="CSDL.Input.Macros.HapticPolar">HapticPolar</see> only uses the first <see cref="Dir"/> parameter. The cardinal directions would be:</para>
    /// <list type="bullet">
    /// <item><description>North: 0 (0 degrees)</description></item>
    /// <item><description>East: 9000 (90 degrees)</description></item>
    /// <item><description>South: 18000 (180 degrees)</description></item>
    /// <item><description>West: 27000 (270 degrees)</description></item>
    /// </list>
    /// <para>If type is <see cref="CSDL.Input.Macros.HapticCartesian">HapticCartesian</see>, direction is encoded by three positions (X axis, Y axis and Z axis (with 3 axes)). <see cref="CSDL.Input.Macros.HapticCartesian">HapticCartesian</see> uses the first three <see cref="Dir"/> parameters. The cardinal directions would be:</para>
    /// <list type="bullet">
    /// <item><description>North: 0,-1, 0</description></item>
    /// <item><description>East: 1, 0, 0</description></item>
    /// <item><description>South: 0, 1, 0</description></item>
    /// <item><description>West: -1, 0, 0</description></item>
    /// </list>
    /// <para>The Z axis represents the height of the effect if supported, otherwise it's unused. In cartesian encoding (1, 2) would be the same as (2, 4), you can use any multiple you want, only the direction matters.</para>
    /// <para>If type is <see cref="CSDL.Input.Macros.HapticSpherical">HapticSpherical</see>, direction is encoded by two rotations. The first two <see cref="Dir"/> parameters are used. The <see cref="Dir"/> parameters are as follows (all values are in hundredths of degrees):</para>
    /// <list type="bullet">
    /// <item><description>Degrees from (1, 0) rotated towards (0, 1).</description></item>
    /// <item><description>Degrees towards (0, 0, 1) (device needs at least 3 axes).</description></item>
    /// </list>
    /// <para>Example of force coming from the south with all encodings (force coming from the south means the user will have to pull the stick to counteract):</para>
    /// <code language="c">
    ///  SDL_HapticDirection direction;
    /// 
    ///  // Cartesian directions
    ///  direction.type = SDL_HAPTIC_CARTESIAN; // Using cartesian direction encoding.
    ///  direction.dir[0] = 0; // X position
    ///  direction.dir[1] = 1; // Y position
    ///  // Assuming the device has 2 axes, we don't need to specify third parameter.
    /// 
    ///  // Polar directions
    ///  direction.type = SDL_HAPTIC_POLAR; // We'll be using polar direction encoding.
    ///  direction.dir[0] = 18000; // Polar only uses first parameter
    /// 
    ///  // Spherical coordinates
    ///  direction.type = SDL_HAPTIC_SPHERICAL; // Spherical encoding
    ///  direction.dir[0] = 9000; // Since we only have two axes we don't need more parameters.
    /// </code>
    /// </remarks>
    /// <since>This struct is available since SDL 3.2.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3/SDL_HapticDirection">SDL_HapticDirection</seealso></SDLWiki>
    /// <seealso><see cref="CSDL.Input.Macros.HapticPolar">HapticPolar</see></seealso>
    /// <seealso><see cref="CSDL.Input.Macros.HapticCartesian">HapticCartesian</see></seealso>
    /// <seealso><see cref="CSDL.Input.Macros.HapticSpherical">HapticSpherical</see></seealso>
    /// <seealso><see cref="CSDL.Input.Macros.HapticSteeringAxis">HapticSteeringAxis</see></seealso>
    /// <seealso><see cref="CSDL.Input.HapticEffect">HapticEffect</see></seealso>
    /// <seealso><see cref="CSDL.Input.HapticDevice.NumAxes">NumAxes</see></seealso>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct HapticDirection {
        /// <summary>
        /// <para>The type of encoding.</para>
        /// </summary>
        public CSDL.Input.HapticDirectionType Type;

        /// <summary>
        /// <para>The encoded direction.</para>
        /// </summary>
        public unsafe fixed int Dir[3];

        /// <summary>
        /// <para>Gets the element at the specified index of Dir.</para>
        /// </summary>
        /// <seealso cref="Dir"/>
        public readonly unsafe int GetDir(int index) {
            if ((uint)index >= 3) throw new System.ArgumentOutOfRangeException(nameof(index));
            fixed (int* p = Dir) {
                return p[index];
            }
        }

    }
}
