// SPDX-FileCopyrightText: 2026 Christof Ignacy
// SPDX-License-Identifier: Zlib

// <auto-generated />
// Derived from SDL definitions.
// Please do not edit this file directly.

namespace CSDL.TTF {
    /// <summary>
    /// <para>The winding order of the vertices returned by <see cref="CSDL.TTF.TextObject.GetGPUDrawData">GetGPUDrawData</see></para>
    /// </summary>
    /// <since>This enum is available since SDL_ttf 3.0.0</since>
    /// <SDLWiki><seealso href="https://wiki.libsdl.org/SDL3_ttf/TTF_GPUTextEngineWinding">TTF_GPUTextEngineWinding</seealso></SDLWiki>
    public enum GPUTextEngineWinding {
        Invalid = -1,
        Clockwise,
        CounterClockwise,
    }
}
